(function(){
 const h=React.createElement,call=(op,args={})=>window.SoloHost.call(op,args),uid=()=>crypto.randomUUID();
 const blank={items:[],actors:[],events:[],dice:[],player:{items:[],slots:[]},combat:{order:[]},map:{tokens:[],terrain:[],w:1,h:1}};
 function useBattle(playerId){
  const [state,setState]=React.useState(blank);
  React.useEffect(()=>{let stopped=false,ticket=0;const load=async()=>{const seq=++ticket;try{const r=await call('battle.get',{playerId});if(r.ok&&!stopped&&seq===ticket)setState(r)}catch{}};load();const timer=setInterval(load,1400);window.addEventListener('solo-state',load);return()=>{stopped=true;clearInterval(timer);window.removeEventListener('solo-state',load)}},[playerId]);return state;
 }
 const defaults={side:320,dock:285,log:28,scale:100,zoom:36};
 function readLayout(){try{return {...defaults,...JSON.parse(localStorage.getItem('solo-battle-layout')||'{}')}}catch{return defaults}}
 window.SoloBattlePage=function(){
  const [playerId,setPlayerId]=React.useState(null),b=useBattle(playerId),C=window.SoloComponents;
  const [layout,setLayout]=React.useState(readLayout),[selection,setSelection]=React.useState(null),[targets,setTargets]=React.useState([]),[point,setPoint]=React.useState(null),[preview,setPreview]=React.useState(null),[msg,setMsg]=React.useState(''),[busy,setBusy]=React.useState(false),[autoDice,setAutoDice]=React.useState(false),[autoEnemy,setAutoEnemy]=React.useState(false),[resource,setResource]=React.useState(false),[slots,setSlots]=React.useState({}),[hover,setHover]=React.useState(null),[aimCells,setAimCells]=React.useState([]),[focusMap,setFocusMap]=React.useState(false),[inspected,setInspected]=React.useState(null);
  const locked=React.useRef(false),npcLock=React.useRef(false),previewSeq=React.useRef(0),aimSeq=React.useRef(0),aimTimer=React.useRef(),actionId=React.useRef(uid()),layoutRef=React.useRef(),stageRef=React.useRef(),narrativeRef=React.useRef(),dragCleanup=React.useRef(()=>{});
  const current=b.combat.order[b.combat.turnIndex],actor=b.actors.find(p=>p.id===b.playerId),sheet=b.player?.sheet,token=b.map.tokens.find(t=>t.id===b.playerId),myTurn=!!actor&&b.combat.active&&(current?.pcId===actor.id||current?.tokenId===actor.id),zoom=layout.zoom;
  React.useEffect(()=>{localStorage.setItem('solo-battle-layout',JSON.stringify(layout))},[layout]);
  React.useEffect(()=>()=>{clearTimeout(aimTimer.current);dragCleanup.current()},[]);
  const resetSelection=()=>{++previewSeq.current;++aimSeq.current;setSelection(null);setTargets([]);setPoint(null);setPreview(null);setAimCells([])};
  React.useEffect(resetSelection,[b.turnKey,b.playerId]);
  const invoke=async(op,args={})=>{if(locked.current)return;locked.current=true;setBusy(true);setMsg('');try{const r=await call(op,args);if(!r.ok)throw Error(r.error);window.dispatchEvent(new Event('solo-state'));return r}catch(e){setMsg(e.message)}finally{locked.current=false;setBusy(false)}};
  const input=(ids=targets,pt=point,ab=selection)=>({actorId:b.request?.actorId||b.playerId,abilityId:ab?.id,targetIds:ids,...pt});
  const preflight=async(ids,pt,ab)=>{const ticket=++previewSeq.current;setPreview(null);try{const legacy=b.request&&!b.request.battleAbility;const r=await call(legacy?'interaction.preview':'battle.preview',legacy?{id:b.request.id,targetIds:ids,...pt}:input(ids,pt,ab));if(ticket!==previewSeq.current)return;if(!r.ok)throw Error(r.error);if(legacy&&r.cells)r.area={cells:r.cells};setPreview(r);setMsg(r.summary||'目标已选择，确认后执行。')}catch(e){if(ticket===previewSeq.current)setMsg(e.message)}};
  const aim=async(ab,pt)=>{if(!ab?.shape||!token)return;const seq=++aimSeq.current;const from=ab.range===0?{x:token.x,y:token.y}:pt;const r=await call('map.area',{shape:ab.shape,size:ab.size||5,from,dir:pt.dir||'n'});if(r.ok&&seq===aimSeq.current)setAimCells(r.cells||[])};
  const choose=ab=>{actionId.current=uid();resetSelection();setSelection(ab);setMsg(ab.shape?'移动鼠标预览范围，点击固定位置。':ab.self?'对自身施放，确认后结算。':'点击地图中的目标；编号区分同名敌人。');if(ab.shape&&token)aim(ab,{x:token.x,y:token.y,dir:'n'});if(ab.self){setTargets([b.playerId]);preflight([b.playerId],null,ab)}};
  React.useEffect(()=>{if(b.request){const r=b.request,ab=r.battleAbility?(b.player.items.find(i=>i.id===r.battleAbility)||{id:'move',kind:'move',name:r.label}):{id:'request',kind:r.kind,name:r.label,count:r.count,shape:r.kind==='area'?(r.shape||'sphere'):null,range:r.range,size:r.size};choose(ab)}},[b.request?.id]);
  React.useEffect(()=>{if(autoEnemy&&b.combat.active&&!b.actors.some(p=>p.id===current?.pcId||p.id===current?.tokenId)&&!b.active&&!b.dice.length&&!b.request&&current&&!npcLock.current){npcLock.current=true;call('battle.enemy').then(r=>{if(!r.ok){setMsg(r.error);setAutoEnemy(false)}window.dispatchEvent(new Event('solo-state'))}).finally(()=>{npcLock.current=false})}},[autoEnemy,b.turnKey,b.events.length,b.dice.length,b.active?.id,b.request?.id]);
  const targetClick=t=>{setInspected(t.id);if(selection&&selection.kind!=='move'&&!selection.shape){const ids=(selection.count||1)>1?(targets.includes(t.id)?targets.filter(x=>x!==t.id):[...targets,t.id].slice(-(selection.count||1))):[t.id];setTargets(ids);preflight(ids,point,selection);return}if(selection?.shape){pointClick(t.x,t.y);return}if(t.kind==='pc'&&!b.request){setPlayerId(t.id);setMsg('已选择 '+t.name+(b.combat.active?'':'，点击地面自由移动。'))}else setMsg('已选中 '+t.name+' ['+t.id+']，可查看详情或向 DM 提问。')};
  const aimPoint=(x,y)=>{const dx=x-(token?.x||0),dy=y-(token?.y||0),dirs=['e','se','s','sw','w','nw','n','ne'];return {x,y,dir:dirs[(Math.round(Math.atan2(dy,dx)/(Math.PI/4))+8)%8]}};
  const pointClick=(x,y)=>{if(!selection){if(!b.combat.active&&actor)invoke('map.token.move',{id:actor.id,x,y});else if(myTurn)choose({id:'move',kind:'move',name:'移动'});if(myTurn&&!selection){const ab={id:'move',kind:'move',name:'移动'},pt=aimPoint(x,y);setPoint(pt);preflight([],pt,ab)}return}const pt=aimPoint(x,y);setPoint(pt);setAimCells([]);if(selection.shape||selection.kind==='move')preflight(targets,pt,selection)};
  const hoverCell=(x,y)=>{if(!selection?.shape||point)return;clearTimeout(aimTimer.current);aimTimer.current=setTimeout(()=>aim(selection,aimPoint(x,y)).catch(()=>{}),60)};
  const confirm=async()=>{if(!preview||!selection)return;if(preview.needsDM){const r=b.request?{request:b.request}:await invoke('battle.begin',{actorId:b.playerId,abilityId:selection.id});if(r&&await invoke('interaction.answer',{id:r.request.id,targetIds:targets,...point}))resetSelection();return}const r=await invoke(b.request?'interaction.answer':'battle.submit',b.request?{id:b.request.id,targetIds:targets,...point,autoDice}:{...input(),version:preview.version,actionId:actionId.current,autoDice});if(r){resetSelection();setMsg('操作已记录。可继续行动，完成后点击结束回合交给 DM。')}};
  const endTurn=async()=>{const r=await invoke('battle.endTurn',{turnKey:b.turnKey});if(r){resetSelection();setMsg('回合已提交，DM 正在读取最新角色卡与地图。');call('session.resume').then(r=>{if(!r.ok)setMsg('回合已保存；DM 暂未续接：'+r.error);window.dispatchEvent(new Event('solo-state'))}).catch(e=>setMsg('回合已保存；DM 连接失败：'+e.message))}};
  const resize=(kind,e)=>{const rect=(kind==='side'?layoutRef:kind==='dock'?stageRef:narrativeRef).current.getBoundingClientRect();setLayout(old=>({...old,[kind]:kind==='side'?Math.max(230,Math.min(rect.width*.48,rect.right-e.clientX)):kind==='dock'?Math.max(175,Math.min(rect.height*.65,rect.bottom-e.clientY)):Math.max(18,Math.min(60,100*(rect.bottom-e.clientY)/rect.height))}))};
  const divider=(kind,label)=>h('div',{className:'battle-divider '+kind,role:'separator',tabIndex:0,'aria-label':label,'aria-orientation':kind==='side'?'vertical':'horizontal',onPointerDown:e=>{dragCleanup.current();e.currentTarget.setPointerCapture(e.pointerId);const move=p=>resize(kind,p),stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);window.removeEventListener('pointercancel',stop)};dragCleanup.current=stop;window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop);window.addEventListener('pointercancel',stop);e.preventDefault()},onKeyDown:e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const delta=['ArrowLeft','ArrowUp'].includes(e.key)?10:-10;setLayout(v=>({...v,[kind]:Math.max(kind==='side'?230:kind==='dock'?175:18,Math.min(kind==='side'?550:kind==='dock'?460:60,v[kind]+delta))}))}}});
  const map=b.map,tiles=[];for(let y=0;y<map.h;y++)for(let x=0;x<map.w;x++){const t=map.terrain[y]?.[x]||'.',wall=['#','b','c',' '].includes(t),classes='ink-cell '+(wall?'wall':t==='~'||t==='W'?'water':t==='+'?'door':'floor');tiles.push(h('rect',{key:x+':'+y,className:classes,x:x*zoom,y:y*zoom,width:zoom,height:zoom,onMouseEnter:()=>hoverCell(x,y),onClick:()=>pointClick(x,y)}));if(!wall)for(const [dx,dy,x1,y1,x2,y2] of [[0,-1,0,0,1,0],[1,0,1,0,1,1],[0,1,0,1,1,1],[-1,0,0,0,0,1]])if(['#','b','c',' '].includes(map.terrain[y+dy]?.[x+dx]||' '))tiles.push(h('line',{key:'l'+x+','+y+','+dx+','+dy,x1:(x+x1)*zoom,y1:(y+y1)*zoom,x2:(x+x2)*zoom,y2:(y+y2)*zoom,className:'ink-wall-edge'}));}
  const cells=preview?.area?.cells||preview?.path||aimCells,persistentCells=(b.effects||[]).filter(e=>e.mapId===b.map.id&&e.area?.cells).flatMap(e=>e.area.cells);
  const mapView=h('div',{className:'battle-map-scroll',onWheel:e=>{if(e.ctrlKey){e.preventDefault();setLayout(v=>({...v,zoom:Math.max(20,Math.min(72,v.zoom+(e.deltaY>0?-2:2)))}))}} },h('svg',{className:'ink-map',width:map.w*zoom,height:map.h*zoom,viewBox:'0 0 '+map.w*zoom+' '+map.h*zoom,role:'img','aria-label':'手绘战术地图'},h('defs',null,h('pattern',{id:'ink-hatch',width:9,height:9,patternUnits:'userSpaceOnUse',patternTransform:'rotate(28)'},h('rect',{width:9,height:9,fill:'#ddd4bb'}),h('path',{d:'M0 0V9 M4 0V9',stroke:'#746e61',strokeWidth:.7}))),map.background?h('image',{href:map.background.url,width:map.w*zoom,height:map.h*zoom,preserveAspectRatio:'none'}):null,h('g',{className:map.background?'ink-pdf-grid':''},tiles),selection?.range&&token?h('rect',{className:'battle-cast-range',x:(token.x+.5-selection.range/5)*zoom,y:(token.y+.5-selection.range/5)*zoom,width:selection.range/5*zoom*2,height:selection.range/5*zoom*2}):null,persistentCells.map((p,i)=>h('rect',{key:'effect'+i,x:p.x*zoom,y:p.y*zoom,width:zoom,height:zoom,className:'battle-effect-cell'})),cells.map((p,i)=>h('rect',{key:'area'+i,x:p.x*zoom,y:p.y*zoom,width:zoom,height:zoom,className:'battle-range'})),map.tokens.filter(t=>!t.hidden).map(t=>h('g',{key:t.id,role:'button',tabIndex:0,'aria-label':t.name+' · '+t.id,onMouseEnter:()=>setHover(t),onMouseLeave:()=>setHover(null),onFocus:()=>setHover(t),onBlur:()=>setHover(null),onClick:e=>{e.stopPropagation();targetClick(t)},onKeyDown:e=>{if(e.key==='Enter')targetClick(t)},className:'battle-token '+t.kind+(targets.includes(t.id)?' selected':'')+(t.id===b.actorId?' current':''),transform:'translate('+((t.x+.5)*zoom)+' '+((t.y+.5)*zoom)+')'},h('title',null,t.name+' ['+t.id+']\nAC '+(t.ac??'待查')+' · HP '+(t.hp??'待查')+'/'+(t.max??'—')+'\n先攻 '+(t.dex??'待查')+' · 豁免 '+JSON.stringify(t.saves||{})),h('circle',{r:zoom*.38}),h('text',{textAnchor:'middle',dy:4},t.name.slice(0,2)),h('text',{className:'battle-token-label',textAnchor:'middle',y:zoom*.68},t.kind==='pc'?t.name.slice(0,2):t.id.slice(-5)),t.hp!=null&&t.max?h('line',{x1:-zoom*.3,y1:-zoom*.47,x2:zoom*.3,y2:-zoom*.47,className:'battle-hp-track'}):null,t.hp!=null&&t.max?h('line',{x1:-zoom*.3,y1:-zoom*.47,x2:-zoom*.3+zoom*.6*Math.max(0,t.hp/t.max),y2:-zoom*.47,className:'battle-hp-value'}):null))));
  const req=b.dice[0],economy=b.combat.order.find(e=>e.pcId===b.playerId||e.tokenId===b.playerId)?.econ||{},selectedToken=b.map.tokens.find(t=>t.id===inspected),abilities=b.player?.items||[];
  const controls=h('div',{className:'battle-selection-controls'},
   selection?h('div',{className:'battle-confirm'},h('span',null,selection.name+' · '+msg),h('button',{disabled:busy||!preview,onClick:confirm},preview?.needsDM?'交给 DM 裁定':'确认执行'),h('button',{onClick:()=>{resetSelection();if(b.request)invoke('interaction.cancel',{id:b.request.id})}},'取消选择')):h('div',{className:'battle-message',role:'status'},msg||'选择动作或法术，再在地图中选择目标。'),
   req?h('div',{className:'battle-dice',role:'status'},h('b',null,req.label),h('span',null,req.expr+(req.dc!=null?' · DC '+req.dc:'')),h('button',{disabled:busy,onClick:()=>invoke('dice.answer',{id:req.id})},'投掷并继续'),h('small',null,b.dice.length>1?'后续 '+(b.dice.length-1)+' 条依次进行':'系统自动记录结果')):null,
   b.active?.reaction?h('div',{className:'battle-reaction'},h('b',null,b.active.reaction.label),h('button',{disabled:busy,onClick:()=>invoke('battle.reaction',{actionId:b.active.id,accept:true})},'使用反应'),h('button',{disabled:busy,onClick:()=>invoke('battle.reaction',{actionId:b.active.id,accept:false})},'放弃')):null);
  const hud=h('section',{className:'battle-dock',style:{height:layout.dock+'px'}},h('div',{className:'battle-dock-content',style:{zoom:layout.scale/100}},
   h('div',{className:'battle-player-strip'},h('div',{className:'battle-portrait',onClick:()=>actor&&window.SoloOpenPage?.({id:'card-'+actor.id,title:actor.name,kind:'character',actorId:actor.id}),role:'button',tabIndex:0,onKeyDown:e=>{if(e.key==='Enter'&&actor)window.SoloOpenPage?.({id:'card-'+actor.id,title:actor.name,kind:'character',actorId:actor.id})}},actor?.name?.slice(0,1)||'♜'),
    h('div',{className:'battle-player-name'},h('select',{'aria-label':'当前角色',value:b.playerId||'',onChange:e=>{setPlayerId(e.target.value);resetSelection()}},b.actors.map(a=>h('option',{key:a.id,value:a.id},a.name))),h('small',null,myTurn?'你的回合':b.combat.active?'等待 · '+(current?.name||'先攻'):'自由探索'),h('button',{className:'character-expand',onClick:()=>actor&&window.SoloOpenPage?.({id:'card-'+actor.id,title:actor.name,kind:'character',actorId:actor.id})},'角色卡 ↗')),
    sheet?h(window.SoloHealthBlock,{s:sheet,compact:true}):null,
    h('div',{className:'battle-ac',title:sheet?.acBreakdown||''},h('b',null,sheet?.ac??'—'),h('small',null,'AC')),
    h('div',{className:'battle-economy'},h('span',{className:economy.action?'spent':''},'● 动作 '+(economy.action?'已用':'可用')),h('span',{className:economy.bonus?'spent':''},'◆ 附赠 '+(economy.bonus?'已用':'可用')),h('span',{className:economy.reaction?'spent':''},'↶ 反应 '+(economy.reaction?'已用':'可用')),h('span',null,'↟ 移动 '+Math.max(0,(token?.speed||30)+(economy.extraMove||0)-(economy.move||0))+'尺')),
    h('button',{className:'battle-end-turn',disabled:busy||!myTurn||!!b.active||!!b.request||b.dice.length>0,onClick:endTurn},h('b',null,'结束我的回合'),h('small',null,'提交状态给 DM'))),
   h('div',{className:'battle-spell-resources'},(b.player?.slots||[]).map(s=>h('span',{key:s.lv,className:'battle-slot'},s.lv+'环 ',h('b',null,s.remaining==null?'待确认':s.remaining+'/'+s.max))), (b.player?.slots||[]).length?h('button',{onClick:()=>{setSlots(Object.fromEntries(b.player.slots.map(s=>[s.lv,s.remaining??s.max])));setResource(true)}},'确认 / 调整剩余法术位'):null,h('label',null,h('input',{type:'checkbox',checked:autoDice,onChange:e=>setAutoDice(e.target.checked)}),'行动自动投骰'),h('label',null,h('input',{type:'checkbox',checked:autoEnemy,onChange:e=>setAutoEnemy(e.target.checked)}),'连续敌方基础回合')),
   h('div',{className:'battle-actionbar'},h('button',{disabled:busy||!myTurn||!!b.active||!!b.request,onClick:()=>choose({id:'move',kind:'move',name:'移动'})},h('i',null,'↟'),h('b',null,'移动')),['dash','disengage'].map(kind=>h('button',{key:kind,disabled:busy||!myTurn||!!b.active||!!b.request||!!economy.action,onClick:()=>invoke('battle.utility',{actorId:b.playerId,kind})},h('i',null,kind==='dash'?'»':'↶'),h('b',null,kind==='dash'?'疾走':'撤离'))),actor?.hp.current===0?h('button',{disabled:busy||!myTurn||!!b.active,onClick:()=>invoke('battle.deathSave')},'死亡豁免'):null,
    abilities.map(ab=>h('button',{key:ab.id,title:ab.name+' · '+(ab.range||0)+'尺\n'+(ab.fx||''),className:'spell-action '+(ab.id==='weapon'?'weapon':ab.level?'leveled':'cantrip')+(selection?.id===ab.id?' selected':''),disabled:busy||!myTurn||!!b.active||!!b.request,onClick:()=>choose(ab)},h('i',null,ab.id==='weapon'?'⚔':ab.shape?'◉':ab.kind==='heal'?'✚':ab.kind==='temp'?'◆':'✦'),h('b',null,ab.name),h('small',null,ab.kind==='dm'?'DM 裁定':ab.id==='weapon'?'攻击':ab.level?ab.level+'环 · '+(ab.cost==='bonus'?'附赠':'动作'):'戏法'))))),controls);
  const targetInfo=selectedToken&&!selection?h('div',{className:'battle-inspector'},h('b',null,selectedToken.name+' · '+selectedToken.id),h('span',null,'AC '+(selectedToken.ac??'待查')+' · HP '+(selectedToken.hp??'—')+'/'+(selectedToken.max??'—')),h('button',{disabled:busy,onClick:()=>invoke('ai.chat',{message:'我指向地图中的「'+selectedToken.name+'」（唯一ID '+selectedToken.id+'，位置 '+selectedToken.x+','+selectedToken.y+'）。请根据当前可见信息介绍它或回应交互，不替我消耗动作。'})},'向 DM 询问'),h('button',{onClick:()=>setInspected(null)},'×')):null;
  const mapStage=h('main',{className:'battle-stage',ref:stageRef},h('div',{className:'battle-map-heading'},h('b',null,b.map.name||'战术地图'),h('small',null,'每格5尺 · Ctrl+滚轮缩放'),h('button',{disabled:!token,onClick:()=>{const el=stageRef.current?.querySelector('.battle-map-scroll');if(el&&token)el.scrollTo({left:(token.x+.5)*zoom-el.clientWidth/2,top:(token.y+.5)*zoom-el.clientHeight/2,behavior:'smooth'})}},'定位角色'),h('button',{onClick:()=>setFocusMap(v=>!v)},focusMap?'显示对话与记录':'专注地图'),h('input',{'aria-label':'地图缩放',type:'range',min:20,max:72,value:zoom,onChange:e=>setLayout(v=>({...v,zoom:Number(e.target.value)}))})),
   (b.effects||[]).filter(e=>e.temp==null&&e.maxHpBonus==null).length?h('div',{className:'battle-effects'},b.effects.filter(e=>e.temp==null&&e.maxHpBonus==null).map(e=>h('span',{key:e.id},e.name+(e.concentration?' · 专注':'')+(e.rounds!=null?' · '+e.rounds+'轮':e.remainingSeconds!=null?' · '+Math.ceil(e.remainingSeconds/60)+'分钟':'')))):null,
   mapView,targetInfo,hover?h('div',{className:'battle-hover'},h('b',null,hover.name+' · '+hover.id),h('span',null,'AC '+(hover.ac??'待查')+' · HP '+(hover.hp??'待查')+'/'+(hover.max??'—')),h('small',null,'先攻 '+(hover.dex??'待查')+' · 豁免 '+Object.entries(hover.saves||{}).map(([k,v])=>k+' '+(v>=0?'+':'')+v).join(' / '))):null,divider('dock','调整操作栏高度'),hud);
  const narrative=h('aside',{className:'battle-narrative',ref:narrativeRef},h('section',{className:'battle-chat',style:{flex:'1 1 0'}},h(C.AIPanel,{})),divider('log','调整战斗记录高度'),h('section',{className:'battle-events',style:{height:layout.log+'%'}},h('header',null,'战斗记录'),b.events.slice(-40).reverse().map(e=>h('article',{key:e.id},h('small',null,'R'+e.round),e.text))));
  return h('div',{className:'battle-page game-hud'},h('div',{className:'battle-top'},h('span',{className:'battle-mode'},b.combat.active?'回合制 · 第 '+b.combat.round+' 轮':'自由探索'),h('button',{disabled:busy||!!b.active||!!b.request||b.dice.length>0,onClick:()=>invoke('combat.mode',{mode:b.combat.active?'free':'turn'})},b.combat.active?'切换自由移动':'开启回合制'),h('div',{className:'battle-initiative'},b.combat.order.map(e=>h('span',{key:e.id,className:e.id===current?.id?'on':''},e.name+' '+e.init))),!myTurn&&b.combat.active?h('button',{disabled:busy||!!b.active,onClick:()=>invoke('battle.enemy')},'推进敌方行动'):null,h('label',{className:'battle-ui-scale'},'操作栏缩放',h('input',{'aria-label':'操作栏缩放',type:'range',min:80,max:135,value:layout.scale,onChange:e=>setLayout(v=>({...v,scale:Number(e.target.value)}))})),h('button',{disabled:busy||!!b.active||!!b.request||b.dice.length>0,onClick:()=>invoke('ai.chat',{message:'请核对当前角色卡和已经发生的剧情奖励/穿戴。先读取 party.sheet 和已有对话，只补写明确已获得却缺失的物品，已明确穿戴的才装备；用 character.update 或 dm.action(action=character)，稳定 changeId，不重复发物品。不凭猜测增加 AC。若无法从对话确定，请说明缺少哪条依据。请核对之前提到的皮甲、盾牌，并区分护盾术。'})},'核对剧情装备'),h('button',{onClick:()=>{setLayout(defaults);setFocusMap(false)}},'重置布局')),
   h('div',{className:'battle-layout'+(focusMap?' map-focus':''),ref:layoutRef,style:{'--battle-sidebar':layout.side+'px'}},mapStage,!focusMap?divider('side','调整地图与对话宽度'):null,!focusMap?narrative:null),
   resource?h('div',{className:'roll-request-modal'},h('div',{className:'roll-request-card'},h('h3',null,'确认真实剩余法术位'),h('p',null,'填写当前战役实际余额；此操作不会视为休息。'),(b.player?.slots||[]).map(s=>h('label',{key:s.lv},s.lv+'环（容量 '+s.max+'）',h('input',{type:'number',min:0,max:s.max,value:slots[s.lv]??0,onChange:e=>setSlots({...slots,[s.lv]:Number(e.target.value)})}))),h('button',{onClick:()=>setResource(false)},'取消'),h('button',{disabled:busy,onClick:async()=>{if(await invoke('battle.resources',{actorId:b.playerId,slots}))setResource(false)}},'确认余额'))):null);
 };
 window.SoloCharacterPage=function({actorId}){const [sheet,setSheet]=React.useState(null);React.useEffect(()=>{const load=()=>call('party.sheet',{id:actorId}).then(r=>{if(r.ok)setSheet(r.sheet)});load();window.addEventListener('solo-state',load);return()=>window.removeEventListener('solo-state',load)},[actorId]);return sheet?h('div',{className:'solo-card-page'},h(window.SoloComponents.Detail,{s:sheet,onReload:()=>call('party.sheet',{id:actorId}).then(r=>setSheet(r.sheet))})):h('p',null,'正在读取角色卡…')};
})();
