(function(){
 const h=React.createElement;
 const call=(op,args={})=>window.SoloHost.call(op,args);
 const uid=()=>crypto.randomUUID();
 const blank={items:[],actors:[],events:[],dice:[],combat:{order:[]},map:{tokens:[],terrain:[],w:1,h:1}};
 function useBattle(){const [state,setState]=React.useState(blank);React.useEffect(()=>{let stopped=false;const load=()=>call('battle.get').then(r=>{if(r.ok&&!stopped)setState(r)}).catch(()=>{});load();const timer=setInterval(load,1400);window.addEventListener('solo-state',load);return()=>{stopped=true;clearInterval(timer);window.removeEventListener('solo-state',load)}},[]);return state;}
 window.SoloBattlePage=function(){
  const b=useBattle(),C=window.SoloComponents,[selection,setSelection]=React.useState(null),[targets,setTargets]=React.useState([]),[point,setPoint]=React.useState(null),[preview,setPreview]=React.useState(null),[msg,setMsg]=React.useState(''),[busy,setBusy]=React.useState(false),[autoDice,setAutoDice]=React.useState(false),[autoEnemy,setAutoEnemy]=React.useState(false),[zoom,setZoom]=React.useState(32),[resource,setResource]=React.useState(false),[slots,setSlots]=React.useState({}),[freeActor,setFreeActor]=React.useState(null),[hover,setHover]=React.useState(null);
  const npcLock=React.useRef(false),previewSeq=React.useRef(0),actionId=React.useRef(uid());
  const actor=b.actors.find(p=>p.id===b.actorId),token=b.map.tokens.find(t=>t.id===b.actorId),current=b.combat.order[b.combat.turnIndex],displayActor=actor||b.actors[0];
  const invoke=async(op,args={})=>{if(busy)return;setBusy(true);setMsg('');try{const r=await call(op,args);if(!r.ok)throw Error(r.error);window.dispatchEvent(new Event('solo-state'));return r}catch(e){setMsg(e.message)}finally{setBusy(false)}};
  React.useEffect(()=>{setSelection(null);setTargets([]);setPoint(null);setPreview(null)},[b.actorId,b.combat.round]);
  React.useEffect(()=>{if(b.request){const r=b.request,ab=r.battleAbility?(b.items.find(i=>i.id===r.battleAbility)||{id:'move',kind:'move',name:r.label}):{id:'request',kind:r.kind,name:r.label,count:r.count,shape:r.kind==='area'?(r.shape||'sphere'):null};choose(ab)}},[b.request?.id]);
  React.useEffect(()=>{if(autoEnemy&&b.combat.active&&!actor&&!b.active&&!b.dice.length&&current&&!npcLock.current){npcLock.current=true;call('battle.enemy').then(r=>{if(!r.ok){setMsg(r.error);setAutoEnemy(false)}window.dispatchEvent(new Event('solo-state'))}).finally(()=>{npcLock.current=false})}},[autoEnemy,b.combat.updatedAt,b.active?.id,b.events.length,b.dice.length,actor?.id]);
  const input=(ids=targets,pt=point,ab=selection)=>({actorId:b.request?.actorId||b.actorId,abilityId:ab?.id,targetIds:ids,...pt});
  const preflight=async(ids,pt,ab)=>{const ticket=++previewSeq.current;setPreview(null);try{const legacy=b.request&&!b.request.battleAbility;const r=await call(legacy?'interaction.preview':'battle.preview',legacy?{id:b.request.id,targetIds:ids,...pt}:input(ids,pt,ab));if(legacy&&r.cells)r.area={cells:r.cells};if(ticket!==previewSeq.current)return;if(!r.ok)throw Error(r.error);setPreview(r);setMsg(r.summary||'预览就绪')}catch(e){if(ticket===previewSeq.current)setMsg(e.message)}};
  const choose=ab=>{actionId.current=uid();setSelection(ab);setTargets([]);setPoint(null);setPreview(null);setMsg(ab.kind==='dm'?'选择目标后交给 DM 裁定。':ab.shape?'点击地图选择范围原点与方向。':ab.self?'确认对自身施放。':'点击地图中的目标。');if(ab.self){setTargets([b.actorId]);preflight([b.actorId],null,ab)}};
  const targetClick=t=>{if(!b.combat.active&&!b.request){if(t.kind==='pc'){setFreeActor(t.id);setMsg('点击地面自由移动 '+t.name)}return}if(!selection)return;const ids=(selection.count||1)>1?(targets.includes(t.id)?targets.filter(x=>x!==t.id):[...targets,t.id].slice(-(selection.count||1))):[t.id];setTargets(ids);preflight(ids,point,selection)};
  const pointClick=(x,y)=>{if(!b.combat.active&&!b.request){const id=freeActor||b.actors[0]?.id;if(id)invoke('map.token.move',{id,x,y});return}if(!selection)return;const dx=x-(token?.x||0),dy=y-(token?.y||0),directions=['e','se','s','sw','w','nw','n','ne'],dir=directions[(Math.round(Math.atan2(dy,dx)/(Math.PI/4))+8)%8],pt={x,y,dir};setPoint(pt);if(selection.shape||selection.kind==='move')preflight(targets,pt,selection)};
  const confirm=async()=>{if(!preview||!selection)return;if(preview.needsDM){const r=b.request?.battleAbility?{request:b.request}:await invoke('battle.begin',{actorId:b.actorId,abilityId:selection.id});if(r){await invoke('interaction.answer',{id:r.request.id,targetIds:targets,...point});setSelection(null)}return}const r=await invoke(b.request?'interaction.answer':'battle.submit',b.request?{id:b.request.id,targetIds:targets,...point,autoDice}:{...input(),version:preview.version,actionId:actionId.current,autoDice});if(r){setSelection(null);setPreview(null);setTargets([]);setPoint(null)}};
  const map=b.map,tiles=[];for(let y=0;y<map.h;y++)for(let x=0;x<map.w;x++){const t=map.terrain[y]?.[x]||'.',wall=['#','b','c',' '].includes(t),classes='ink-cell '+(wall?'wall':t==='~'||t==='W'?'water':t==='+'?'door':'floor');tiles.push(h('rect',{key:x+':'+y,className:classes,x:x*zoom,y:y*zoom,width:zoom,height:zoom,onClick:()=>pointClick(x,y)}));if(!wall)for(const [dx,dy,x1,y1,x2,y2] of [[0,-1,0,0,1,0],[1,0,1,0,1,1],[0,1,0,1,1,1],[-1,0,0,0,0,1]])if(['#','b','c',' '].includes(map.terrain[y+dy]?.[x+dx]||' '))tiles.push(h('line',{key:'l'+x+','+y+','+dx+','+dy,x1:(x+x1)*zoom,y1:(y+y1)*zoom,x2:(x+x2)*zoom,y2:(y+y2)*zoom,className:'ink-wall-edge'}));}
  const cells=preview?.area?.cells||preview?.path||[],persistentCells=(b.effects||[]).filter(e=>e.mapId===b.map.id&&e.area?.cells).flatMap(e=>e.area.cells);
  const mapView=h('div',{className:'battle-map-scroll'},h('svg',{className:'ink-map',width:map.w*zoom,height:map.h*zoom,viewBox:'0 0 '+map.w*zoom+' '+map.h*zoom,role:'img','aria-label':'手绘战术地图'},h('defs',null,h('pattern',{id:'ink-hatch',width:9,height:9,patternUnits:'userSpaceOnUse',patternTransform:'rotate(28)'},h('rect',{width:9,height:9,fill:'#ddd4bb'}),h('path',{d:'M0 0V9 M4 0V9',stroke:'#746e61',strokeWidth:.7}))),map.background?h('image',{href:map.background.url,width:map.w*zoom,height:map.h*zoom,preserveAspectRatio:'none'}):null,h('g',{className:map.background?'ink-pdf-grid':''},tiles),persistentCells.map((p,i)=>h('rect',{key:'effect'+i,x:p.x*zoom,y:p.y*zoom,width:zoom,height:zoom,className:'battle-effect-cell'})),cells.map((p,i)=>h('rect',{key:'area'+i,x:p.x*zoom,y:p.y*zoom,width:zoom,height:zoom,className:'battle-range'})),map.tokens.filter(t=>!t.hidden).map(t=>h('g',{key:t.id,role:'button',tabIndex:0,'aria-label':t.name+' · '+t.id,onMouseEnter:()=>setHover(t),onMouseLeave:()=>setHover(null),onFocus:()=>setHover(t),onBlur:()=>setHover(null),onClick:e=>{e.stopPropagation();targetClick(t)},onKeyDown:e=>{if(e.key==='Enter')targetClick(t)},className:'battle-token '+t.kind+(targets.includes(t.id)?' selected':'')+(t.id===b.actorId?' current':''),transform:'translate('+((t.x+.5)*zoom)+' '+((t.y+.5)*zoom)+')'},h('title',null,t.name+' ['+t.id+']\nAC '+(t.ac??'待查')+' · HP '+(t.hp??'待查')+'/'+(t.max??'—')+'\n先攻 '+(t.dex??'待查')+' · 豁免 '+JSON.stringify(t.saves||{})),h('circle',{r:zoom*.38}),h('text',{textAnchor:'middle',dy:4},t.name.slice(0,2)),h('text',{className:'battle-token-label',textAnchor:'middle',y:zoom*.68},t.kind==='pc'?t.name.slice(0,2):t.id.slice(-5)),t.hp!=null&&t.max?h('line',{x1:-zoom*.3,y1:-zoom*.47,x2:zoom*.3,y2:-zoom*.47,className:'battle-hp-track'}):null,t.hp!=null&&t.max?h('line',{x1:-zoom*.3,y1:-zoom*.47,x2:-zoom*.3+zoom*.6*Math.max(0,t.hp/t.max),y2:-zoom*.47,className:'battle-hp-value'}):null))));
  const req=b.dice[0];
  const card=h('section',{className:'battle-character'},h('header',null,h('b',null,displayActor?.name||current?.name||'尚未进入战斗'),h('button',{onClick:()=>window.SoloOpenPage?.({id:'card-'+(displayActor?.id||''),title:displayActor?.name||'角色卡',kind:'character',actorId:displayActor?.id}),disabled:!displayActor},'↗')),
    displayActor?h('div',{className:'battle-health'},h('strong',null,displayActor.hp.current+' / '+displayActor.hp.max),h('span',null,'HP'),h('div',{className:'battle-temp','aria-label':'临时生命'},h('b',null,displayActor.hp.temp||0),h('small',null,'临时生命'))):h('p',null,b.combat.active?'敌方回合':'可在地图工具栏开启回合制。'),
    displayActor?.death?h('p',null,displayActor.death.dead?'已死亡':displayActor.hp.current===0?'濒死 · 成功 '+displayActor.death.success+' / 失败 '+displayActor.death.failure:''):null,
    h('p',null,'AC '+(actor?b.sheet?.ac:b.map.tokens.find(t=>t.id===displayActor?.id)?.ac??'—')+' · '+(actor?'移动剩余 '+Math.max(0,(token?.speed||30)+(current?.econ?.extraMove||0)-(current?.econ?.move||0))+' 尺':'等待我的回合')),
    (b.slots||[]).map(s=>h('div',{key:s.lv,className:'battle-slot'},s.lv+'环法术位',h('b',null,s.remaining==null?'待确认':s.remaining+' / '+s.max))),actor&&(b.slots||[]).length?h('button',{onClick:()=>{setSlots(Object.fromEntries(b.slots.map(s=>[s.lv,s.remaining??s.max])));setResource(true)}},'确认 / 调整剩余法术位'):null,
    h('p',{className:'battle-help'},'法术点击后在地图选目标；确认前不消耗行动或资源。'),
    h('label',null,h('input',{type:'checkbox',checked:autoDice,onChange:e=>setAutoDice(e.target.checked)}),' 我的行动自动投骰'),h('label',null,h('input',{type:'checkbox',checked:autoEnemy,onChange:e=>setAutoEnemy(e.target.checked)}),' 连续执行敌方基础回合'));
  return h('div',{className:'battle-page'},h('div',{className:'battle-top'},h('span',{className:'battle-mode'},b.combat.active?'回合制 · 第 '+b.combat.round+' 轮':'自由探索'),h('button',{disabled:busy||!!b.active,onClick:()=>invoke('combat.mode',{mode:b.combat.active?'free':'turn'})},b.combat.active?'切换自由移动':'开启回合制'),h('div',{className:'battle-initiative'},b.combat.order.map(e=>h('span',{key:e.id,className:e.id===current?.id?'on':''},e.name+' '+e.init))),h('button',{disabled:busy||!b.combat.active||!!b.active,onClick:()=>invoke(actor?'battle.endTurn':'battle.enemy')},actor?'结束我的回合':'推进敌方行动')),
    h('div',{className:'battle-layout'},h('aside',null,card),h('main',{className:'battle-stage'},h('div',{className:'battle-map-heading'},h('b',null,map.name||'战术地图'),h('small',null,'纸面墨线 · 每格5尺'),h('input',{'aria-label':'地图缩放',type:'range',min:20,max:64,value:zoom,onChange:e=>setZoom(Number(e.target.value))})),(b.effects||[]).length?h('div',{className:'battle-effects'},b.effects.map(e=>h('span',{key:e.id},e.name+(e.concentration?' · 专注':'')+(e.rounds!=null?' · '+e.rounds+'轮':e.remainingSeconds!=null?' · '+Math.ceil(e.remainingSeconds/60)+'分钟':'')))):null,mapView,hover?h('div',{className:'battle-hover'},h('b',null,hover.name+' · '+hover.id),h('span',null,'AC '+(hover.ac??'待查')+' · HP '+(hover.hp??'待查')+'/'+(hover.max??'—')),h('small',null,'先攻加值 '+(hover.dex??'待查')+' · 豁免 '+Object.entries(hover.saves||{}).map(([k,v])=>k+' '+(v>=0?'+':'')+v).join(' / '))):null,
      h('div',{className:'battle-actionbar'},h('button',{disabled:busy||!actor||!!b.active||!!b.request||!b.combat.active,onClick:()=>choose({id:'move',kind:'move',name:'移动'})},'移动'),['dash','disengage'].map(kind=>h('button',{key:kind,disabled:busy||!actor||!!b.active||!!b.request||!b.combat.active||!b.combat.active,onClick:()=>invoke('battle.utility',{actorId:b.actorId,kind})},kind==='dash'?'疾走':'撤离')),actor?.hp.current===0?h('button',{disabled:busy||!!b.active,onClick:()=>invoke('battle.deathSave')},'死亡豁免'):null,b.items.map(ab=>h('button',{key:ab.id,title:ab.fx||ab.name,className:selection?.id===ab.id?'selected':'',disabled:busy||!actor||!!b.active||!!b.request||!b.combat.active,onClick:()=>choose(ab)},h('b',null,ab.name),h('small',null,ab.kind==='dm'?'DM 裁定':ab.id==='weapon'?'攻击':ab.level?'法术 · '+ab.level+'环':'戏法')))),
      selection?h('div',{className:'battle-confirm'},h('span',null,selection.name+' · '+msg),h('button',{disabled:busy||!preview,onClick:confirm},preview?.needsDM?'交给 DM 裁定':'确认执行'),h('button',{onClick:()=>{setSelection(null);setPreview(null);setTargets([]);if(b.request)invoke('interaction.cancel',{id:b.request.id})}},'取消选择')):msg?h('div',{role:'status',className:'battle-message'},msg):null,
      req?h('div',{className:'battle-dice',role:'status'},h('b',null,req.label),h('span',null,req.expr+(req.dc!=null?' · DC '+req.dc:'')),h('button',{disabled:busy,onClick:()=>invoke('dice.answer',{id:req.id})},'投掷并继续'),h('small',null,b.dice.length>1?'后续 '+(b.dice.length-1)+' 条依次处理':'结果自动进入行动结算')):null,
      b.active?.reaction?h('div',{className:'battle-reaction'},h('b',null,b.active.reaction.label),h('button',{disabled:busy,onClick:()=>invoke('battle.reaction',{actionId:b.active.id,accept:true})},'使用反应'),h('button',{disabled:busy,onClick:()=>invoke('battle.reaction',{actionId:b.active.id,accept:false})},'放弃')):null),
    h('aside',{className:'battle-narrative'},h('section',{className:'battle-chat'},h(C.AIPanel,{})),h('section',{className:'battle-events'},h('header',null,'战斗记录'),b.events.slice(-30).reverse().map(e=>h('article',{key:e.id},h('small',null,'R'+e.round),e.text))))),
    resource?h('div',{className:'roll-request-modal'},h('div',{className:'roll-request-card'},h('h3',null,'确认真实剩余法术位'),h('p',null,'旧版本只保存容量。请按当前战役真实消耗填写，这不是休息或免费恢复。'),(b.slots||[]).map(s=>h('label',{key:s.lv},s.lv+'环（容量 '+s.max+'）',h('input',{type:'number',min:0,max:s.max,value:slots[s.lv]??0,onChange:e=>setSlots({...slots,[s.lv]:Number(e.target.value)})}))),h('button',{onClick:()=>setResource(false)},'取消'),h('button',{disabled:busy,onClick:async()=>{if(await invoke('battle.resources',{actorId:actor.id,slots}))setResource(false)}},'确认余额'))):null);
 };
 window.SoloCharacterPage=function({actorId}){const [sheet,setSheet]=React.useState(null);React.useEffect(()=>{const load=()=>call('party.sheet',{id:actorId}).then(r=>{if(r.ok)setSheet(r.sheet)});load();window.addEventListener('solo-state',load);return()=>window.removeEventListener('solo-state',load)},[actorId]);return sheet?h('div',{className:'solo-card-page'},h(window.SoloComponents.Detail,{s:sheet,onReload:()=>call('party.sheet',{id:actorId}).then(r=>setSheet(r.sheet))})):h('p',null,'正在读取角色卡…')};
})();
