(function(){
 const h=React.createElement,call=(op,args={})=>window.SoloHost.call(op,args);
 const btn=(text,fn,disabled=false)=>h('button',{key:text,type:'button',className:'dndp-btn',onClick:fn,disabled},text);
 window.SoloHome=function(){
  const [data,setData]=React.useState({items:[]}),[modules,setModules]=React.useState([]),[name,setName]=React.useState(''),[moduleId,setModule]=React.useState(''),[aidm,setAidm]=React.useState(false),[create,setCreate]=React.useState(location.hash==='#new-character'),[phase,setPhase]=React.useState(location.hash==='#new-character'?'character':'module'),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
  const refresh=async()=>{setData(await call('profiles.list'));const c=await call('campaign.get');setModules(c.modules||[])};React.useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
  const run=async fn=>{if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const open=(id,role)=>run(async()=>{const r=await call('profiles.select',{id});if(!r.ok)throw Error(r.error);location.hash=role==='dm'?'open-dm':'open-player';location.reload()});
  return h('main',{className:'home-page'},h('header',null,h('small',null,'SOLOTRPG · 冒险从这里开始'),h('h1',null,'你的跑团桌'),h('p',null,'选择已有战役，或创建一场新的冒险。'),btn('新建战役',()=>{setCreate(true);setPhase('module')})),error?h('p',{role:'alert'},error):null,
   create?h('section',{className:'home-create'},h('h2',null,phase==='module'?'① 导入模组 · ② 选择主持方式':phase==='character'?'③ 新建角色':'准备完成'),
    phase==='module'?h(React.Fragment,null,h('label',null,'战役名称',h('input',{value:name,onChange:e=>setName(e.target.value)})),h('label',null,'模组',h('select',{value:moduleId,onChange:e=>setModule(e.target.value)},h('option',{value:''},'请选择已导入模组'),modules.map(m=>h('option',{key:m.id,value:m.id},m.name)))),btn('刷新模组列表',refresh),h('details',null,h('summary',null,'导入新的 PDF / 模组'),h(window.SoloModuleLibrary,{call})),h('label',null,h('input',{type:'checkbox',checked:aidm,onChange:e=>setAidm(e.target.checked)}),'启用 AI DM（关闭时由人工 DM 主持）'),btn('创建战役并新建角色',()=>run(async()=>{const r=await call('profiles.create',{name,moduleId,aidm});if(!r.ok)throw Error(r.error);location.hash='new-character';location.reload()}),busy||!name.trim()||!moduleId)):
    phase==='character'?h(window.SoloComponents.Wizard,{onDone:()=>{setPhase('ready');refresh()},onBack:()=>setPhase('ready')}):h('div',null,btn('以玩家进入',()=>open(data.active,'player')),btn('以 DM 进入',()=>open(data.active,'dm'))),btn('返回存档列表',()=>{setCreate(false);history.replaceState(null,'',location.pathname)})):
   h('section',{className:'save-grid'},data.items.map(s=>h('article',{key:s.id,className:'save-card'},h('span',{className:'save-mark'},'✦'),h('h2',null,s.name),h('p',null,s.id===data.active?'当前战役':'独立角色、地图与对话存档'),btn('玩家进入',()=>open(s.id,'player'),busy),btn('DM 进入',()=>open(s.id,'dm'),busy)))),
   h('footer',null,'角色数据保存在 AppData；战役对话、地图和记录保存在程序旁的 saves。模组和规则书共用 library，不重复复制。'));
 };
 const names={'dice.request':'请求玩家投骰','dice.secret':'DM暗骰','combat.mode':'自由 / 回合制','combat.start':'建立先攻','combat.next':'结束当前回合','combat.damage':'伤害与治疗','combat.conditions':'添加 / 移除状态','battle.npcEnd':'NPC结束回合','enemy.bind':'绑定敌人资料','dm.move':'移动单位','map.token.add':'添加棋子','map.token.update':'编辑棋子','map.token.remove':'移除棋子','map.create':'新建地图','map.compose':'绘制地图','character.update':'装备与角色同步','effect.add':'登记持续效果','effect.end':'结束持续效果','narration.say':'DM / NPC 发言','log.append':'添加战斗记录','combat.end':'结束并归档战斗'};
 const labels={actorId:'角色 / 单位',targetId:'目标',tokenId:'地图单位',id:'目标 ID',amount:'生命变化（伤害填负数）',expr:'骰子表达式',label:'检定名称',dc:'难度 DC',name:'名称',speaker:'发言者',text:'正文',reason:'裁定依据',x:'横坐标',y:'纵坐标',range:'距离（尺）',size:'范围（尺）',durationSeconds:'持续秒数',rounds:'持续回合',temp:'临时生命',acBonus:'AC 加值',maxHpBonus:'生命上限加值',concentration:'需要专注',mode:'移动模式',kind:'类型',statblockId:'规则条目 ID',turnKey:'当前回合标识',spell:'法术键',query:'查询',title:'标题',changeId:'本次变更标识',slot:'穿戴位置',key:'物品键',hidden:'隐藏',note:'备注'};
 function Field({schema={},value,onChange,name,units=[],depth=0}){
  const type=Array.isArray(schema.type)?schema.type.find(t=>t!=='null'):schema.type;
  if(schema.enum)return h('select',{value:value??'',onChange:e=>onChange(e.target.value)},h('option',{value:''},'请选择'),schema.enum.map(v=>h('option',{key:v,value:v},v)));
  if(type==='boolean')return h('input',{type:'checkbox',checked:!!value,onChange:e=>onChange(e.target.checked)});
  if(type==='object'&&schema.properties&&depth<4)return h('fieldset',null,Object.entries(schema.properties).map(([k,s])=>h('label',{key:k},(labels[k]||k)+(schema.required?.includes(k)?' *':''),h(Field,{schema:s,value:value?.[k],name:k,units,depth:depth+1,onChange:v=>onChange({...value,[k]:v})}))));
  if(type==='array'&&depth<4){const children=(value||[]).map((v,i)=>h('div',{key:i},h(Field,{schema:schema.items,value:v,units,depth:depth+1,onChange:n=>onChange(value.map((x,j)=>i===j?n:x))}),btn('移除',()=>onChange(value.filter((_,j)=>i!==j)))));return h('div',null,children,btn('添加一项',()=>onChange([...(value||[]),schema.items?.type==='object'?{}:''])))}
  if(schema.unit||['actorId','targetId','tokenId'].includes(name))return h('select',{value:value||'',onChange:e=>onChange(e.target.value)},h('option',{value:''},'选择单位'),units.map(u=>h('option',{key:u.id,value:u.id},u.name)));
  if(type==='object')return h('textarea',{value:typeof value==='object'?JSON.stringify(value):value||'',placeholder:'高级参数 JSON',onChange:e=>{try{onChange(JSON.parse(e.target.value))}catch{onChange(e.target.value)}}});
  return h(type==='string'&&['text','note','reason','message'].includes(name)?'textarea':'input',{type:type==='number'||type==='integer'?'number':'text',value:value??'',onChange:e=>onChange(type==='number'||type==='integer'?(e.target.value===''?undefined:Number(e.target.value)):e.target.value)});
 }
 const extra=[{op:'dm.move',name:'dm_move',desc:'DM 移动单位（遵守当前回合与移动距离）',schema:{type:'object',properties:{id:{type:'string'},x:{type:'number'},y:{type:'number'}},required:['id','x','y']}},{op:'combat.next',name:'combat_next',desc:'结束当前回合',schema:{type:'object',properties:{}}},{op:'log.append',name:'log_append',desc:'添加战斗记录',schema:{type:'object',properties:{text:{type:'string'},actor:{type:'string'}}}},{op:'combat.mode',name:'combat_mode',desc:'切换自由移动 / 回合制',schema:{type:'object',properties:{mode:{type:'string',enum:['free','turn']}},required:['mode']}}];
 window.SoloDMConsole=function(){
  const [controls,setControls]=React.useState({aidm:false,economy:'economy'}),[tools,setTools]=React.useState([]),[units,setUnits]=React.useState([]),[usage,setUsage]=React.useState({requests:[]}),[op,setOp]=React.useState('dice.request'),[args,setArgs]=React.useState({}),[query,setQuery]=React.useState(''),[result,setResult]=React.useState(null),[busy,setBusy]=React.useState(false),[task,setTask]=React.useState('rules'),[prompt,setPrompt]=React.useState(''),[reply,setReply]=React.useState('');
  const load=async()=>{const [c,t,s,u]=await Promise.all([call('controls.get'),call('ai.tools'),call('scene.get'),call('ai.usage')]);setControls(c);setTools([...t.tools.filter(x=>!extra.some(e=>e.op===x.op)),...extra]);setUnits([...s.characters,...(s.map?.tokens||[]).filter(t=>!s.characters.some(c=>c.id===t.id))]);setUsage(u)};React.useEffect(()=>{load();window.addEventListener('solo-state',load);return()=>window.removeEventListener('solo-state',load)},[]);
  const run=async fn=>{if(busy)return;setBusy(true);try{const r=await fn();setResult(r);await load();window.dispatchEvent(new Event('solo-state'));return r}catch(e){setResult({ok:false,error:e.message})}finally{setBusy(false)}};
  const tool=tools.find(t=>t.op===op),common=['dice.request','dice.secret','combat.mode','combat.start','combat.next','combat.damage','combat.conditions','battle.npcEnd','enemy.bind','dm.move','map.token.add','map.token.update','map.token.remove','map.create','map.compose','character.update','effect.add','effect.end','narration.say','log.append','combat.end'];
  return h('main',{className:'dm-console'},h('header',null,h('h1',null,'DM 控制台'),h('p',null,'裁定由你决定，操作直接写入场景与角色状态。'),h('label',null,h('input',{type:'checkbox',checked:!!controls.aidm,disabled:busy,onChange:e=>run(()=>call('controls.set',{aidm:e.target.checked}))}),'启用 AI DM 自动主持'),h('label',null,'AI 用量档位',h('select',{value:controls.economy,onChange:e=>run(()=>call('controls.set',{economy:e.target.value}))},h('option',{value:'economy'},'节省：最多3轮 / 每轮1200输出'),h('option',{value:'balanced'},'均衡：最多5轮 / 每轮2400输出')))),
   h(window.SoloLan),h('section',{className:'dm-grid'},h('article',null,h('h2',null,'裁定与场景操作'),h('div',{className:'dm-shortcuts'},common.map(key=>btn(names[key]||key,()=>{setOp(key);setArgs({});setQuery('')}))),h('label',null,'全部接口检索',h('input',{value:query,onChange:e=>setQuery(e.target.value)})),h('select',{value:op,onChange:e=>{setOp(e.target.value);setArgs({})}},tools.filter(t=>!query||(t.op+' '+t.desc).includes(query)).map(t=>h('option',{key:t.op,value:t.op},t.desc+' · '+t.op))),tool?h('form',{onSubmit:e=>{e.preventDefault();run(()=>call(op,args))}},h(Field,{schema:['combat.damage','combat.conditions','dm.move','map.token.update','map.token.remove'].includes(op)?{...tool.schema,properties:{...tool.schema.properties,id:{type:'string',unit:true}}}:tool.schema,value:args,onChange:setArgs,units}),h('button',{className:'dndp-btn primary',type:'submit',disabled:busy},'确认执行')):null,result?h('div',{className:'dm-result',role:'status'},h('b',null,result.ok?'操作成功':'未执行'),h('p',null,result.summary||result.error||''),h('details',null,h('summary',null,'查看返回数据'),h('pre',null,JSON.stringify(result,null,2)))):null),
    h('article',null,h('h2',null,'按需 AI 辅助'),h('select',{value:task,onChange:e=>setTask(e.target.value)},h('option',{value:'rules'},'规则检索与裁定建议（只读）'),h('option',{value:'map'},'生成地图（应用到当前场景）'),h('option',{value:'recap'},'整理战斗记录（先预览）')),h('textarea',{value:prompt,onChange:e=>setPrompt(e.target.value),placeholder:'描述要查的规则、地图需求，或需要整理的记录'}),btn('调用 AI 辅助',()=>run(async()=>{const r=await call('ai.chat',{assistantTool:task,message:prompt});if(r.ok)setReply(r.reply);return r}),busy||!prompt.trim()),reply?h('div',{className:'dm-assistant-result'},h(window.SoloMarkdown,{text:reply}),task==='recap'?btn('确认写入战斗记录',()=>run(()=>call('log.append',{text:reply,actor:'DM'})),busy):null):null,h('h2',null,'当前战役 AI 用量'),h('p',null,'请求 '+(usage.calls||0)+' 次 · 输入 '+(usage.prompt_tokens||0)+' · 输出 '+(usage.completion_tokens||0)),h('small',null,'仅统计服务商返回的用量；未返回用量时不作零消耗推断。'),h('div',{className:'usage-list'},usage.requests?.slice(-8).reverse().map((u,i)=>h('p',{key:i},u.task+' · 输入 '+(u.prompt_tokens??'未报告')+' / 输出 '+(u.completion_tokens??'未报告')+' · 请求 '+u.inputChars+' 字符'))))));
 };
})();
