import {isSurprised,surpriseCondition,monsterName,meleeProfile,completeAttack} from './combat-state.mjs';
import {characterTools,installCharacter} from './character-sync.mjs';
import {createHash,randomUUID} from 'node:crypto';
import path from 'node:path';
import {readJson,saveJson} from './gameplay.mjs';
const clone=x=>structuredClone(x),signed=n=>n>=0?'+'+n:String(n);
const distance=(a,b)=>Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y))*5;
const incapacitated=u=>u.hp<=0||u.conditions.some(c=>['unconscious','incapacitated','stunned','paralyzed','petrified'].includes(c.key||c));
const templates={
 mageHand:{kind:'summon',range:30,placement:true,durationSeconds:60},
 fireBolt:{kind:'attack',range:120,die:10},eldritchBlast:{kind:'attack',range:120,die:10,lowLevelOnly:true},
 acidSplash:{kind:'save',range:60,die:6,save:'dex',count:2},
 burningHands:{kind:'save',range:0,shape:'cone',size:15,damage:'3d6',save:'dex',half:true},
 magicMissile:{kind:'auto',range:120,damage:'1d4+1',repeat:3},
 fogCloud:{kind:'effect',range:120,shape:'sphere',size:20,concentration:true,durationSeconds:3600},
 falseLife:{kind:'temp',range:0,self:true,damage:'1d4+4',durationSeconds:3600},
 cureWounds:{kind:'heal',range:5,die:8},healingWord:{kind:'heal',range:60,die:4,bonus:true}
};
const obj=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false}),str={type:'string'},num={type:'number'};
export const battleTools=[...characterTools,
 ['battle.advance','继续当前敌方基础回合直到玩家回合或玩家请求。正确处理突袭空过，真实结果以返回的 current/status 为准；资料不足会停止报错。',obj({})],
 ['battle.npcEnd','结束当前NPC的回合（等待/不行动/裁定完特殊动作）。必须提供当前actorId、battle.get的turnKey及reason；不能跳过玩家。',obj({actorId:str,turnKey:str,reason:str},['actorId','turnKey','reason'])],
 ['battle.surprise','将已由DM判定被突袭的单位登记为措手不及。仅战斗第一轮且未行动者；首次回合结束解除。不能只在正文描述。',obj({actorIds:{type:'array',items:str},reason:str},['actorIds','reason'])],
 ['battle.get','读取动作执行器状态、当前回合、可用攻击和法术、资源、等待请求与已结算事件。',obj({actorId:str,playerId:str})],
 ['battle.begin','按已声明的动作建立地图选目标/范围请求；支持 weapon、已知法术key、move。玩家在地图确认后由本地执行器连续投骰结算，未知法术只交给DM裁定。',obj({actorId:str,abilityId:str},['actorId','abilityId'])],
 ['battle.preview','预检动作，不投骰、不花资源。返回合法性、距离、命中条件及版本；提交时带相同 version。',obj({actorId:str,abilityId:str,targetIds:{type:'array',items:str},x:num,y:num,dir:str},['actorId','abilityId'])],
 ['battle.enemy','执行当前NPC的基础近战行动；能力缺少可靠数值会拒绝。玩家反应/豁免发生时暂停，完成后恢复。',obj({})]
];

// All handlers below use gameplay's existing command queue. A durable after-image
// is committed before updating legacy JSON projections, so replay is idempotent.
export function installBattle(a){
 const {ops,reg,root,hydrate,loadSrd,readMap,writeMap,readCombat,writeCombat,readDice,writeDice,readPc,persist,readLog,writeLog,state,save,rollExpr,check,route,baseAnswer,baseCancel,baseInteraction,baseNext,setRecovery}=a;
 const file=path.join(root,'battle.json');
 const load=()=>readJson(file,{schema:1,seq:0,active:null,receipts:{},events:[],projection:null});
 const capture=async()=>{await hydrate();await cleanHands();const chars={};for(const p of (await ops['party.list']({})).items||[])chars[p.id]=clone(await readPc(p.id));return {map:clone(await readMap()),combat:clone(await readCombat()),dice:clone(await readDice()),session:clone(await state()),log:clone(await readLog()),chars}};
 const cleanHands=async()=>{const map=await readMap(),session=await state();let dirty=false;for(const t of [...map.tokens].filter(t=>t.spell==='mageHand')){const owner=map.tokens.find(p=>p.id===t.ownerId),effect=session.effects.find(e=>e.tokenId===t.id&&e.mapId===map.id);if(!owner||!effect||effect.expiresAt<=session.clock||distance(owner,t)>30){map.tokens=map.tokens.filter(p=>p.id!==t.id);session.effects=session.effects.filter(e=>e.tokenId!==t.id);dirty=true}}if(dirty){check(await writeMap(map));await save(session)}};
 const project=async w=>{for(const pc of Object.values(w.chars))check(await persist(pc));for(const pc of Object.values(w.chars)){const sheet=check(await ops['party.sheet']({id:pc.id})).sheet;const entry=w.combat.order.find(e=>e.pcId===pc.id||e.tokenId===pc.id),token=w.map.tokens.find(t=>t.id===pc.id||t.id===entry?.tokenId);for(const obj of [entry,token])if(obj)Object.assign(obj,{hp:sheet.hp.cur,max:sheet.hp.max,temp:sheet.hp.temp||0,ac:sheet.ac,saves:sheet.saves})}check(await writeMap(w.map));check(await writeCombat(w.combat));check(await writeDice(w.dice));check(await writeLog(w.log));await save(w.session)};
 const recover=async()=>{const b=await load();if(b.projection){await project(b.projection);b.projection=null;await saveJson(file,b)}};
 setRecovery(recover);
 const commit=async(b,w)=>{b.seq++;b.projection=w;await saveJson(file,b);await project(w);b.projection=null;await saveJson(file,b)};
 const entity=(w,id)=>{const token=w.map.tokens.find(t=>t.id===id),entry=w.combat.order.find(e=>e.id===id||e.tokenId===id||e.pcId===id),pc=w.chars[entry?.pcId||id];if(!token&&!entry&&!pc)throw Error('找不到单位 '+id);return {id:token?.id||entry?.tokenId||pc?.id||entry.id,token,entry,pc,name:pc?.name||token?.name||entry?.name,hp:(pc?.hp.current??token?.hp??entry?.hp)==null?NaN:Number(pc?.hp.current??token?.hp??entry?.hp),max:Number(pc?.hp.max??token?.max??entry?.max),temp:Number(pc?.hp.temp??token?.temp??entry?.temp)||0,conditions:pc?.conditions||entry?.conditions||[],kind:token?.kind||entry?.kind||(pc?'pc':'enemy')}};
 const version=w=>createHash('sha256').update(JSON.stringify([w.map,w.combat,w.dice.pending,w.session.requests,w.session.effects,w.chars])).digest('hex').slice(0,20);
 const pauseKey=w=>createHash('sha256').update(JSON.stringify([w.combat,w.map,w.chars],(key,value)=>key==='updatedAt'?undefined:value)).digest('hex').slice(0,20);
 const noStanding=w=>w.combat.active&&w.map.tokens.some(t=>t.kind==='pc')&&!w.map.tokens.some(t=>t.kind==='pc'&&t.hp>0);
 const flowPause=(b,w)=>{if(!w.combat.active)return null;const e=w.combat.order[w.combat.turnIndex];if(w.chars[e?.pcId||e?.tokenId])return null;if(b.pause?.key===pauseKey(w))return b.pause;if(noStanding(w))return {status:'waiting_dm',reason:'玩家全部倒地：等待 DM 裁定敌方行为，或确认敌方暂不行动后推进死亡豁免。',key:pauseKey(w)};return null};
 const pauseFlow=async(b,w,reason)=>{const key=pauseKey(w);if(b.pause?.key===key&&b.pause.reason===reason)return {ok:true,status:'waiting_dm',pause:b.pause};b.pause={key,reason,status:'waiting_dm'};w.session.needsResume=false;event(b,w,'敌方流程暂停：'+reason,{kind:'pause'});await commit(b,w);return {ok:true,status:'waiting_dm',pause:b.pause}};
 const event=(b,w,text,extra={})=>{const e={id:'ev-'+randomUUID(),t:new Date().toISOString(),round:w.combat.round,text,actionId:b.active?.id,...extra};b.events.push(e);b.events=b.events.slice(-100);w.log.entries.push({...e,kind:extra.kind||'narrate',actor:extra.actor||'执行器',detail:extra.detail||'',seq:++w.log.seq});return e};
 const hp=(w,u,value,temp)=>{if(u.pc){u.pc.hp.current=value;u.pc.hp.temp=temp}if(u.token){u.token.hp=value;u.token.temp=temp}if(u.entry){u.entry.hp=value;u.entry.temp=temp}u.hp=value;u.temp=temp};
 const addDice=(w,b,p,expr,label,actorId,dc,tag,advantage='normal')=>{check(rollExpr(expr,advantage));const req={id:'r'+(++w.dice.seq),expr,label,actorId,actor:entity(w,actorId).name,dc:dc??null,advantage,kind:tag,battleAction:p.id,requestKey:p.id+':'+p.cursor+':'+tag,t:new Date().toISOString()};w.dice.pending.push(req);p.waiting={id:req.id,tag};return req};
 const attacks=pc=>Math.max(1,...(pc.classes||[]).map(c=>c.class==='fighter'?(c.level>=20?4:c.level>=11?3:c.level>=5?2:1):['barbarian','monk','paladin','ranger'].includes(c.class)&&c.level>=5?2:1));
 const spellSlots=(pc,sheet)=>sheet.slots.map(s=>({lv:s.lv,max:s.max,remaining:pc?.battleResources?.slots?.[s.lv]??null}));
 const catalog=async(w,id)=>{const u=entity(w,id),items=[];let sheet=null;if(u.pc){sheet=check(await ops['party.sheet']({id:u.pc.id})).sheet;items.push({id:'stealth',name:'潜行',kind:'dm',range:0,self:true,cost:'action',count:1});const weapon=sheet.weaponStats?.main;if(weapon){const key=weapon.key||u.pc.equipment?.mainHand||'',ranged=/bow|crossbow|sling|blowgun/i.test(String(key)),props=u.pc.equipment?.mainHand?.props||[],weaponRange=({lightCrossbow:80,shortbow:80,sling:30,handCrossbow:30,heavyCrossbow:100,longbow:150,blowgun:25})[key];items.push({id:'weapon',name:weapon.name||'武器攻击',kind:'attack',range:ranged?(weaponRange||5):props.includes('reach')?10:5,attack:Number(weapon.attack),damage:weapon.damage+(Number(weapon.dmgBonus)?signed(weapon.dmgBonus):''),ranged,maxAttacks:props.includes('loading')?1:attacks(u.pc),level:0,cost:'action',count:1})}for(const sp of sheet.spells||[]){const t=templates[sp.key],scale=1+(sheet.level>=5)+(sheet.level>=11)+(sheet.level>=17),ability=u.pc.spellcasting?.ability||'int',mod=sheet.mods[ability]||0;const supported=!!t&&!(t.lowLevelOnly&&sheet.level>=5)&&!(sp.source==='种族施法'&&sp.level>0);items.push({...sp,...(supported?t:{}),id:sp.key,kind:supported?t.kind:'dm',supported,cost:sp.time?.includes('附赠')?'bonus':'action',range:t?.range??(Number(String(sp.range).match(/\d+/)?.[0])||0),count:t?.count||1,attack:Number(sheet.attack??(sheet.pb+mod)),dc:Number(sheet.dc??(8+sheet.pb+mod)),damage:t?.damage||(t?.die?(t.kind==='heal'?'1d'+t.die+signed(mod):scale+'d'+t.die):null),requiresSlots:sp.level>0,slots:spellSlots(u.pc,sheet)})}}else{let profile=u.token||{};if(!completeAttack(profile)&&u.token?.statblockId){const sb=await ops['mod.statblock']({id:u.token.statblockId,title:monsterName(u.name)});profile=meleeProfile(sb)}const {attackBonus:bonus,damage,reach}=profile;if(completeAttack(profile))items.push({id:'weapon',name:'基础攻击',kind:'attack',range:reach,attack:Number(bonus),damage,level:0,cost:'action',count:1})}if(u.pc&&w.map.tokens.some(t=>t.spell==='mageHand'&&t.ownerId===u.id)){items.push({id:'mageHandControl',name:'操控法师之手',kind:'summon',placement:true,range:30,cost:'action'},{id:'mageHandDismiss',name:'解散法师之手',kind:'summon',self:true,range:0,cost:'action'})}return {items,sheet,slots:sheet?spellSlots(u.pc,sheet):[]}};
 const activeCheck=(w,u)=>{if(!w.combat.active)throw Error('请先开启回合制。');const current=w.combat.order[w.combat.turnIndex];if(!u.entry||current?.id!==u.entry.id)throw Error('还没轮到这个单位。');if(incapacitated(u)||isSurprised(u))throw Error('当前单位无法行动（失能或措手不及），请结束受限回合。');if(w.dice.pending.length)throw Error('请先完成队首投骰（包括先攻）。')};
 const preview=async args=>{const w=await capture(),b=await load(),u=entity(w,args.actorId);if(w.combat.active)activeCheck(w,u);else if(!u.pc)throw Error('探索行动只用于玩家。');if(b.active)throw Error('请先完成当前行动。');const data=await catalog(w,u.id),ability=args.abilityId==='move'?{id:'move',kind:'move',name:'移动'}:data.items.find(i=>i.id===args.abilityId);if(!ability)throw Error('角色没有这项能力。');if(ability.kind==='summon'){
 if(!u.token)throw Error('施法者不在地图上。');
 if(w.combat.active&&u.entry.econ?.action)throw Error('动作已使用。');
 const hand=w.map.tokens.find(t=>t.spell==='mageHand'&&t.ownerId===u.id);
 if(ability.id!=='mageHand'&&!hand)throw Error('法师之手已消失，请重新施放。');
 if(ability.id==='mageHandDismiss')return {ok:true,version:version(w),ability};
 const point={x:Number(args.x),y:Number(args.y)};
 if(!Number.isInteger(point.x)||!Number.isInteger(point.y)||point.x<0||point.y<0||point.x>=w.map.w||point.y>=w.map.h)throw Error('请点击地图选择法师之手的位置。');
 if(distance(u.token,point)>30)throw Error('法师之手必须在施法者30尺内。');
 if(hand&&ability.id==='mageHandControl'&&distance(hand,point)>30)throw Error('一次操控最多移动法师之手30尺。');
 if(['#','b','c',' '].includes(w.map.terrain[point.y]?.[point.x]))throw Error('不能将法师之手放入墙体。');
 const los=check(await ops['map.los']({from:ability.id==='mageHandControl'?hand:u.token,to:point}));if(los.blocked)throw Error('法师之手的路径被地形遮挡。');
 return {ok:true,version:version(w),ability,point,area:{cells:[point]},summary:ability.name+' · '+point.x+','+point.y};
 }if(!w.combat.active&&ability.kind==='move'){const p=route(w.map,u.token,{x:Number(args.x),y:Number(args.y)});if(!p)throw Error('该位置不可达。');return {ok:true,version:version(w),ability,path:p.path,feet:p.cost}}if(!w.combat.active||ability.kind==='dm')return {ok:true,version:version(w),ability,needsDM:true,summary:'此能力由 DM 查规则后裁定；地图选择会自动交给 DM。'};
 if(ability.kind==='move'){const end={x:Number(args.x),y:Number(args.y)},p=route(w.map,u.token,end);if(!p)throw Error('该位置不可达。');const used=u.entry.econ?.move||0;if(p.cost+used>(u.token.speed||30)+(u.entry.econ.extraMove||0))throw Error('超出本回合移动距离。');return {ok:true,version:version(w),ability,path:p.path,feet:p.cost}}
 const econ=u.entry.econ||{};if(econ[ability.cost]&&!(ability.id==='weapon'&&econ.weaponAttacks>0&&econ.weaponAttacks<(ability.maxAttacks||1)))throw Error(ability.cost==='bonus'?'附赠动作已使用。':'动作已使用。');if(ability.key&&(econ.bonusSpell&&!(ability.level===0&&ability.cost==='action')||ability.cost==='bonus'&&econ.leveledSpell))throw Error('本回合附赠施法限制：其他施法只能是施法时间为一动作的戏法。');
 if(ability.requiresSlots){const slot=data.slots.find(s=>s.lv===ability.level);if(slot?.remaining==null)throw Error('剩余法术位尚未确认，请先在战斗角色卡设置真实余额。');if(slot.remaining<1)throw Error('该环法术位不足；本版自动结算只支持原环施法。')}
 if(new Set(args.targetIds||[]).size!==(args.targetIds||[]).length)throw Error('目标不能重复。');let targets=(args.targetIds||[]).map(id=>entity(w,id)),area=null;
 if(ability.self)targets=[u];
 if(ability.shape){const from=ability.range===0?u.token:{x:Number(args.x),y:Number(args.y)};if(!from||!Number.isInteger(from.x)||!Number.isInteger(from.y)||from.x<0||from.y<0||from.x>=w.map.w||from.y>=w.map.h)throw Error('请选择范围原点。');if(distance(u.token,from)>ability.range)throw Error('范围原点超出射程。');area=check(await ops['map.area']({shape:ability.shape,size:ability.size,from,dir:args.dir||'n'}));targets=w.map.tokens.filter(t=>t.kind!=='effect'&&t.id!==u.id&&area.cells.some(c=>c.x===t.x&&c.y===t.y)&&t.hp!==0&&!t.hidden).map(t=>entity(w,t.id));}
 if(!ability.shape&&(!targets.length||targets.length>(ability.count||1)))throw Error('请选择正确数量的目标。');if(ability.id==='acidSplash'&&targets.length===2&&distance(targets[0].token,targets[1].token)>5)throw Error('酸液飞溅的两个目标必须相距不超过5尺。');
 const info=[];for(const t of targets){if(t.token?.hidden)throw Error('目标尚未被发现。');if(!t.token)throw Error('目标不在地图上。');if(t.pc?.battleDeath?.dead&&ability.kind==='heal')throw Error('普通治疗不能复活死者。');if(!ability.shape&&distance(u.token,t.token)>ability.range)throw Error('目标超出射程。');if(t.hp<=0&&ability.kind!=='heal')throw Error('该目标已倒下。');const los=check(await ops['map.los']({from:u.token,to:t.token}));if(los.blocked)throw Error('目标被地形遮挡。');const fog=w.session.effects.some(e=>e.spell==='fogCloud'&&e.area?.cells?.some(c=>(c.x===u.token.x&&c.y===u.token.y)||(c.x===t.token.x&&c.y===t.token.y)));if(fog)throw Error('浓雾影响视线；请让 DM 核对可见性和攻击优势后裁定。');const cover=Number(los.cover?.ac??los.coverBonus??los.cover)||0;let ac=t.pc?check(await ops['party.sheet']({id:t.pc.id})).sheet.ac:t.token.ac;if(ability.kind==='attack'&&(ac==null||!Number.isFinite(Number(ac))))throw Error('目标 AC 未查明。');let saves=t.pc?check(await ops['party.sheet']({id:t.pc.id})).sheet.saves:t.token.saves;if(ability.save&&(saves?.[ability.save]==null||!Number.isFinite(Number(saves?.[ability.save]))))throw Error('目标豁免数据缺失，请先查规则简表。');info.push({id:t.id,name:t.name,ac:Number(ac)+cover,save:(Number(saves?.[ability.save])||0)+(ability.save==='dex'?cover:0),kind:t.kind,distance:distance(u.token,t.token),friendly:t.kind===u.kind});}
 return {ok:true,version:version(w),ability,targets:info,area,cost:ability.cost,summary:ability.name+' · '+(info.map(t=>t.name+' ['+t.id+']').join('、')||'范围效果')};};
 const damage=async(b,w,id,amount,critical=false)=>{const u=entity(w,id);if(!Number.isFinite(u.hp))throw Error('目标 HP 未查明。');if(amount<=0)return;const absorb=Math.min(u.temp,amount),before=u.hp,next=Math.max(0,before-(amount-absorb));hp(w,u,next,u.temp-absorb);if(u.temp===0)w.session.effects=w.session.effects.filter(e=>!(e.temp!=null&&e.targetId===u.id));if(u.pc&&next===0){const death=u.pc.battleDeath||{success:0,failure:0};if(before===0)death.failure+=critical?2:1;if(amount-absorb-before>=u.max)death.failure=3;death.dead=death.failure>=3;death.stable=false;u.pc.battleDeath=death;}
 const effects=w.session.effects.filter(e=>e.concentration&&[u.id,u.entry?.id,u.pc?.id].includes(e.actorId));if(next===0)w.session.effects=w.session.effects.filter(e=>!effects.includes(e));else if(effects.length){const bonus=u.pc?check(await ops['party.sheet']({id:u.pc.id})).sheet.saves.con:u.token.saves?.con||0;const dc=Math.max(10,Math.floor(amount/2));if(u.pc){w.dice.pending.push({id:'r'+(++w.dice.seq),expr:'1d20'+signed(bonus),label:'专注豁免',actorId:u.id,actor:u.name,dc,kind:'concentration',effectIds:effects.map(e=>e.id)})}else if(check(rollExpr('1d20'+signed(bonus))).total<dc)w.session.effects=w.session.effects.filter(e=>!effects.includes(e));}event(b,w,u.name+' 受到 '+amount+' 点伤害'+(absorb?'，临时生命吸收 '+absorb:''),{kind:'damage',targetId:u.id,damage:amount,absorbed:absorb,hp:next});};
 const roll=async(b,w,p,expr,label,id,dc,tag,advantage='normal')=>{if(p.results[tag])return p.results[tag];const u=entity(w,id);if(u.pc&&!(p.autoDice&&u.id===p.actorId)){addDice(w,b,p,expr,label,id,dc,tag,advantage);await commit(b,w);return null}const r=check(rollExpr(expr,advantage));p.results[tag]={...r,success:dc==null?null:r.total>=dc};event(b,w,label+'：'+r.detail,{kind:'roll',actor:u.name,total:r.total});await commit(b,w);return p.results[tag]};
 const drive=async()=>{for(let guard=0;guard<100;guard++){let b=await load(),w=await capture(),p=b.active;if(!p)return {ok:true,status:'idle'};if(p.waiting||w.dice.pending.length)return {ok:true,status:'awaiting_roll',actionId:p.id};const step=p.steps[p.cursor];if(!step){p.status='complete';b.receipts[p.id]=clone(p);b.active=null;w.session.needsResume=false;w.session.completed.push({id:p.id,kind:'battle',status:'complete',result:{ability:p.ability.name,targets:p.targetIds,eventIds:b.events.filter(e=>e.actionId===p.id).map(e=>e.id)}});await commit(b,w);return {ok:true,status:'complete',actionId:p.id,summary:'行动已结算，DM 可读取最新结果。'}}
 const u=entity(w,step.actorId||p.actorId),tag='step-'+p.cursor;
 if(step.type==='death'){const r=await roll(b,w,p,'1d20','死亡豁免',u.id,10,tag);if(!r)return {ok:true,status:'awaiting_roll'};b=await load();w=await capture();p=b.active;const t=entity(w,u.id),d=t.pc.battleDeath||{success:0,failure:0};if(r.total===20){hp(w,t,1,t.temp);delete t.pc.battleDeath}else{if(r.total===1)d.failure+=2;else if(r.total>=10)d.success++;else d.failure++;d.dead=d.failure>=3;d.stable=d.success>=3;t.pc.battleDeath=d}event(b,w,t.name+' 死亡豁免：'+r.total,{actionId:p.id})}
 if(step.type==='move'){if(incapacitated(u)){p.cursor=p.steps.length;await commit(b,w);continue}u.token.x=step.x;u.token.y=step.y;u.entry.econ.move=(u.entry.econ.move||0)+step.cost;event(b,w,u.name+' 移动到 '+step.x+','+step.y,{kind:'move',actionId:p.id,actorId:u.id});}
 if(step.type==='reaction'){if(incapacitated(u)||isSurprised(u)||u.entry.econ.reaction){p.cursor++;await commit(b,w);continue}if(u.pc&&step.accepted==null){p.reaction={actorId:u.id,targetId:step.targetId,label:'是否对离开触及的目标进行机会攻击？'};await commit(b,w);return {ok:true,status:'awaiting_reaction'}}if(step.accepted!==false){u.entry.econ.reaction=true;const target=entity(w,step.targetId),ac=target.pc?check(await ops['party.sheet']({id:target.pc.id})).sheet.ac:target.token.ac;p.steps.splice(p.cursor+1,0,{type:'attack',actorId:u.id,targetId:step.targetId,ability:step.ability,ac});}}
 if(step.type==='attack'){const t=entity(w,step.targetId),ab=step.ability||p.ability;if(t.hp<=0){p.cursor++;await commit(b,w);continue}const ranged=!!ab.ranged,near=w.map.tokens.some(tk=>tk.kind!=='effect'&&tk.kind!==u.kind&&tk.hp>0&&distance(u.token,tk)<=5);const own=u.conditions.map(c=>c.key||c),conditions=t.conditions.map(c=>c.key||c);let advantage=own.includes('invisible')||conditions.some(c=>['blinded','restrained','paralyzed','unconscious'].includes(c)),disadvantage=ranged&&near||own.some(c=>['prone','poisoned','restrained','blinded','frightened'].includes(c))||conditions.includes('invisible');if(conditions.includes('prone')){if(distance(u.token,t.token)<=5)advantage=true;else disadvantage=true}const adv=advantage===disadvantage?'normal':advantage?'adv':'dis';const r=await roll(b,w,p,'1d20'+signed(ab.attack),ab.name+' · 命中',u.id,null,tag,adv);if(!r)return {ok:true,status:'awaiting_roll'};b=await load();w=await capture();p=b.active;const nat=r.dice?.[0],ac=step.ac??t.token.ac;const hit=nat===20||(nat!==1&&r.total>=ac);event(b,w,ab.name+(hit?' 命中 ':' 未命中 ')+t.name,{kind:'attack',actionId:p.id,total:r.total,ac,hit,targetId:t.id});if(hit){const critical=nat===20||(distance(u.token,t.token)<=5&&conditions.some(c=>['paralyzed','unconscious'].includes(c)));const expr=critical?ab.damage.replace(/(\d+)d/g,(_,n)=>Number(n)*2+'d'):ab.damage;p.steps.splice(p.cursor+1,0,{type:'damage',actorId:u.id,targetId:t.id,expr,critical});}}
 if(step.type==='damage'||step.type==='heal'||step.type==='temp'){const r=await roll(b,w,p,step.expr,p.ability.name+' · '+(step.type==='damage'?'伤害':'效果'),u.id,null,step.shared?'shared-damage':tag);if(!r)return {ok:true,status:'awaiting_roll'};b=await load();w=await capture();p=b.active;const total=Math.max(0,r.total),t=entity(w,step.targetId);if(step.type==='damage')await damage(b,w,t.id,step.half?Math.floor(total/2):total,step.critical);if(step.type==='heal'){hp(w,t,Math.min(t.max,t.hp+total),t.temp);if(t.pc)delete t.pc.battleDeath;event(b,w,t.name+' 恢复 '+total+' HP',{kind:'heal',actionId:p.id})}if(step.type==='temp'&&total>t.temp){hp(w,t,t.hp,total);const id='fx-'+randomUUID();if(t.pc)t.pc.hp.tempEffect=id;w.session.effects=w.session.effects.filter(e=>!(e.temp!=null&&e.targetId===t.id));w.session.effects.push({id,name:p.ability.name,actorId:u.id,targetId:t.id,temp:total,expiresAt:w.session.clock+3600});event(b,w,t.name+' 获得 '+total+' 临时生命',{actionId:p.id})}}
 if(step.type==='save'){const t=entity(w,step.targetId),r=await roll(b,w,p,'1d20'+signed(step.bonus),p.ability.name+' · '+p.ability.save+' 豁免',t.id,p.ability.dc,tag);if(!r)return {ok:true,status:'awaiting_roll'};b=await load();w=await capture();p=b.active;if(!r.success||p.ability.half)p.steps.splice(p.cursor+1,0,{type:'damage',targetId:t.id,expr:p.ability.damage,half:r.success,shared:true});event(b,w,t.name+' 豁免'+(r.success?'成功':'失败'),{actionId:p.id,total:r.total});}
 if(step.type==='effect'){if(p.ability.concentration)w.session.effects=w.session.effects.filter(e=>!e.concentration||e.actorId!==u.id);w.session.effects.push({id:'fx-'+randomUUID(),name:p.ability.name,spell:p.ability.id,actorId:u.id,concentration:!!p.ability.concentration,expiresAt:w.session.clock+p.ability.durationSeconds,area:p.area,mapId:w.map.id,mapName:w.map.name});event(b,w,p.ability.name+' 已生效',{actionId:p.id});}
 p.cursor++;await commit(b,w);
 }throw Error('动作步骤超出上限，请检查当前计划。')};
 const submit=async args=>{await recover();let b=await load();if(!args.actionId||!/^[a-zA-Z0-9_-]{1,100}$/.test(args.actionId))throw Error('需要稳定 actionId。');if(b.receipts[args.actionId])return {ok:true,duplicate:true,receipt:b.receipts[args.actionId]};if(b.active?.id===args.actionId)return {ok:true,duplicate:true,status:b.active.waiting?'awaiting_roll':'resolving'};const previewed=await preview(args);if(previewed.needsDM)throw Error('此能力需要 DM 裁定，请先选择目标并发送意图。');if(args.version!==previewed.version)throw Error('场景已经变化，请重新预览。');let w=await capture(),u=entity(w,args.actorId),ab=previewed.ability,steps=[];
 if(ab.kind==='summon'){
 const old=w.map.tokens.find(t=>t.spell==='mageHand'&&t.ownerId===u.id);
 if(ab.id==='mageHandControl'){Object.assign(old,previewed.point)}else{
  w.map.tokens=w.map.tokens.filter(t=>!(t.spell==='mageHand'&&t.ownerId===u.id));w.session.effects=w.session.effects.filter(e=>!(e.spell==='mageHand'&&e.actorId===u.id));
  if(ab.id==='mageHand'){const id='hand-'+randomUUID();w.map.tokens.push({id,name:'法师之手',kind:'effect',spell:'mageHand',ownerId:u.id,...previewed.point,size:1,speed:30,note:'幽灵手 · 由施法者动作操控，不能攻击'});w.session.effects.push({id:'fx-'+randomUUID(),name:'法师之手',spell:'mageHand',actorId:u.id,tokenId:id,mapId:w.map.id,expiresAt:w.session.clock+60,concentration:false})}
 }
 if(w.combat.active){u.entry.econ={...u.entry.econ,action:true}}else w.session.needsResume=true;
 const result={id:args.actionId,kind:'battle',status:'complete',result:{ability:ab.name,origin:previewed.point,actorId:u.id}};w.session.completed.push(result);b.receipts[args.actionId]=result;event(b,w,u.name+' · '+ab.name+(previewed.point?' → '+previewed.point.x+','+previewed.point.y:''),{actionId:args.actionId});await commit(b,w);return {ok:true,status:'complete',summary:'法师之手已同步到地图。'};
 }
 if(ab.kind==='move'){let prev=u.token;const reacted=new Set();for(const point of previewed.path){for(const e of w.combat.order){const other=entity(w,e.tokenId||e.pcId||e.id);if(other.kind===u.kind||!other.token||incapacitated(other)||isSurprised(other)||reacted.has(other.id)||other.entry.econ?.reaction||u.entry.econ?.disengage)continue;const profile=(await catalog(w,other.id)).items.find(i=>i.id==='weapon'&&!i.ranged),reach=profile?.range||5;if(distance(prev,other.token)<=reach&&distance(point,other.token)>reach){if(!profile)throw Error('沿途敌人的机会攻击数据缺失，请让 DM 先补齐。');steps.push({type:'reaction',actorId:other.id,targetId:u.id,ability:profile});reacted.add(other.id)}}const difficult=['~',',','x','f'].includes(w.map.terrain[point.y]?.[point.x]);steps.push({type:'move',...point,cost:difficult?10:5});prev=point;}}
 else{u.entry.econ=u.entry.econ||{};u.entry.econ[ab.cost]=true;if(ab.id==='weapon')u.entry.econ.weaponAttacks=(u.entry.econ.weaponAttacks||0)+1;if(ab.key){if(ab.cost==='bonus')u.entry.econ.bonusSpell=true;if(ab.level>0)u.entry.econ.leveledSpell=true;}if(ab.requiresSlots)u.pc.battleResources.slots[ab.level]--;if(ab.kind==='effect')steps.push({type:'effect'});for(const t of previewed.targets||[]){if(ab.kind==='attack')steps.push({type:'attack',targetId:t.id,ac:t.ac});if(ab.kind==='save')steps.push({type:'save',targetId:t.id,bonus:t.save});if(['heal','temp'].includes(ab.kind))steps.push({type:ab.kind,targetId:t.id,expr:ab.damage});if(ab.kind==='auto')for(let n=0;n<(ab.repeat||1);n++)steps.push({type:'damage',targetId:t.id,expr:ab.damage});}}
 b.active={id:args.actionId,actorId:u.id,ability:ab,targetIds:(previewed.targets||[]).map(t=>t.id),area:previewed.area,steps,cursor:0,results:{},status:'resolving',autoDice:args.autoDice===true};w.session.needsResume=false;event(b,w,u.name+' 使用 '+ab.name,{actionId:args.actionId,actor:u.name});await commit(b,w);return drive()};
 reg('battle.preview',preview,'read');
 reg('battle.submit',submit);
 reg('battle.get',async args=>{
  const saved=await load();if(saved.active&&!saved.active.waiting&&!saved.active.reaction)await drive();
  const b=await load(),w=await capture(),turn=w.combat.order[w.combat.turnIndex];
  const actorId=args.actorId||turn?.tokenId||turn?.pcId||Object.keys(w.chars)[0];
  const playerId=w.chars[args.playerId]?args.playerId:(w.chars[turn?.pcId||actorId]?.id||Object.keys(w.chars)[0]);
  const player=playerId?await catalog(w,playerId):{items:[],slots:[]};
  return {ok:true,aidm:(await ops['controls.get']({})).aidm,version:version(w),turnKey:w.combat.round+':'+turn?.id,active:b.active?{id:b.active.id,actorId:b.active.actorId,ability:b.active.ability.name,waiting:b.active.waiting,reaction:b.active.reaction}:null,events:w.log.entries.map((e,i)=>({...e,id:e.id||'log-'+e.seq+'-'+i,text:[e.text,e.detail].filter(Boolean).join(' · ')})),combat:w.combat,map:w.map,request:w.session.requests[0]||null,effects:w.session.effects.map(e=>({...e,remainingSeconds:e.expiresAt==null?null:Math.max(0,e.expiresAt-w.session.clock)})),dice:w.dice.pending,actors:Object.values(w.chars).map(pc=>({id:pc.id,name:pc.name,hp:pc.hp,death:pc.battleDeath})),actorId,playerId,player,pause:flowPause(b,w),blockedReason:flowPause(b,w)?.reason||(w.dice.pending.length?'等待投骰（包括先攻）':w.session.requests.length?'等待地图选择':w.combat.active?(isSurprised(entity(w,actorId))?'当前单位措手不及，首次回合需空过':incapacitated(entity(w,actorId))?'当前单位无法行动':w.chars[turn?.pcId||actorId]?'玩家回合':'等待 DM 处理 '+turn?.name):'自由探索：选择行动后交给 DM'),...(actorId?await catalog(w,actorId):{items:[]})};
 },'read');
 reg('battle.resources',async args=>{const b=await load(),w=await capture();if(b.active)throw Error('行动进行中不能改资源。');const u=entity(w,args.actorId),data=await catalog(w,u.id);if(!u.pc)throw Error('只设置玩家资源。');const slots={};for(const s of data.slots){const n=Number(args.slots?.[s.lv]);if(!Number.isInteger(n)||n<0||n>s.max)throw Error('法术位余额必须在0到容量之间。');slots[s.lv]=n}u.pc.battleResources={slots,confirmedAt:new Date().toISOString()};await commit(b,w);return {ok:true,summary:'已记录真实剩余法术位。'}});
 reg('battle.begin',async args=>{const b=await load(),w=await capture(),u=entity(w,args.actorId);if(w.combat.active)activeCheck(w,u);else if(!u.pc)throw Error('探索行动只用于玩家。');if(b.active||w.session.requests.length)throw Error('请先完成当前请求。');const ab=args.abilityId==='move'?{id:'move',name:'移动',kind:'move'}:(await catalog(w,u.id)).items.find(x=>x.id===args.abilityId);if(!ab)throw Error('没有此能力。');const req={id:'q-'+randomUUID(),actorId:u.id,label:ab.name,kind:ab.kind==='move'?'move':ab.placement?'point':ab.shape?'area':'target',battleAbility:ab.id,needsDM:ab.kind!=='summon'&&(!w.combat.active||ab.kind==='dm'),exploration:!w.combat.active,count:ab.count||1,range:ab.range,shape:ab.shape,size:ab.size,dir:'n',self:ab.self,mapId:w.map.id,turnId:u.entry?.id||null,round:w.combat.round};w.session.requests.push(req);w.session.needsResume=false;await commit(b,w);return {ok:true,request:req,summary:'请在地图选择 '+ab.name+' 的目标或位置。'}});
 reg('interaction.answer',async args=>{const w=await capture(),req=w.session.requests[0];if(!req?.battleAbility)return baseInteraction(args);if(req.id!==args.id)throw Error('请求已失效。');if(req.exploration&&req.needsDM){if(w.combat.active)throw Error('已进入战斗，请重新选择行动。');return baseInteraction(args)}if(req.mapId!==w.map.id||req.round!==w.combat.round||(!req.exploration&&req.turnId!==w.combat.order[w.combat.turnIndex]?.id))throw Error('请求对应的地图或回合已变化。');if(req.needsDM){activeCheck(w,entity(w,req.actorId));if(new Set(args.targetIds||[]).size!==(args.targetIds||[]).length)throw Error('目标不能重复。');for(const id of args.targetIds||[])if(!w.map.tokens.some(t=>t.id===id&&!t.hidden))throw Error('目标不在当前可见地图上。');const b=await load();w.session.requests.shift();w.session.completed.push({...req,status:'complete',result:{targetIds:args.targetIds||[],origin:args.x==null?null:{x:args.x,y:args.y},needsDM:true}});w.session.needsResume=true;await commit(b,w);return {ok:true,summary:'玩家法术及目标已交给 DM 查规则裁定，尚未扣资源或生效。'}}const input={...args,actorId:req.actorId,abilityId:req.battleAbility};const pv=await preview(input);const b=await load();w.session.requests.shift();await commit(b,w);const current=await preview(input);return submit({...input,actionId:req.id,version:current.version,autoDice:args.autoDice})});
 reg('dice.answer',async args=>{const b=await load(),w=await capture(),req=w.dice.pending[0],done=w.dice.done.find(d=>d.id===args.id);if(done)return {ok:true,...done,duplicate:true};if(!req?.battleAction){const result=await baseAnswer(args);if(result.ok&&(await load()).active)await drive();return result}if(req.id!==args.id||b.active?.waiting?.id!==args.id)throw Error('请先完成当前行动的队首骰子。');const r=check(rollExpr(req.expr,req.advantage)),result={...req,...r,success:req.dc==null?null:r.total>=req.dc};w.dice.pending.shift();w.dice.done.push(result);b.active.results[b.active.waiting.tag]=result;b.active.waiting=null;event(b,w,req.label+'：'+r.detail,{kind:'roll',actionId:b.active.id,actor:req.actor,total:r.total});await commit(b,w);const next=await drive();return {ok:true,...result,next}});
 reg('dice.cancel',async args=>{const w=await capture();if(w.dice.pending[0]?.battleAction)throw Error('已消耗行动的骰子不能丢弃；请完成投骰后继续。');return baseCancel(args)});
 reg('battle.reaction',async args=>{const b=await load(),w=await capture();if(!b.active?.reaction||b.active.id!==args.actionId)throw Error('反应窗口已失效。');b.active.steps[b.active.cursor].accepted=args.accept===true;b.active.reaction=null;await commit(b,w);return drive()});
 reg('battle.deathSave',async()=>{const b=await load(),w=await capture(),e=w.combat.order[w.combat.turnIndex],u=entity(w,e?.tokenId||e?.pcId||e?.id);if(!w.combat.active||!u.pc||u.hp!==0||u.pc.battleDeath?.dead||u.pc.battleDeath?.stable||b.active||w.dice.pending.length||w.session.requests.length||e.econ.deathSave)throw Error('当前不能进行死亡豁免。');e.econ.deathSave=true;b.active={id:'death-'+randomUUID(),actorId:u.id,ability:{name:'死亡豁免'},targetIds:[],steps:[{type:'death'}],cursor:0,results:{}};await commit(b,w);return drive()});
 reg('battle.utility',async args=>{const b=await load(),w=await capture(),u=entity(w,args.actorId);activeCheck(w,u);if(b.active||w.session.requests.length||u.entry.econ.action||!['dash','disengage'].includes(args.kind))throw Error('当前不能使用此动作。');u.entry.econ.action=true;if(args.kind==='dash')u.entry.econ.extraMove=(u.entry.econ.extraMove||0)+(u.token.speed||30);else u.entry.econ.disengage=true;event(b,w,u.name+(args.kind==='dash'?' 疾走':' 撤离'));await commit(b,w);return {ok:true}});
 reg('battle.endTurn',async args=>{const w=await capture(),current=w.combat.order[w.combat.turnIndex];if(args.turnKey&&args.turnKey!==w.combat.round+':'+current?.id)return {ok:true,duplicate:true};if((await load()).active)throw Error('当前行动还未完成。');const result=check(await baseNext({})),s=await state();s.completed.push({id:'turn-'+randomUUID(),kind:'turn',status:'complete',result:{actorId:current?.pcId||current?.tokenId,round:w.combat.round,events:(await load()).events.filter(e=>e.round===w.combat.round).slice(-20)}});s.completed=s.completed.slice(-40);s.needsResume=true;await save(s);return {...result,summary:'回合已结束，最新状态已提交给 DM。'}});
 const enemyStep=async()=>{if(!(await readCombat()).active)return {ok:true,status:'exploration',summary:'当前为自由模式，不执行敌方战斗回合。'};const b=await load(),w=await capture();if(b.active)return drive();const e=w.combat.order[w.combat.turnIndex],u=entity(w,e?.tokenId||e?.pcId||e?.id);const paused=flowPause(b,w);if(paused)return pauseFlow(b,w,paused.reason);if(u.pc)throw Error('这是玩家回合，请由玩家操作。');if(incapacitated(u)||isSurprised(u)){event(b,w,u.name+(isSurprised(u)?' 措手不及，首次回合空过':' 无法行动，结束回合'),{kind:'turn'});await commit(b,w);return baseNext({})}if(u.entry.econ.action)return baseNext({});const ab=(await catalog(w,u.id)).items.find(x=>x.id==='weapon');if(!ab)throw Error(u.name+'的攻击资料尚未完整绑定，请 DM 查阅该单位的动作原文并绑定后继续。');const targets=w.map.tokens.filter(t=>t.kind==='pc'&&t.hp>0).sort((x,y)=>distance(u.token,x)-distance(u.token,y));if(!targets.length)return pauseFlow(b,w,'没有可攻击的玩家，等待 DM 裁定。');const target=targets[0];if(distance(u.token,target)>ab.range){let best=null;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const r=route(w.map,u.token,{x:target.x+dx,y:target.y+dy});if(r&&(!best||r.cost<best.cost))best=r}if(best?.path.length){let cost=0,end=null;for(const cell of best.path){cost+=['~',',','x','f'].includes(w.map.terrain[cell.y]?.[cell.x])?10:5;if(cost>(u.token.speed||30)-(u.entry.econ.move||0))break;end=cell}if(end){const input={actorId:u.id,abilityId:'move',...end},pv=await preview(input);return submit({...input,version:pv.version,actionId:'npc-'+randomUUID(),autoDice:true})}}return baseNext({})}if(u.entry.econ.action)return baseNext({});const input={actorId:u.id,abilityId:'weapon',targetIds:[target.id]},pv=await preview(input);return submit({...input,version:pv.version,actionId:'npc-'+randomUUID(),autoDice:true})};
 reg('battle.enemy',enemyStep);
 reg('battle.surprise',async args=>{const b=await load(),w=await capture();if(!w.combat.active||w.combat.round!==1||!args.reason||!args.actorIds?.length)throw Error('仅首次回合前可登记已确认的突袭。');const units=args.actorIds.map(id=>entity(w,id));if(units.some(u=>!u.entry||u.entry.firstTurnEnded||u.entry.econ?.action||u.entry.econ?.move))throw Error('单位已经行动，不能补加突袭。');for(const u of units){const c={key:'surprised',name:'措手不及',rounds:null};u.entry.conditions=[...(u.entry.conditions||[]).filter(x=>!surpriseCondition(x)),c];if(u.pc)u.pc.conditions=[...(u.pc.conditions||[]).filter(x=>!surpriseCondition(x)),c];event(b,w,u.name+' 措手不及：'+args.reason,{kind:'state'})}await commit(b,w);return {ok:true,summary:'突袭已登记，首次回合不能行动，结束后恢复反应。'}});
 reg('battle.npcEnd',async args=>{const b=await load(),w=await capture(),e=w.combat.order[w.combat.turnIndex];if(!w.combat.active||!e)throw Error('尚未进入回合制。');if(args.turnKey!==w.combat.round+':'+e.id)throw Error('回合已变化，请重新读取。');const u=entity(w,args.actorId);if(u.pc||u.entry?.id!==e.id)throw Error('只能结束当前NPC回合，不能替玩家结束。');if(!args.reason?.trim()||b.active||w.dice.pending.length||w.session.requests.length)throw Error('需要原因，且先完成当前请求。');event(b,w,u.name+' 结束回合：'+args.reason,{kind:'turn'});await commit(b,w);return baseNext({})});
 reg('battle.awaitDeathSave',async()=>{let b=await load(),w=await capture();if(!noStanding(w)||b.active||w.dice.pending.length||w.session.requests.length)throw Error('仅全员倒地且无待办动作时可确认敌方等待。');if(!w.combat.order.some(e=>{const pc=w.chars[e.pcId||e.tokenId];return pc&&pc.hp.current===0&&!pc.battleDeath?.dead&&!pc.battleDeath?.stable}))throw Error('没有需要死亡豁免的角色，请 DM 裁定遭遇结果。');for(let n=0;n<w.combat.order.length;n++){const e=w.combat.order[w.combat.turnIndex],pc=w.chars[e.pcId||e.tokenId];if(pc){b.pause=null;w.session.needsResume=false;await commit(b,w);return {ok:true,status:'player_turn',current:e.name}}event(b,w,e.name+' 暂不行动（玩家确认），按先攻推进',{kind:'turn'});await commit(b,w);check(await baseNext({}));b=await load();w=await capture()}throw Error('未找到玩家回合。')});
 reg('battle.advance',async()=>{for(let n=0;n<80;n++){const b=await load(),w=await capture(),e=w.combat.order[w.combat.turnIndex];if(!w.combat.active)return {ok:true,status:'exploration'};if(w.dice.pending.length||w.session.requests.length||b.active?.reaction||b.active?.waiting)return {ok:true,status:'waiting_player',current:e?.name};if(!e)throw Error('先攻列表为空。');const paused=flowPause(b,w);if(paused)return pauseFlow(b,w,paused.reason);if(w.chars[e.pcId||e.tokenId])return {ok:true,status:'player_turn',current:e.name};const signature=JSON.stringify([w.combat,w.map,b.active]);let r;try{r=check(await enemyStep())}catch(error){return pauseFlow(await load(),await capture(),error.message)}if(r.status==='waiting_dm')return r;const after=await capture();if(signature===JSON.stringify([after.combat,after.map,(await load()).active]))throw Error('敌方行动未改变状态，请 DM 核对后使用 battle.npcEnd。')}throw Error('敌方处理达到安全步数上限，请继续处理。')});
 reg('battle.explore',async args=>{const w=await capture();if(w.combat.active)throw Error('回合制中请结束回合。');const u=entity(w,args.actorId);if(!u.pc||w.dice.pending.length||w.session.requests.length)throw Error('请先完成待办并选择真实玩家。');w.session.completed.push({id:'explore-'+randomUUID(),kind:'exploration',status:'complete',result:{actorId:u.id,position:u.token?{x:u.token.x,y:u.token.y}:null,intent:args.intent||'观察移动后的环境'}});w.session.needsResume=true;await save(w.session);return {ok:true,summary:'探索位置与行动已提交，等待 DM。'}});
 installCharacter({reg,ops,load,capture,commit,event,entity,check,loadSrd});
 return {recover};
}
