import {createHash} from 'node:crypto';
import path from 'node:path';
import {readJson,saveJson} from './gameplay.mjs';
export const actionSchema={type:'object',additionalProperties:false,required:['action'],properties:{
 action:{type:'string',enum:['roll','turn','free','move','target','area','town']},expr:{type:'string'},label:{type:'string'},actorId:{type:'string'},dc:{type:'number'},advantage:{type:'string',enum:['normal','adv','dis']},range:{type:'number'},count:{type:'number'},shape:{type:'string',enum:['sphere','cube','cone','line','cylinder']},size:{type:'number'},spell:{type:'string'},name:{type:'string'},places:{type:'array',items:{type:'object',properties:{name:{type:'string'},description:{type:'string'}},required:['name'],additionalProperties:false}},npcs:{type:'array',items:{type:'object',properties:{name:{type:'string'},place:{type:'string'},description:{type:'string'}},required:['name'],additionalProperties:false}}
}};
export function extractActions(content){
 const actions=[],errors=[];const text=String(content||'').replace(/```dm-action\s*([\s\S]*?)```/gi,(_,raw)=>{try{const v=JSON.parse(raw);for(const a of(Array.isArray(v)?v:[v])){if(!a||typeof a!=='object'||!actionSchema.properties.action.enum.includes(a.action))throw Error('未知 DM 动作');actions.push(a)}}catch(e){errors.push(e.message)}return ''});return {text:text.trim(),actions:actions.slice(0,8),errors};
}
export function missedRoll(text){const t=String(text||'').replace(/```[\s\S]*?```/g,'');return /(?:请|现在|需要|开始)(?:你|玩家|进行|做|来|先|一次|一项|个|次|一下|\s|\*|[:：]){0,12}(?:投掷|掷骰|投骰|.{0,10}(?:检定|豁免))/.test(t)&&!/(?:如果|若你|是否|确定.*[?？]|你怎么选)/.test(t)}
export function townPlan(a){
 const places=(a.places?.length?a.places:[{name:'入口'},{name:'广场'},{name:'客栈'},{name:'集市'}]).slice(0,12),w=32,h=Math.max(18,Math.ceil(places.length/3)*8+2),grid=Array.from({length:h},()=>Array(w).fill('g')),locations=[];
 for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++)if(x%10>=7||y%8>=6)grid[y][x]='s';
 const tokens=[];places.forEach((p,i)=>{const x=2+(i%3)*10,y=2+Math.floor(i/3)*8;for(let yy=y;yy<y+4;yy++)for(let xx=x;xx<x+6;xx++)grid[yy][xx]=yy===y||yy===y+3||xx===x||xx===x+5?'b':'w';grid[y+3][x+3]='+';locations.push({id:'place-'+i,name:String(p.name).slice(0,60),x:x+3,y:y+5,description:String(p.description||'').slice(0,400)});tokens.push({id:'place-'+i,name:p.name,kind:'object',x:x+3,y:y+1,note:p.description||'',size:1})});
 const used=new Set();(a.npcs||[]).slice(0,30).forEach((npc,i)=>{const p=locations.find(p=>p.name===npc.place)||locations[i%locations.length];let x=p.x-2+(i%4),y=p.y;while(used.has(x+','+y)){x++;if(x>=w-1){x=1;y=Math.min(h-1,y+1)}}used.add(x+','+y);tokens.push({id:'npc-'+i,name:String(npc.name).slice(0,60),kind:'ally',x,y,note:npc.description||'',size:1})});
 return {name:a.name||'城镇示意图',w,h,terrain:grid.map(r=>r.join('')),tokens,locations};
}
const tidy=s=>String(s).replace(/[\s,，]/g,'');
const containsNumber=(quote,n)=>new RegExp('(?<![0-9])'+n+'(?![0-9])').test(String(quote).replace(/(?<=[0-9])[,，](?=[0-9]{3}(?:[^0-9]|$))/g,''));
export function installCampaign(a){
 const {ops,register,root,readPc,persist,modules,defaultThresholds}=a,file=path.join(root,'progression.json');let chain=Promise.resolve();
 const load=()=>readJson(file,{profiles:{},rewards:{}}),adventure=()=>readJson(path.join(root,'adventure.json'),{});
 const reg=(n,fn,mutate=true)=>register(n,async args=>{const run=()=>fn(args||{});try{if(!mutate)return await run();const work=chain.then(run);chain=work.catch(()=>{});return await work}catch(e){return {ok:false,error:e.message}}});
 const evidence=async(sourceId,quote)=>{const selected=await adventure();if(!selected.moduleId)throw Error('请先选择已导入的模组。');const entry=(await modules.entries()).find(e=>e.id===sourceId&&e.id.startsWith('upload:'+selected.moduleId+':'));if(!entry||!quote||!tidy(entry.text).includes(tidy(quote)))throw Error('请提供当前模组可核对的 sourceId 和原文 quote。');return selected.moduleId};
 reg('campaign.progression.get',async()=>{const s=await load(),m=await adventure();return {ok:true,moduleId:m.moduleId||null,profile:s.profiles[m.moduleId]||{thresholds:await defaultThresholds(),source:'默认 5e 经验门槛（模组尚未另行设定）'},rewards:Object.values(s.rewards).filter(r=>r.moduleId===m.moduleId)}},false);
 reg('campaign.progression.set',async args=>{const moduleId=await evidence(args.sourceId,args.quote),base=await defaultThresholds();if(!Array.isArray(args.thresholds)||args.thresholds.length<2||args.thresholds.length>20)throw Error('thresholds 为从1级开始的累计经验数组，2–20项。');const table=[...base];args.thresholds.forEach((n,i)=>{if(!Number.isSafeInteger(n)||n<0)throw Error('经验门槛必须为非负整数。');if(i&& !containsNumber(args.quote,n))throw Error('经验门槛缺少对应原文数值：'+n);table[i]=n});if(table[0]!==0||table.some((n,i)=>i&&n<=table[i-1]))throw Error('累计经验须从0开始，逐级递增；请补足后续阈值。');const s=await load();s.profiles[moduleId]={thresholds:table,source:args.sourceId,quote:args.quote};await saveJson(file,s);return {ok:true,profile:s.profiles[moduleId],summary:'已按模组设置升级门槛。'}});
 reg('campaign.resolve',async args=>{const moduleId=await evidence(args.sourceId,args.quote);if(!args.objectiveId||!args.title||!['combat','negotiation','stealth','other'].includes(args.method))throw Error('需要稳定的 objectiveId、title 和解决方式 method。');if(!Number.isSafeInteger(args.amount)||args.amount<=0||!containsNumber(args.quote,args.amount))throw Error('奖励经验必须是模组原文可核对的正整数。');if(!['each','split'].includes(args.per))throw Error('请明确模组奖励是 each 每人还是 split 队伍平分。');const s=await load(),key=createHash('sha256').update(moduleId+':'+args.objectiveId).digest('hex');let receipt=s.rewards[key];const sameQuote=Object.values(s.rewards).find(r=>r.moduleId===moduleId&&r.sourceId===args.sourceId&&tidy(r.title)===tidy(args.title)&&tidy(r.quote)===tidy(args.quote));if(!receipt&&sameQuote)receipt=sameQuote;if(receipt?.status==='done')return {ok:true,duplicate:true,receipt,summary:'该目标已结算，不会因更换解决方式重复发经验。'};
 if(!receipt){const party=await ops['party.list']({}),ids=args.ids?.length?[...new Set(args.ids)]:party.items.map(p=>p.id);if(!ids.length||ids.some(id=>!party.items.some(p=>p.id===id)))throw Error('奖励角色列表无效。');const shares=ids.map((id,i)=>({id,amount:args.per==='each'?args.amount:Math.floor(args.amount/ids.length)+(i<args.amount%ids.length?1:0)}));receipt={...args,key,moduleId,shares,status:'pending',t:new Date().toISOString()};s.rewards[key]=receipt;await saveJson(file,s)}
 for(const share of receipt.shares){const pc=structuredClone(await readPc(share.id));pc.meta=pc.meta||{};pc.meta.moduleRewards=pc.meta.moduleRewards||{};if(pc.meta.moduleRewards[receipt.key])continue;pc.xp=(Number(pc.xp)||0)+share.amount;pc.meta.moduleRewards[receipt.key]=share.amount||true;const r=await persist(pc);if(!r.ok)throw Error(r.error||'经验保存失败，下次重试会续接。')}
 receipt.status='done';await saveJson(file,s);await ops['session.save']({});await ops['log.append']({entries:[{kind:'xp',actor:'DM',text:args.title+'（'+args.method+'）',detail:receipt.shares.map(p=>p.id+' +'+p.amount+' XP').join('；')}]});return {ok:true,receipt,summary:'目标已解决并发放经验：'+receipt.shares.map(p=>p.amount+' XP').join(' / ')}});

 reg('scene.town',async args=>{if((await ops['combat.get']({})).active)throw Error('回合制进行中，先切换为自由模式。');const plan=townPlan(args),old=await ops['map.get']({});for(const [i,pc] of (old.tokens||[]).filter(t=>t.kind==='pc').entries())plan.tokens.push({...pc,x:1+i%6,y:0});const r=await ops['map.create'](plan);if(!r.ok||r.saved===false)return r;const scene=await ops['map.get']({});await saveJson(path.join(root,'town.json'),{mapId:scene.id,locations:plan.locations});return {...r,locations:plan.locations,summary:'已绘制城镇示意图，可点击地点表达意图；这是示意布局，不是原书测绘图。'}});
 reg('scene.visit',async args=>{const town=await readJson(path.join(root,'town.json'),null),map=await ops['map.get']({});if((await ops['combat.get']({})).active)throw Error('回合制下请通过当前回合请求行动。');const location=town?.mapId===map.id&&town.locations.find(p=>p.id===args.id);if(!location)throw Error('地点不存在于当前示意图。');return {ok:true,location,message:'我想去「'+location.name+'」。请根据模组描述抵达过程和当地 NPC，不自动进入战斗。'}});
 const town=async()=>{const t=await readJson(path.join(root,'town.json'),null),m=await ops['map.get']({});return t?.mapId===m.id?t:null};
 for(const name of ['session.pending','scene.get']){const original=ops[name];reg(name,async args=>{const r=await original(args);return {...r,mode:r.combat?.active?'turn':'free',town:await town(),...(name==='scene.get'?{progression:await ops['campaign.progression.get']({})}:{})}},false)}
 reg('dm.action',async args=>{switch(args.action){case 'roll':{const party=await ops['party.list']({});let id=args.actorId;if(id&&!party.items.some(p=>p.id===id)){const matched=party.items.filter(p=>p.name===id);if(matched.length===1)id=matched[0].id}if(!id&&party.items.length===1)id=party.items[0].id;if(!party.items.some(p=>p.id===id))throw Error('请明确需要投骰的玩家角色 ID。');return ops['dice.request']({...args,actorId:id,label:args.label||'DM 要求的判定'})}case 'turn':return ops['combat.mode']({mode:'turn'});case 'free':return ops['combat.mode']({mode:'free'});case 'move':case 'target':case 'area':return ops['interaction.request']({...args,kind:args.action});case 'town':return ops['scene.town'](args);default:throw Error('未知动作。')}} ,false);
}

const str={type:'string'},num={type:'number'};
const obj=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false});
export const campaignTools=[
 ['dm.action','首选统一交互入口：roll 发起玩家投骰并等待；turn 进入回合制；free 自由移动；move 仅回合制且当前玩家；target/area 选目标/范围；town 绘制非战斗城镇。',actionSchema],
 ['combat.mode','切换 turn 回合制 / free 自由移动。free 不代表目标完成，不发经验、不清记录。',obj({mode:{type:'string',enum:['turn','free']}},['mode'])],
 ['campaign.progression.get','读取当前模组累计经验门槛、奖励与来源。',obj({})],
 ['campaign.progression.set','仅按当前模组原文设置累计经验门槛，无自定义规则时保持默认。',obj({thresholds:{type:'array',items:num},sourceId:str,quote:str},['thresholds','sourceId','quote'])],
 ['campaign.resolve','结算已解决的目标，战斗、谈判、潜行等方式同样有效。必须核对模组原文奖励、每人或均分，稳定目标ID防止重复奖励。',obj({objectiveId:str,title:str,method:{type:'string',enum:['combat','negotiation','stealth','other']},amount:num,per:{type:'string',enum:['each','split']},sourceId:str,quote:str,ids:{type:'array',items:str}},['objectiveId','title','method','amount','per','sourceId','quote'])]
];
export const campaignPrompt=`
【统一动作接口】优先 dm.action，参数是平铺对象：{"action":"roll","actorId":"实际角色ID","expr":"1d20+2","label":"察觉检定"}。请求一次后暂停等玩家；多个请求可同时建立，界面按顺序完成。不要只说“请投骰”而不调用。若供应商不支持工具调用，可输出 dm-action 围栏内的同结构 JSON（单对象或数组），系统执行后才视为成功。建议、假设和“如果你决定”不代表实际请求，不要提前投骰。
combat.active 是唯一回合制依据，mode=free 时玩家自由移动，禁止发 move 请求；明确进入战斗先建立实际单位再 action=turn，按先攻轮转。不能把玩家动手解释成所有敌人立即反击。手动切换 free 只是解除移动限制，不代表胜利。确认战斗结束仍用 combat.end 归档。
进入地点复杂或 NPC 较多的城镇时，依据已读模组用 action=town，name 城镇名、places:[{name,description}]、npcs:[{name,place,description}]，只画已知的地点和人物，不剧透；它是示意布局，不声称复刻原图。简单场景无需重画。不要在活跃战斗中换图。
目标解决后不论战斗、谈判、潜行或其他方式，都查模组的经验奖励，调用 campaign.resolve。objectiveId 稳定标识章节/遭遇，同目标不可重复领。sourceId 是 mod.read 的 upload: 条目ID，quote 为包含奖励数值与适用条件的原文，amount/per 严格对应原文。查不到明确奖励应说明待核对，不能乱发经验。准备模组时查阅升级章节；若有自定义经验表，campaign.progression.set 写入 thresholds（从1级0开始的累计经验）、sourceId、quote；没有则保留默认。里程碑升级按原文另行裁定，不虚构经验表。`;
