import {surpriseCondition,monsterName,meleeProfile,completeAttack} from './combat-state.mjs';
import {installBattle} from './battle.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';

export async function readJson(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch(e){if(e.code==='ENOENT')return fallback;throw e}}
export async function saveJson(file,value){await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.'+randomUUID()+'.tmp';try{await fs.writeFile(temp,JSON.stringify(value,null,2));await fs.rename(temp,file)}finally{await fs.unlink(temp).catch(()=>{})}return {ok:true}}
export async function migrateSession(oldRoot,root){
 for(const name of ['combat-log.json','adventure.json']){const from=path.join(oldRoot,'data',name),to=path.join(root,name);const data=await readJson(from,null);if(data&&!(await readJson(to,null))){await saveJson(to,data);const copied=await readJson(to,null);if(JSON.stringify(data)!==JSON.stringify(copied))throw Error('存档迁移校验失败：'+name);await fs.unlink(from)}}
}
export function sessionFiles(root){return {
 async readChat(legacy=[]){const file=path.join(root,'chat.json');const data=await readJson(file,null);if(data)return data.messages||[];if(legacy.length)await saveJson(file,{messages:legacy});return legacy},
 async writeChat(messages){return saveJson(path.join(root,'chat.json'),{messages})}
}}
const obj=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false});
const str={type:'string'},num={type:'number'},bool={type:'boolean'};
export const gameplayTools=[
 ['scene.get','读取权威场景：角色法术清单、坐标、唯一单位 ID、当前回合、待选目标、持续效果及投骰结果。',obj({})],
 ['interaction.request','暂停，要求当前玩家在地图移动、选目标或选法术范围原点。range/size 单位尺；所有角色引用必须用 ID。',obj({kind:{type:'string',enum:['move','target','area']},actorId:str,label:str,spell:str,range:num,count:num,targetKind:{type:'string',enum:['enemy','pc','ally','any']},shape:{type:'string',enum:['sphere','cube','cone','line','cylinder']},size:num,dir:str},['kind','actorId','label'])],
 ['effect.add','登记已生效的持续法术/临时生命。rounds为施法者回合数，durationSeconds为游戏时间；专注仅在受伤等触发时检定，不能每回合强制检定。temp不叠加。',obj({name:str,actorId:str,targetId:str,spell:str,rounds:num,durationSeconds:num,concentration:bool,temp:num,maxHpBonus:num,acBonus:num,requestId:str,trigger:{type:'string',enum:['start','end']},note:str},['name','actorId'])],
 ['effect.end','结束指定持续效果；专注中断应结束该施法者对应效果。',obj({id:str},['id'])],
 ['session.advance','推进战斗外游戏时间（秒），结算到期效果。不要用现实时间代替游戏时间。',obj({seconds:num},['seconds'])],
 ['dice.secret','DM 暗骰：仅适用于隐藏信息或 NPC 判定，必须说明原因；结果不进入公开骰盘。玩家正常检定使用 dice.request。',obj({expr:str,label:str,reason:str,actorId:str},['expr','label','reason'])],
 ['narration.say','在玩家对话区呈现 NPC 发言卡，speaker 为发言者名，text 为台词；不重复输出同一台词。',obj({speaker:str,text:str},['speaker','text'])]
];
export const gameplayPrompt=`\n【交互与规则约定：D&D 5e 2014】
scene.get 是权威现场，包含完整法术名清单；角色卡上的 fogCloud 是云雾术。判断会不会法术前读 scene.get / party.spells，不能从被截断的 party.sheet 断定没有法术。
先用工具更新地图/生命/效果，再描述成功的变更；工具失败不得叙述为成功。每次续接重新读取场景，不用旧坐标。
玩家的攻击、伤害、主动检定、豁免用 dice.request，必须给 expr、label、actorId；发起后等玩家完成，不能自行编造结果。NPC 可用 roll.dice；暗藏信息才用 dice.secret 并给 reason，被动检定直接用被动数值，不额外乱掷骰。这是本应用的公开/暗骰约定，不代表所有桌团只有一种公开方式。
战斗时仅当前单位行动。玩家移动用 interaction.request(kind=move)，目标用 target，范围法术用 area；等地图选择反馈。使用唯一 token ID，不使用模糊的“地精”。移动完成后检查机会攻击、掩体、距离与地形，再请求相应骰子。效果结算与战斗轮次以工具结果为准。
持续法术生效后 effect.add，带范围时关联已完成选择的 requestId；轮次/时间到期自动移除。专注只在受伤等规则触发时豁免，DC=max(10,伤害一半向下取整)，每个伤害来源分别判定。新专注会替换旧专注；失能或0 HP会终止专注。环境要求另行发起专注骰。临时 HP 先于本体扣除、不叠加；虚假生命按规则投骰后登记 temp 与3600秒持续时间。
NPC台词优先 narration.say。确认战斗结束才 combat.end，系统会先归档再清空战斗记录。筹备资料不向玩家剧透。`;

export function installGameplay(a){
 const {ops,register,root,loadSrd,readMap,writeMap,readCombat,writeCombat,combatView,readDice,writeDice,readPc,persist,readLog,writeLog,pushLog,rollExpr,readAi,writeAi}=a;
 const original={...ops};const file=path.join(root,'session.json');let chain=Promise.resolve(),resuming=false,resumeStarted=0,resumeRetryAt=0,resumeError='',recovery=async()=>{};
 const state=()=>readJson(file,{clock:0,requests:[],completed:[],effects:[],needsResume:false,revision:0});
 const save=async s=>{s.revision=(s.revision||0)+1;return saveJson(file,s)};
 const serial=(fn,saveAfter=true)=>args=>{const work=chain.then(async()=>{await recovery();const result=await fn(args||{});if(saveAfter&&result?.ok!==false){await syncCharacters();await checkpoint();}return result});chain=work.catch(()=>{});return work.catch(e=>({ok:false,error:e.message}))};
 const checkpoint=async()=>{const party=await original['party.list']({}),characters=[];for(const p of party.items||[])characters.push(await readPc(p.id));await saveJson(path.join(root,'current.json'),{schema:1,t:new Date().toISOString(),map:await readMap(),combat:await readCombat(),dice:await readDice(),battle:await readJson(path.join(root,'battle.json'),null),characters,session:await state()})};
 const reg=(name,fn,write=true)=>register(name,write?serial(async args=>{if(write!=='read'&&!name.startsWith('battle.')&&!['dice.answer','dice.cancel','session.save','narration.say'].includes(name)&&(await readJson(path.join(root,'battle.json'),{})).active)throw Error('当前行动尚未结算，请先完成骰子或反应。');return fn(args)},write!=='read'):async args=>{try{return await fn(args||{})}catch(e){return {ok:false,error:e.message}}});
 const check=r=>{if(r?.ok===false||r?.saved===false)throw Error(r.error||r.saveError||'保存失败');return r};

 const statCache=new Map();
 const hydrate=async()=>{await syncCharacters();const map=await readMap(),combat=await readCombat();let dirty=false;for(const tk of map.tokens){if(!['enemy','ally'].includes(tk.kind)||tk.ac!=null&&tk.statblockId&&completeAttack(tk))continue;const query=monsterName(tk.name),key=(tk.statblockId||'')+':'+query;let sb=statCache.get(key);if(!sb){sb=await original['mod.statblock'](tk.statblockId?{id:tk.statblockId,title:query}:{title:query});if(sb.ok&&completeAttack(meleeProfile(sb)))statCache.set(key,sb)}if(!sb.ok||sb.ac==null||(!tk.statblockId&&monsterName(sb.title)!==query))continue;const patch={ac:tk.ac??sb.ac,hp:tk.hp??sb.hp,max:tk.max??sb.hp,dex:tk.dex??sb.mods?.dex,saves:tk.saves||sb.saves||sb.mods,statblockId:sb.id,source:sb.book+' / '+sb.title,...meleeProfile(sb)};if(completeAttack(tk)){patch.damage=tk.damage;patch.attackBonus=tk.attackBonus;patch.reach=tk.reach}if(Object.entries(patch).some(([k,v])=>JSON.stringify(tk[k])!==JSON.stringify(v))){Object.assign(tk,patch);dirty=true}const entry=combat.order.find(e=>e.tokenId===tk.id);if(entry)Object.assign(entry,{ac:tk.ac,saves:tk.saves})}if(dirty){check(await writeMap(map));check(await writeCombat(combat))}};
 const syncCharacters=async()=>{const map=await readMap(),combat=await readCombat();let mapDirty=false,combatDirty=false;for(const p of (await original['party.list']({})).items||[]){const r=await ops['party.sheet']({id:p.id});if(!r.ok)continue;const sheet=r.sheet,entry=combat.order.find(e=>e.pcId===p.id||e.tokenId===p.id),token=map.tokens.find(t=>t.id===p.id||t.id===entry?.tokenId);const values={hp:sheet.hp.cur,max:sheet.hp.max,temp:sheet.hp.temp||0,ac:sheet.ac,saves:sheet.saves,conditions:sheet.conditions};for(const [object,kind] of [[token,'map'],[entry,'combat']])if(object&&Object.entries(values).some(([k,v])=>JSON.stringify(object[k])!==JSON.stringify(v))){Object.assign(object,values);if(kind==='map')mapDirty=true;else combatDirty=true}}if(mapDirty)check(await writeMap(map));if(combatDirty)check(await writeCombat(combat))};
 reg('enemy.bind',async args=>{const r=check(await original['enemy.bind'](args));statCache.clear();await hydrate();const token=(await readMap()).tokens.find(t=>t.id===args.tokenId);return {...r,token,attackReady:completeAttack(token),summary:completeAttack(token)?'已绑定角色简表与近战攻击资料':'已绑定角色简表；来源缺少可识别的近战攻击，请 DM 查阅动作原文。'}});
 reg('party.sheet',async args=>{const result=check(await original['party.sheet'](args)),s=await state(),pc=await readPc(args.id);result.sheet.hp.effects=s.effects.filter(e=>e.targetId===args.id||(!e.targetId&&e.actorId===args.id)).filter(e=>e.temp!=null||e.maxHpBonus!=null).map(e=>({id:e.id,name:e.name,temp:e.temp,maxHpBonus:e.maxHpBonus,rounds:e.rounds,remainingSeconds:e.expiresAt==null?null:Math.max(0,e.expiresAt-s.clock)}));result.sheet.slots=result.sheet.slots.map(slot=>({...slot,remaining:pc.battleResources?.slots?.[slot.lv]??null}));return result},false);
 for(const name of Object.keys(original).filter(n=>n.startsWith('sheet.')||['levelset.apply','pc.repair'].includes(n)))reg(name,args=>original[name](args));
 const unit=async id=>{const map=await readMap(),st=await readCombat();const entry=st.order.find(e=>e.id===id||e.tokenId===id||e.pcId===id);const token=map.tokens.find(t=>t.id===id||t.id===entry?.tokenId);let pc=null;const pcId=entry?.pcId||(token?.kind==='pc'?token.id:null);if(pcId)try{pc=await readPc(pcId)}catch{};if(!token&&!entry)try{pc=await readPc(id)}catch{};if(!token&&!entry&&!pc)throw Error('找不到单位 ID：'+id);return {map,st,entry,token,pc,id:token?.id||entry?.id||pc?.id,name:pc?.name||token?.name||entry?.name}};
 const current=st=>st.order[st.turnIndex];
 const assertTurn=(u)=>{if(u.st.active&&(u.pc?.conditions||u.entry?.conditions||[]).some(c=>surpriseCondition(c)||['incapacitated','unconscious','stunned','paralyzed','petrified'].includes(c.key)))throw Error('当前单位无法行动，请结束受限回合。');if(u.st.active&&current(u.st)?.id!==u.entry?.id)throw Error('还没轮到这个单位。')};
 const identity=u=>[u.id,u.entry?.id,u.entry?.tokenId,u.pc?.id].filter(Boolean);
 const syncHp=async(u,hp,temp)=>{if(u.pc){u.pc.hp.current=hp;u.pc.hp.temp=temp;check(await persist(u.pc))}if(u.token){u.token.hp=hp;u.token.temp=temp;check(await writeMap(u.map))}if(u.entry){u.entry.hp=hp;u.entry.temp=temp;check(await writeCombat(u.st))}};
 const endEffect=async(s,id)=>{const effect=s.effects.find(e=>e.id===id);if(!effect)return;if(effect.tokenId){const map=await readMap();map.tokens=map.tokens.filter(t=>t.id!==effect.tokenId);check(await writeMap(map))}if(effect.temp!=null&&effect.targetId){const u=await unit(effect.targetId);if(!u.pc||u.pc.hp.tempEffect===id){if(u.pc)delete u.pc.hp.tempEffect;await syncHp(u,Number(u.pc?.hp.current??u.token?.hp??u.entry?.hp)||0,0)}}if(effect.maxHpBonus!=null&&effect.targetId){const u=await unit(effect.targetId);if(u.pc){const max=Math.max(1,u.pc.hp.max-effect.maxHpBonus);u.pc.hp.max=max;await syncHp(u,Math.max(0,Math.min(max,u.pc.hp.current-effect.maxHpBonus)),u.pc.hp.temp||0)}}if(effect.acBonus!=null){const u=await unit(effect.targetId||effect.actorId);if(u.pc){u.pc.acBuffs=(u.pc.acBuffs||[]).filter(e=>e.id!==id);check(await persist(u.pc))}}s.effects=s.effects.filter(e=>e.id!==id)};
 const enqueue=async args=>{const label=args.label||args.why||args.reason;if(!args.expr||!label)throw Error('投骰需要 expr 和 label（用途）。');check(rollExpr(args.expr,args.advantage));const d=await readDice();if(d.pending.length>=20)throw Error('待投队列已满，请先处理现有请求。');if(args.requestKey){const hit=[...d.pending,...d.done].find(r=>r.requestKey===args.requestKey);if(hit)return {ok:true,id:hit.id,duplicate:true,request:hit}}
  const req={id:'r'+(++d.seq),t:new Date().toISOString(),expr:args.expr,label,actor:args.actor||'',actorId:args.actorId||'',dc:args.dc==null?null:Number(args.dc),advantage:args.advantage||'normal',kind:args.kind||'roll',why:args.why||'',effectIds:args.effectIds||[],requestKey:args.requestKey,entryId:args.entryId};d.pending.push(req);check(await writeDice(d));const s=await state();s.needsResume=true;await save(s);return {ok:true,id:req.id,request:req,saved:true,waiting:true,summary:'等待玩家依次投骰：'+label}};
 reg('dice.request',enqueue);
 const answerDice=async args=>{const d=await readDice(),existing=d.done.find(r=>r.id===args.id);if(existing)return {ok:true,...existing,saved:true,duplicate:true};const req=d.pending[0];if(!req||req.id!==args.id)throw Error('请先完成队首投骰请求。');const r=check(rollExpr(req.expr,req.advantage));const result={...req,...r,success:req.dc==null?null:r.total>=req.dc,t:new Date().toISOString()};d.pending.shift();d.done.push(result);check(await writeDice(d));if(req.kind==='initiative'){const st=await readCombat(),e=st.order.find(e=>e.id===req.entryId);if(e){e.roll=r.dice[0];e.init=r.total;st.order.sort((x,y)=>y.init-x.init);st.turnIndex=0;check(await writeCombat(st))}}const s=await state();if(result.success===false)for(const id of req.effectIds||[])await endEffect(s,id);s.needsResume=true;await save(s);check(await pushLog([{kind:req.kind,actor:req.actor||req.actorId||'玩家',text:req.label,detail:r.detail,total:r.total,expr:req.expr,dice:r.dice}],{round:(await readCombat()).round}));return {ok:true,...result,saved:true,summary:'投骰已记录：'+r.detail}};
 reg('dice.answer',answerDice);
 const cancelDice=async args=>{const d=await readDice();if(d.pending[0]?.id!==args.id)throw Error('只能取消当前请求。');const req=d.pending.shift();d.done.push({...req,cancelled:true,total:null,success:null});check(await writeDice(d));const s=await state();s.needsResume=true;await save(s);return {ok:true,summary:'已取消当前请求，其余请求保留。'}};
 reg('dice.cancel',cancelDice);
 reg('dice.secret',async args=>{if(!args.reason)throw Error('暗骰必须说明原因。');const result=check(rollExpr(args.expr,args.advantage));const rolls=await readJson(path.join(root,'dm-rolls.json'),[]);rolls.push({...result,label:args.label,reason:args.reason,t:new Date().toISOString()});await saveJson(path.join(root,'dm-rolls.json'),rolls);return {...result,secret:true,summary:'DM 暗骰已记录'}});
 const request=async args=>{if(!['move','target','area'].includes(args.kind))throw Error('需要 move、target 或 area');const u=await unit(args.actorId);if(args.kind==='move'&&!u.st.active)throw Error('自由移动模式不需要 DM 移动请求；进入回合制后才能请求移动。');assertTurn(u);if(!u.token)throw Error('请先把已有角色放到当前地图。');if(u.token.kind!=='pc')throw Error('交互请求只用于玩家角色。');const s=await state();if(s.requests.length)throw Error('请先完成上一条地图请求。');const r={...args,id:'q-'+randomUUID(),round:u.st.round,turnId:current(u.st)?.id||null,mapName:u.map.name,mapId:u.map.id,actorId:u.token.id,status:'pending'};s.requests.push(r);s.needsResume=true;await save(s);return {ok:true,request:r,waiting:true,summary:'等待玩家：'+(args.label||args.kind)}};
 reg('interaction.request',request);
 const within=(m,x,y)=>Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&y>=0&&x<m.w&&y<m.h;
 // Shortest reachable path; diagonal corner cutting, solid terrain and occupied cells are disallowed.
 const route=(m,tk,to)=>{const blocked=(x,y)=>!within(m,x,y)||['#','b','c',' '].includes(m.terrain[y]?.[x])||m.tokens.some(t=>t.id!==tk.id&&t.kind!=='effect'&&t.x===x&&t.y===y&&(t.hp==null||t.hp>0));const start={x:tk.x,y:tk.y,cost:0,path:[]},todo=[start],best=new Map();while(todo.length){todo.sort((a,b)=>a.cost-b.cost);const p=todo.shift(),k=p.x+','+p.y;if(best.has(k))continue;best.set(k,p.cost);if(p.x===to.x&&p.y===to.y)return p;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const x=p.x+dx,y=p.y+dy;if(blocked(x,y)||(dx&&dy&&(blocked(p.x+dx,p.y)||blocked(p.x,p.y+dy))))continue;const difficult=['~',',','x','f'].includes(m.terrain[y]?.[x]);todo.push({x,y,cost:p.cost+5*(difficult?2:1),path:[...p.path,{x,y}]})}}return null};
 const move=async(args,approved=false)=>{const u=await unit(args.id);if(!u.token)throw Error('地图没有这个单位。');if(u.token.spell==='mageHand')throw Error('请使用施法者的操控法师之手动作。');if(!within(u.map,Number(args.x),Number(args.y)))throw Error('目的地不在地图内。');if(u.st.active){assertTurn(u);if(!approved&&u.token.kind==='pc')throw Error('战斗移动请先等待 DM 请求，再提交移动位置。');const p=route(u.map,u.token,{x:Number(args.x),y:Number(args.y)});if(!p)throw Error('目的地不可达（墙壁或单位阻挡）。');const budget=Number(u.token.speed)||30,used=Number(u.entry.econ?.move)||0;if(p.cost+used>budget)throw Error('超过本回合剩余移动距离 '+(budget-used)+' 尺。');const r=check(await original['map.token.move'](args));u.entry.econ={...u.entry.econ,move:used+p.cost};check(await writeCombat(u.st));return {...r,path:p.path,feet:p.cost,remaining:budget-used-p.cost}}
 return check(await original['map.token.move'](args))};
 reg('map.token.move',args=>move(args));
 for(const name of ['map.set','map.create','map.compose','map.use','map.batch'])reg(name,async args=>{if((await readCombat()).active)throw Error('战斗中不能重置/批改地图；移动用 map.token.move，伤害用 combat.damage。');return original[name](args)},false);
 reg('map.token.update',async args=>{if((await readCombat()).active&&['x','y','hp','max','kind'].some(k=>args.patch?.[k]!=null))throw Error('战斗中请使用移动请求或 combat.damage，不能直接覆盖坐标和生命值。');return original['map.token.update'](args)});
 const startCombat=async args=>{if((await readCombat()).active)throw Error('战斗已经开始，不可重置先攻。');const r=check(await original['combat.start'](args));await hydrate();const ready=await state();ready.needsResume=true;await save(ready);if(!args.entries){const st=await readCombat();for(const e of st.order)if(e.pcId){const u=await unit(e.pcId);await enqueue({expr:'1d20'+(e.dex>=0?'+':'')+e.dex,actor:e.name,actorId:u.id,label:'先攻 · '+e.name,kind:'initiative',entryId:e.id})}}return r};
 reg('combat.start',startCombat);
 reg('combat.mode',async args=>{if(!['turn','free'].includes(args.mode))throw Error('模式必须为 turn 或 free。');const st=await readCombat();if(args.mode==='turn'){if(st.active)return {ok:true,...combatView(st)};if(st.suspended&&st.order.length&&st.suspendedMapId===(await readMap()).id){st.active=true;st.suspended=false;check(await writeCombat(st));return {ok:true,...combatView(st),summary:'已恢复回合制，保持原有先攻与轮次。'}}return startCombat({})}const s=await state();s.completed.push(...s.requests.map(r=>({...r,status:'cancelled'})));s.requests=[];const d=await readDice();d.done.push(...d.pending.filter(r=>r.kind==='initiative').map(r=>({...r,cancelled:true})));d.pending=d.pending.filter(r=>r.kind!=='initiative');check(await writeDice(d));s.needsResume=false;await save(s);st.suspended=st.active||st.suspended;st.suspendedMapId=(await readMap()).id;st.active=false;check(await writeCombat(st));return {ok:true,...combatView(st),summary:'自由移动已开启。当前记录保留，目标尚未自动结算。'}});

 reg('map.token.remove',async args=>{const st=await readCombat(),now=current(st);const r=check(await original['map.token.remove'](args));if(st.active){st.order=st.order.filter(e=>e.tokenId!==args.id);st.turnIndex=Math.max(0,st.order.findIndex(e=>e.id===now?.id));if(!st.order.length)st.active=false;check(await writeCombat(st))}return r});
 reg('map.token.add',async args=>{const r=check(await original['map.token.add'](args));const map=await readMap(),token=map.tokens.find(t=>t.id===(args.token?.id||args.id||r.id));if(token?.kind==='enemy'&&(token.ac==null||token.hp==null)){const sb=await original['mod.statblock'](token.statblockId?{id:token.statblockId,title:token.name}:{query:token.name.replace(/[\d０-９]+$/,'').trim()});if(sb.ok){Object.assign(token,{ac:sb.ac,hp:token.hp??sb.hp,max:token.max??sb.hp,dex:sb.mods?.dex,saves:sb.saves||sb.mods,statblockId:sb.id,source:sb.book+' / '+sb.title});check(await writeMap(map))}}const st=await readCombat();if(st.active&&token&&token.kind!=='effect'&&!st.order.some(e=>e.tokenId===token.id)){const active=current(st)?.id,roll=check(rollExpr('1d20'));st.order.push({id:'t-'+token.id,tokenId:token.id,kind:token.kind,name:token.name,hp:token.hp,max:token.max,init:roll.total+(Number(token.dex)||0),roll:roll.total,dex:token.dex,conditions:[],econ:{}});st.order.sort((x,y)=>y.init-x.init);st.turnIndex=Math.max(0,st.order.findIndex(e=>e.id===active));check(await writeCombat(st))}return {...r,token}});

 const preview=async args=>{const s=await state(),r=s.requests[0];if(!r||r.id!==args.id)throw Error('地图请求已失效。');const u=await unit(r.actorId);assertTurn(u);if(r.mapId&&r.mapId!==u.map.id)throw Error('地图已切换，请取消并重新发起请求。');if(u.st.active&&(r.turnId!==current(u.st)?.id||r.round!==u.st.round))throw Error('回合已经变化，请重新发起请求。');if(r.kind==='move'){const p=route(u.map,u.token,args);if(!p)throw Error('不可到达。');return {ok:true,path:p.path,feet:p.cost}}
 if(r.kind==='target'){const ids=[...new Set(args.targetIds||[])];if(!ids.length||ids.length>(r.count||1))throw Error('选择目标数量不正确。');const targets=ids.map(id=>u.map.tokens.find(t=>t.id===id));if(targets.some(t=>!t))throw Error('目标不存在。');for(const t of targets){if(r.targetKind&&r.targetKind!=='any'&&t.kind!==r.targetKind)throw Error('目标类型不符。');if(r.range!=null&&Math.max(Math.abs(t.x-u.token.x),Math.abs(t.y-u.token.y))*5>r.range)throw Error('目标超出施法距离。')}
 return {ok:true,targets:await Promise.all(targets.map(async t=>({id:t.id,name:t.name,x:t.x,y:t.y,ac:t.ac,hp:t.hp,los:await original['map.los']({from:{x:u.token.x,y:u.token.y},to:{x:t.x,y:t.y}})})))}}
 if(!within(u.map,Number(args.x),Number(args.y)))throw Error('范围原点不在地图内。');if(r.range!=null&&Math.max(Math.abs(args.x-u.token.x),Math.abs(args.y-u.token.y))*5>r.range)throw Error('范围原点超出施法距离。');const area=check(await original['map.area']({shape:r.shape||'sphere',size:r.size||5,from:{x:args.x,y:args.y},dir:args.dir||r.dir||'n'}));return {...area,origin:{x:args.x,y:args.y}}};
 reg('interaction.preview',preview,false);
 const answerInteraction=async args=>{const s=await state(),req=s.requests[0];if(!req||req.id!==args.id)throw Error('请求不存在或已经提交。');const result=await preview(args);if(req.kind==='move')Object.assign(result,await move({id:req.actorId,x:args.x,y:args.y},true));s.requests.shift();s.completed.push({...req,status:'complete',result,t:new Date().toISOString()});s.completed=s.completed.slice(-40);s.needsResume=true;await save(s);return {ok:true,result,summary:'已提交给 DM，请等待分析。'}};
 reg('interaction.answer',answerInteraction);
 reg('interaction.cancel',async args=>{const s=await state();if(s.requests[0]?.id!==args.id)throw Error('请求不存在。');s.completed.push({...s.requests.shift(),status:'cancelled'});s.needsResume=true;await save(s);return {ok:true}});
 reg('effect.add',async args=>{for(const key of ['temp','maxHpBonus','acBonus'])if(args[key]!=null&&(!Number.isFinite(args[key])||args[key]<0||args[key]>999))throw Error('生命BUFF数值无效。');if(args.temp!=null&&args.maxHpBonus!=null)throw Error('请分开登记临时生命与生命上限BUFF。');const s=await state(),u=await unit(args.actorId);if(u.pc){const list=await ops['party.spells']({id:u.pc.id});const sp=list.spells?.find(sp=>sp.key===args.spell||sp.name===args.name);if(sp){args={...args,concentration:!!sp.conc};if(args.durationSeconds==null&&args.rounds==null){const m=String(sp.duration).match(/(\d+)\s*(小时|分钟|轮|回合)/);if(m)args.durationSeconds=Number(m[1])*({'小时':3600,'分钟':60,'轮':6,'回合':6}[m[2]])}}}const ids=identity(u);if(args.concentration)for(const e of [...s.effects])if(e.concentration&&ids.includes(e.actorId))await endEffect(s,e.id);const effect={...args,id:'fx-'+randomUUID(),actorId:u.id,createdClock:s.clock,rounds:args.rounds==null?null:Math.max(1,Number(args.rounds)),expiresAt:args.durationSeconds==null?null:s.clock+Math.max(1,Number(args.durationSeconds)),trigger:args.trigger||'start'};if(args.requestId){const selection=s.completed.find(r=>r.id===args.requestId&&r.status==='complete');if(!selection||selection.actorId!==u.id)throw Error('没有该施法者已确认的范围选择。');effect.area=selection.result;effect.mapName=selection.mapName;effect.mapId=selection.mapId}
 if(args.temp!=null){const target=await unit(args.targetId||u.id);effect.targetId=target.id;const previous=Number(target.pc?.hp.temp??target.token?.temp??target.entry?.temp)||0;if(Number(args.temp)<=previous)return {ok:true,kept:true,summary:'临时生命不叠加，保留较高的现有值。'};for(const old of [...s.effects])if(old.temp!=null&&old.targetId===target.id)await endEffect(s,old.id);const fresh=await unit(target.id);if(fresh.pc)fresh.pc.hp.tempEffect=effect.id;await syncHp(fresh,Number(fresh.pc?.hp.current??fresh.token?.hp??fresh.entry?.hp)||0,Math.max(0,Number(args.temp)))}
 if(args.maxHpBonus!=null){const target=await unit(args.targetId||u.id);if(!target.pc)throw Error('生命上限BUFF需要真实角色。');effect.targetId=target.id;for(const old of [...s.effects])if(old.maxHpBonus!=null&&old.targetId===target.id&&(args.spell?old.spell===args.spell:old.name===args.name))await endEffect(s,old.id);const fresh=await unit(target.id);fresh.pc.hp.max+=args.maxHpBonus;await syncHp(fresh,fresh.pc.hp.current+args.maxHpBonus,fresh.pc.hp.temp||0)}
 if(args.acBonus!=null){const target=await unit(args.targetId||u.id);if(!target.pc)throw Error('AC效果需要真实角色卡。');effect.targetId=target.id;for(const old of [...s.effects])if(old.acBonus!=null&&old.targetId===target.id&&(args.spell?old.spell===args.spell:old.name===args.name))await endEffect(s,old.id);const fresh=await unit(target.id);fresh.pc.acBuffs=[...(fresh.pc.acBuffs||[]),{id:effect.id,name:effect.name,bonus:args.acBonus}];check(await persist(fresh.pc))}
 s.effects.push(effect);await save(s);return {ok:true,effect,summary:'持续效果已登记：'+args.name}});
 reg('effect.end',async args=>{const s=await state();await endEffect(s,args.id);await save(s);return {ok:true}});
 const expire=async(s)=>{for(const e of [...s.effects])if(e.expiresAt!=null&&e.expiresAt<=s.clock)await endEffect(s,e.id)};
 reg('session.advance',async args=>{if((await readCombat()).active)throw Error('战斗中请推进回合。');const seconds=Number(args.seconds);if(!Number.isFinite(seconds)||seconds<0)throw Error('seconds 必须非负。');const s=await state();s.clock+=seconds;await expire(s);await save(s);return {ok:true,clock:s.clock,effects:s.effects}});
 const damage=async args=>{const u=await unit(args.id),amount=Number(args.amount);if(!Number.isFinite(amount))throw Error('伤害/治疗必须是数值。');const hp=Number(u.pc?.hp.current??u.token?.hp??u.entry?.hp),max=Number(u.pc?.hp.max??u.token?.max??u.entry?.max)||9999;if(!Number.isFinite(hp))throw Error('尚无可靠生命值，请先绑定规则简表。');const temp=Number(u.pc?.hp.temp??u.token?.temp??u.entry?.temp)||0,absorb=amount<0?Math.min(temp,-amount):0,next=Math.max(0,Math.min(max,hp+amount+absorb));await syncHp(u,next,temp-absorb);const s=await state(),ids=identity(u),concentrating=s.effects.filter(e=>e.concentration&&ids.includes(e.actorId));if(next===0)for(const e of concentrating)await endEffect(s,e.id);if(temp&&temp===absorb)for(const e of [...s.effects])if(e.temp!=null&&ids.includes(e.targetId))await endEffect(s,e.id);await save(s);
 if(amount<0&&next>0&&concentrating.length){const sheet=u.pc?check(await ops['party.sheet']({id:u.pc.id})).sheet:null;const bonus=Number(sheet?.saves?.con??u.token?.saves?.con??0);const dc=Math.max(10,Math.floor(-amount/2));if(u.pc)await enqueue({expr:'1d20'+(bonus>=0?'+':'')+bonus,label:'专注豁免 · '+concentrating.map(e=>e.name).join('、'),actor:u.name,actorId:u.id,dc,kind:'concentration',effectIds:concentrating.map(e=>e.id)});else{const r=check(rollExpr('1d20'+(bonus>=0?'+':'')+bonus));if(r.total<dc){const latest=await state();for(const e of concentrating)await endEffect(latest,e.id);await save(latest)}}}
 check(await pushLog([{kind:amount<0?'damage':'heal',actor:u.name,text:args.log||'生命值结算',detail:`${amount}，临时 HP 吸收 ${absorb} → HP ${next}/${max}，临时 ${temp-absorb}`}],{round:u.st.round}));return {...combatView(await readCombat()),hp:next,temp:temp-absorb,absorbed:absorb,saved:true,summary:u.name+' HP '+next+'/'+max+' · 临时 '+(temp-absorb)}};
 reg('combat.damage',damage);
 reg('pc.apply',async args=>{let r;if(args.hp!=null){r=await damage({id:args.id,amount:args.hp,log:args.log});args={...args};delete args.hp}const rest=check(await original['pc.apply'](args));{const u=await unit(args.id);await syncHp(u,u.pc.hp.current,u.pc.hp.temp);const stateNow=await state();if(u.pc.conditions?.some(c=>['incapacitated','unconscious','stunned','paralyzed','petrified'].includes(c.key)))for(const e of [...stateNow.effects])if(e.concentration&&identity(u).includes(e.actorId))await endEffect(stateNow,e.id);await save(stateNow)}return r?{...rest,damage:r}:rest});
 reg('combat.conditions',async args=>{args={...args,add:(args.add||[]).map(c=>surpriseCondition(c)?{...(typeof c==='string'?{}:c),key:'surprised',name:'措手不及',rounds:null}:c)};const r=check(await original['combat.conditions'](args));const u=await unit(args.id),s=await state();if(u.entry?.conditions?.some(c=>['incapacitated','unconscious','stunned','paralyzed','petrified'].includes(c.key)))for(const e of [...s.effects])if(e.concentration&&identity(u).includes(e.actorId))await endEffect(s,e.id);await save(s);return r});
 const nextTurn=async args=>{const s=await state(),d=await readDice();if(s.requests.length||d.pending.length)throw Error('还有玩家请求未完成，不能跳过回合。');const before=await readCombat();const leaving=current(before);if(leaving){leaving.firstTurnEnded=true;leaving.conditions=(leaving.conditions||[]).filter(c=>!surpriseCondition(c));if(leaving.pcId){const pc=await readPc(leaving.pcId);pc.conditions=(pc.conditions||[]).filter(c=>!surpriseCondition(c));check(await persist(pc))}check(await writeCombat(before))}const r=check(await original['combat.next']({...args,steps:1}));const after=await readCombat(),entering=current(after);for(const e of [...s.effects]){const who=e.trigger==='end'?leaving:entering;if(e.rounds!=null&&[who?.id,who?.tokenId,who?.pcId].includes(e.actorId)){e.rounds--;if(e.rounds<=0)await endEffect(s,e.id)}}if(after.round>before.round)s.clock+=6;await expire(s);await save(s);await writeLog({...await readLog(),round:after.round});return {...r,effects:s.effects}};
 reg('combat.next',nextTurn);
 reg('combat.end',async args=>{const st=await readCombat();if(!st.active&&!st.suspended)return {ok:true,...combatView(st),summary:'战斗已经结束。'};const s=await state(),dice=await readDice();if(s.requests.length||dice.pending.length)throw Error('请先完成或取消剩余玩家请求。');const id=new Date().toISOString().replace(/[:.]/g,'-')+'-'+randomUUID().slice(0,8),log=await readLog(),map=await readMap(),chat=await readAi();await saveJson(path.join(root,'battles',id+'.json'),{id,title:args.title||map.name||'战斗回顾',t:new Date().toISOString(),combat:st,map,log,messages:chat.messages});check(await original['combat.end'](args));const ended=await readCombat();ended.suspended=false;check(await writeCombat(ended));check(await writeLog({campaign:log.campaign,round:0,seq:0,entries:[]}));const battle=await readJson(path.join(root,'battle.json'),null);if(battle){battle.events=[];await saveJson(path.join(root,'battle.json'),battle)}check(await writeDice({...dice,pending:[],done:[]}));return {ok:true,...combatView(await readCombat()),archiveId:id,summary:'战斗已归档，当前记录已清空。'}});
 reg('session.save',async()=>{await checkpoint();return {ok:true,summary:'当前战役已保存到 EXE 同级 saves。'}});
 reg('session.restore',async()=>{const snapshot=await readJson(path.join(root,'current.json'),null);if(!snapshot||snapshot.schema!==1)throw Error('没有可继续的战役存档。');if((await readCombat()).active)throw Error('战斗进行中不能覆盖当前状态。');for(const pc of snapshot.characters)check(await persist(pc));check(await writeMap(snapshot.map));check(await writeCombat(snapshot.combat));check(await writeDice(snapshot.dice));await save(snapshot.session);await saveJson(path.join(root,'battle.json'),snapshot.battle||{schema:1,seq:0,active:null,receipts:{},events:[],projection:null});return {ok:true,summary:'上次战役状态已恢复。'}});
 reg('archive.list',async()=>{const dir=path.join(root,'battles');let files=[];try{files=await fs.readdir(dir)}catch(e){if(e.code!=='ENOENT')throw e}const items=[];for(const f of files.filter(f=>/^[A-Za-z0-9-]+\.json$/.test(f))){const b=await readJson(path.join(dir,f),null);if(b)items.push({id:b.id,title:b.title,t:b.t,rounds:b.combat.round,count:b.log.entries.length})}return {ok:true,items:items.sort((a,b)=>b.t.localeCompare(a.t))}},false);
 reg('archive.read',async args=>{if(!/^[A-Za-z0-9-]+$/.test(args.id))throw Error('存档 ID 无效');return {ok:true,archive:await readJson(path.join(root,'battles',args.id+'.json'),null)}},false);
 reg('narration.say',async args=>{if(!args.speaker||!args.text)throw Error('需要 speaker 和 text');const ai=await readAi();ai.messages.push({role:'assistant',speaker:String(args.speaker).slice(0,60),content:String(args.text),t:new Date().toISOString()});check(await writeAi(ai));return {ok:true,summary:'已显示 '+args.speaker+' 的发言'}});
 reg('session.pending',async()=>{const s=await state(),d=await readDice(),st=await readCombat();return {ok:true,request:s.requests[0]||null,completed:s.completed.slice(-4),effects:s.effects,dice:d.pending,resuming,elapsedMs:resuming?Date.now()-resumeStarted:0,resumeError,retryAt:resumeRetryAt,ready:!resuming&&Date.now()>=resumeRetryAt&&!!s.needsResume&&!s.requests.length&&!d.pending.length,revision:s.revision,combat:combatView(st),clock:s.clock}},false);
 reg('scene.get',async()=>{const map=await readMap(),s=await state(),d=await readDice(),party=await original['party.list']({}),characters=[];for(const p of party.items||[]){const sheet=await ops['party.sheet']({id:p.id});if(sheet.ok)characters.push({id:p.id,name:sheet.sheet.name,hp:sheet.sheet.hp,ac:sheet.sheet.ac,spells:sheet.sheet.spells.map(sp=>({key:sp.key,name:sp.name,level:sp.level,source:sp.source})),slots:sheet.sheet.slots,equipment:sheet.sheet.equipment,inventory:sheet.sheet.inventory,acBreakdown:sheet.sheet.acBreakdown,conditions:sheet.sheet.conditions})}return {ok:true,map,characters,combat:combatView(await readCombat()),requests:s.requests,completed:s.completed.slice(-6),effects:s.effects,dice:d.done.slice(-6),pendingDice:d.pending,clock:s.clock}},false);
 reg('session.resume',async args=>{if(resuming)return {ok:true,status:'processing',summary:'DM 正在处理同一次续接。'};if(Date.now()<resumeRetryAt)return {ok:true,status:'retry_wait',retryAt:resumeRetryAt};resuming=true;resumeStarted=Date.now();try{const s=await state(),d=await readDice();const combat=await readCombat(),entry=current(combat),npcTurn=combat.active&&entry&&!entry.pcId&&entry.kind!=='pc';if((!s.needsResume&&!(args.continueEnemies&&npcTurn))||s.requests.length||d.pending.length)return {ok:true,idle:true};if((await readJson(path.join(root,'battle.json'),{})).active)return {ok:true,idle:true,summary:'本地行动执行中，等待玩家完成。'};const battleStatus=await ops['battle.get']({});if(battleStatus.pause)return ops['battle.advance']({});const completedIds=new Set(s.completed.map(e=>e.id));const r=await ops['ai.chat']({message:'玩家已完成请求或结束回合。根据最新 scene.get 的选择、坐标和骰子结果继续裁定；不要重复已完成请求。',internal:true,resume:true});if(r.ok){const flow=await ops['battle.advance']({});if(flow.status==='waiting_dm')return {...r,status:'waiting_dm',flow};if(!flow.ok){const stalled=await state();stalled.needsResume=false;await save(stalled);return {...r,ok:false,error:flow.error,flow}}const latest=await state();latest.needsResume=latest.completed.some(e=>!completedIds.has(e.id)&&e.kind!=='battle')||!!latest.requests.length||!!(await readDice()).pending.length;await save(latest)}if(!r.ok){resumeError=r.error;resumeRetryAt=Date.now()+30000}else{resumeError='';resumeRetryAt=0}return r}catch(e){resumeError=e.message;resumeRetryAt=Date.now()+30000;return {ok:false,error:e.message}}finally{resuming=false}},false);
 installBattle({ops,reg,root,hydrate,loadSrd,readMap,writeMap,readCombat,writeCombat,readDice,writeDice,readPc,persist,readLog,writeLog,state,save,rollExpr,check,route,baseAnswer:answerDice,baseCancel:cancelDice,baseInteraction:answerInteraction,baseNext:nextTurn,setRecovery:fn=>{recovery=fn}});
 return {state};
}
