const fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
module.exports=async(window,runtime,home,fixture)=>{
 const wc=window.webContents;wc.setBackgroundThrottling(false);
 const run=code=>wc.executeJavaScript(code),delay=ms=>new Promise(r=>setTimeout(r,ms));
 const until=async code=>{for(let i=0;i<160;i++){if(await run(code))return;await delay(100)}throw Error('Battle UI timeout: '+code+' / '+await run(`document.querySelector('.battle-confirm,.battle-message')?.textContent`))};
 const click=async text=>{await run(`(()=>{const el=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===${JSON.stringify(text)});if(!el)throw Error('Missing button '+${JSON.stringify(text)});el.click()})()`);await delay(160)};
 const api=async(op,args={})=>{const r=(await(await fetch(runtime.url+'/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op,args})})).json()).value;assert.equal(r.ok,true,op+': '+r.error);return r};
 const capture=async name=>{await run(`document.getAnimations().forEach(a=>{try{a.finish()}catch{}})`);await wc.capturePage();await delay(300);await fs.writeFile(path.join(home,name+'.png'),(await wc.capturePage()).toPNG())};
 const provider=http.createServer(async(req,res)=>{for await(const p of req){}res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'你掌心的魔力掠过石壁。DM 已读取场景中实际结算的坐标、伤害和资源。'}}]}))});await new Promise(r=>provider.listen(0,'127.0.0.1',r));
 try{
 const pc=JSON.parse(await fs.readFile(fixture,'utf8'));Object.assign(pc,{id:'hero',name:'迷雾法师',race:'human',level:3,classes:[{class:'wizard',level:3}],hp:{current:30,max:30,temp:0},conditions:[],choices:{},abilities:{str:10,dex:14,con:12,int:16,wis:10,cha:10},spellcasting:{ability:'int',cantrips:['acidSplash','fireBolt'],spells:['falseLife','fogCloud']}});
 await fs.writeFile(path.join(home,'campaign/characters/hero.json'),JSON.stringify(pc));await api('settings.set',{baseUrl:'http://127.0.0.1:'+provider.address().port,model:'test-battle'});
 await api('map.create',{name:'旧堡 · 灰岩回廊',w:20,h:15,terrain:Array.from({length:15},(_,y)=>y===0||y===14?'#'.repeat(20):'#'+'.'.repeat(18)+'#'),tokens:[{id:'hero',name:pc.name,kind:'pc',x:4,y:6,hp:30,max:30,ac:12,speed:30},{id:'g1',name:'地精哨兵',kind:'enemy',x:5,y:6,hp:50,max:50,ac:15,saves:{dex:-100},attackBonus:4,damage:'1d6+2',reach:5,speed:30},{id:'g2',name:'地精弓手',kind:'enemy',x:6,y:6,hp:50,max:50,ac:15,saves:{dex:-100}}]});
 await api('combat.start',{entries:[{id:'p',pcId:'hero',tokenId:'hero',kind:'pc',name:pc.name,hp:30,max:30,init:20},{id:'e',tokenId:'g1',kind:'enemy',name:'地精哨兵',hp:50,max:50,init:10}]});
 for(const id of ['g1','g2'])await api('map.token.update',{id,patch:{saves:{dex:-100}}});
 await click('战斗专页');await until(`document.querySelectorAll('.battle-token').length===3`);
 await click('确认 / 调整剩余法术位');await until(`!!document.querySelector('.roll-request-modal')`);await click('确认余额');await until(`!document.querySelector('.roll-request-modal')`);
 await run(`[...document.querySelectorAll('.battle-actionbar button')].find(e=>e.textContent.includes('虚假生命')).click()`);await until(`!!document.querySelector('.battle-confirm button:first-of-type:not(:disabled)')`);await click('确认执行');await until(`document.querySelector('.battle-dice')?.textContent.includes('效果')`);await click('投掷并继续');await until(`Number(document.querySelector('.battle-temp b').textContent)>=5`);
 await click('结束我的回合');await until(`document.querySelector('.battle-initiative .on')?.textContent.includes('地精')`);assert.ok(await run(`document.querySelector('.battle-character').textContent.includes('迷雾法师')`));assert.ok(await run(`document.querySelector('.battle-character').textContent.includes('AC 12')`));await api('battle.endTurn');await until(`document.querySelector('.battle-initiative .on')?.textContent.includes('迷雾法师')`);
 await run(`[...document.querySelectorAll('.battle-actionbar button')].find(e=>e.textContent.includes('酸液飞溅')).click()`);for(const id of ['g1','g2'])await run(`document.querySelector('[aria-label$=" · ${id}"]').dispatchEvent(new MouseEvent('click',{bubbles:true}))`);await until(`document.querySelectorAll('.battle-token.selected').length===2`);await until(`!!document.querySelector('.battle-confirm button:first-of-type:not(:disabled)')`);await click('确认执行');await until(`document.querySelector('.battle-dice')?.textContent.includes('伤害')`);await click('投掷并继续');await until(`!document.querySelector('.battle-dice')`);let map=await api('map.get');assert.equal(map.tokens[1].hp,map.tokens[2].hp);assert.ok(map.tokens[1].hp<50);
 await api('battle.endTurn');await api('battle.endTurn');await delay(400);await run(`[...document.querySelectorAll('.battle-actionbar button')].find(e=>e.textContent.includes('云雾术')).click()`);await run(`document.querySelector('rect.ink-cell[x="320"][y="256"]').dispatchEvent(new MouseEvent('click',{bubbles:true}))`);await until(`document.querySelectorAll('.battle-range').length>10`);await capture('battle-area-preview');await click('取消选择');
 await run(`document.querySelector('[aria-label$=" · g1"]').dispatchEvent(new MouseEvent('mouseover',{bubbles:true}))`);await until(`document.querySelector('.battle-hover')?.textContent.includes('AC 15')`);await capture('battle-desktop');await run(`document.querySelector('[aria-label$=" · g1"]').dispatchEvent(new MouseEvent('mouseout',{bubbles:true}))`);
 await run(`document.querySelector('.battle-character header button').click()`);await until(`!!document.querySelector('.solo-card-page')`);assert.ok(await run(`document.querySelector('.solo-card-page').textContent.includes('临时生命')`));await run(`document.querySelector('.solo-card-page .card-expand').click()`);await until(`!!document.querySelector('.solo-detail-page article')`);await capture('battle-card-page');await run(`document.querySelectorAll('.solo-tab-close')[1].click()`);await click('战斗专页');await until(`!!document.querySelector('.battle-map-scroll')`);
 await api('interaction.request',{kind:'target',actorId:'hero',label:'兼容目标请求',count:1,range:60});await until(`document.querySelector('.battle-confirm')?.textContent.includes('兼容目标请求')`);await run(`document.querySelector('[aria-label$=" · g1"]').dispatchEvent(new MouseEvent('click',{bubbles:true}))`);await until(`!!document.querySelector('.battle-confirm button:first-of-type:not(:disabled)')`);await click('确认执行');await until(`!document.querySelector('.battle-confirm')`);assert.equal((await api('session.pending')).request,null);
 await click('切换自由移动');await until(`document.querySelector('.battle-mode')?.textContent==='自由探索'`);await run(`document.querySelector('rect.ink-cell[x="128"][y="160"]').dispatchEvent(new MouseEvent('click',{bubbles:true}))`);await delay(600);map=await api('map.get');assert.equal(map.tokens.find(t=>t.id==='hero').y,5);
 window.setSize(1000,760);await delay(350);assert.ok(await run(`document.documentElement.scrollWidth<=window.innerWidth+2`));await capture('battle-small');window.setSize(1440,960);
 await fs.writeFile(path.join(home,'battle-smoke.json'),JSON.stringify({temporaryHp:true,sharedAreaDamage:true,areaPreview:true,clearAC:true,cardTabs:true,freeMovement:true,npcTurnKeepsPlayerCard:true},null,2));
 }finally{await new Promise(r=>provider.close(r))}
};
