const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
module.exports=async(window,runtime,home)=>{
 const wc=window.webContents;wc.setBackgroundThrottling(false);const run=async code=>{try{return await wc.executeJavaScript(code)}catch(e){await fs.writeFile(path.join(home,'lobby-failure.png'),(await wc.capturePage()).toPNG());throw Error(code.slice(0,350)+': '+e.message)}},delay=ms=>new Promise(r=>setTimeout(r,ms));
 const until=async code=>{for(let i=0;i<150;i++){if(await run(code))return;await delay(100)}await fs.writeFile(path.join(home,'lobby-failure.png'),(await wc.capturePage()).toPNG());throw Error('Lobby UI timeout: '+code)};
 const click=async text=>{await run(`(()=>{const e=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===${JSON.stringify(text)});if(!e)throw Error('Missing '+${JSON.stringify(text)});e.click()})()`);await delay(200)};
 const set=async(selector,value)=>run(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el)throw Error('Missing input');const proto=el.tagName==='SELECT'?HTMLSelectElement.prototype:el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))})()`);
 const api=async(op,args={})=>{const r=(await(await fetch(runtime.url+'/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op,args})})).json()).value;assert.equal(r.ok,true,r.error);return r};
 await until(`!!document.querySelector('.home-page')`);await fs.writeFile(path.join(home,'lobby-home.png'),(await wc.capturePage()).toPNG());
 await fetch(runtime.url+'/api/modules?filename=Lobby.md',{method:'POST',body:'# 回廊测试\n守卫站在庭院的入口处。'});await click('新建战役');await click('刷新模组列表');const moduleId=(await api('campaign.get')).modules[0].id;
 await set('.home-create input:not([type=checkbox])','人工主持测试');await set('.home-create select',moduleId);await click('创建战役并新建角色');await until(`!!document.querySelector('.home-create .dndp-input')&&document.body.textContent.includes('角色名')`);
 const profile=(await api('profiles.list')).active;assert.notEqual(profile,'legacy');assert.equal((await api('party.list')).items.length,0);
 // Existing character wizard is rendered in the new isolated profile. Seed a
 // synthetic character to exercise DM forms without selecting every build option.
 const pc={schema:'dnd5e.character.v1',id:'lobby-hero',name:'控制台测试角色',level:1,race:'human',classes:[{class:'fighter',level:1}],abilities:{str:15,dex:12,con:14,int:10,wis:10,cha:10},hp:{current:12,max:12,temp:0},inventory:[],equipment:{},conditions:[]};
 await fs.writeFile(path.join(home,'campaign','profiles',profile,'characters','lobby-hero.json'),JSON.stringify(pc));await click('取消');await click('以 DM 进入');await until(`!!document.querySelector('.dm-console form')`);assert.equal((await api('controls.get')).aidm,false);
 const p=await api('session.resume',{continueEnemies:true});assert.equal(p.status,'manual_dm');
 await set('.dm-console .dm-grid article>select','dice.request');await until(`document.querySelector('.dm-console form')?.textContent.includes('骰子表达式')`);
 await run(`(()=>{const form=document.querySelector('.dm-console form');for(const [label,value] of [['骰子表达式','1d20+2'],['检定名称','DM可视化检定']]){const el=[...form.querySelectorAll('label')].find(l=>l.textContent.includes(label))?.querySelector('input');if(!el)throw Error(label);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}))}})()`);
 await run(`(()=>{const select=[...document.querySelectorAll('.dm-console form label')].find(l=>l.textContent.includes('角色 / 单位'))?.querySelector('select');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(select,'lobby-hero');select.dispatchEvent(new Event('change',{bubbles:true}))})()`);await click('确认执行');await until(`document.querySelector('.dm-result')?.textContent.includes('操作成功')`);assert.equal((await api('dice.pending')).pending[0].expr,'1d20+2');
 await delay(400);await wc.capturePage();await delay(200);await fs.writeFile(path.join(home,'lobby-dm.png'),(await wc.capturePage()).toPNG());
 await click('主界面');await until(`document.querySelectorAll('.save-card').length===2`);await run(`[...document.querySelectorAll('.save-card')].find(e=>e.textContent.includes('原有战役')).querySelector('button').click()`);await until(`!!document.querySelector('.dndp-ws')`);assert.equal((await api('profiles.list')).active,'legacy');assert.equal((await api('dice.pending')).pending.length,0);
 await fs.writeFile(path.join(home,'lobby-smoke.json'),JSON.stringify({startupHome:true,newProfileWizard:true,manualDM:true,visualDice:true,switchIsolation:true}));
};
