const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
module.exports = async function uiSmoke(window, runtime, home) {
  const wc = window.webContents;
  wc.setBackgroundThrottling(false);
  const evaluate = async code => { try { return await wc.executeJavaScript(code); } catch (error) { throw new Error(code.slice(0, 240) + ': ' + error.message); } };
  const delay = ms => new Promise(r => setTimeout(r, ms));
  const click = async label => { await evaluate(`(() => { const el = [...document.querySelectorAll('button')].find(b => b.textContent.trim() === ${JSON.stringify(label)}); if (!el) throw Error('Missing button: ' + ${JSON.stringify(label)}); el.click(); })()`); await delay(150); };
  const until = async code => { for (let i = 0; i < 50; i++) { if (await evaluate(code)) return; await delay(100); } throw Error('UI condition timed out: ' + code); };
  const capture = async name => { await evaluate(`document.getAnimations().forEach(a => { try { a.finish(); } catch {} })`); await wc.capturePage(); await delay(250); await fs.writeFile(path.join(home, name + '.png'), (await wc.capturePage()).toPNG()); };
  await click('外观');
  await until(`!!document.querySelector('.appearance-presets')`);
  await click('翡翠');
  assert.equal(await evaluate(`document.documentElement.style.getPropertyValue('--solo-accent')`), '#4fbf8b');
  await evaluate(`(() => { const input = document.querySelector('input[type=color][aria-label="强调色"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, '#3eac91'); input.dispatchEvent(new Event('input', {bubbles:true})); input.dispatchEvent(new Event('change', {bubbles:true})); })()`);
  await delay(100);
  assert.equal(await evaluate(`document.documentElement.style.getPropertyValue('--solo-accent')`), '#3eac91');
  const colors = { '背景色': '#25334a', '面板色': '#2b3d56', '正文颜色': '#f7deb1', '辅助文字颜色': '#bdc9de', '按钮文字颜色': '#1b2638', '强调色': '#87d9c4' };
  for (const [label, color] of Object.entries(colors)) {
    await evaluate(`(() => { const input = document.querySelector('[aria-label="' + ${JSON.stringify(label + ' Hex')} + '"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, ${JSON.stringify(color)}); input.dispatchEvent(new Event('input', {bubbles:true})); })()`);
    await delay(90);
  }
  await until(`document.querySelector('.appearance-status').textContent.includes('已保存')`);
  const saved = JSON.parse(await fs.readFile(path.join(home, 'campaign/data/theme.json'), 'utf8'));
  assert.equal(saved.background, '#25334a'); assert.equal(saved.text, '#f7deb1'); assert.equal(saved.onAccent, '#1b2638'); assert.equal(saved.accent, '#87d9c4');
  await click('模组库 / 上传');
  await capture('custom-theme');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.module-library')).color`), 'rgb(247, 222, 177)');
  await click('跑团工作区');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.dndp-ws')).color`), 'rgb(247, 222, 177)');
  await click('外观'); await click('减少动效'); await until(`document.documentElement.dataset.motion === 'reduced'`);
  await click('跑团工作区');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.dndp-panel')).animationName`), 'none');
  await click('外观'); await click('恢复默认外观'); await click('晨光 · 浅色');
  await until(`document.querySelector('.appearance-status').textContent.includes('已保存')`);
  await capture('appearance-light');
  await wc.reload(); await until(`!!document.querySelector('.dndp-ws')`); await delay(500);
  assert.equal(await evaluate(`document.documentElement.style.getPropertyValue('--solo-bg')`), '#eef2f8');
  await click('外观'); await click('深空 · 深色'); await capture('appearance-dark');
  await click('跑团工作区'); await delay(800);
  const contrast=await evaluate(`Array.from(document.querySelectorAll('.dndp-panel,.dndp-ptitle,.dndp-note')).slice(0,12).map(e=>({class:e.className,color:getComputedStyle(e).color,opacity:getComputedStyle(e).opacity,animation:getComputedStyle(e).animationName}))`);
  await fs.writeFile(path.join(home,'contrast.json'),JSON.stringify(contrast,null,2));
  assert.ok(contrast.filter(c=>c.class==='dndp-panel').every(c=>Number(c.opacity)>.95),'Panels must remain visible during animations');
  await capture('workspace-dark');
  const api=async(op,args={})=>(await(await fetch(runtime.url+'/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op,args})})).json()).value;
  await api('map.compose',{name:'检索与浮层验证',biome:'cave'});
  const sb=await api('mod.statblock',{query:'地精'});assert.equal(sb.ok,true);
  await api('map.token.add',{token:{id:'hover-enemy',name:'地精',kind:'enemy',x:5,y:5}});
  const bound=await api('enemy.bind',{tokenId:'hover-enemy',statblockId:sb.id});assert.equal(bound.ok,true);
  await until(`!!document.querySelector('.dndp-tok')`);
  await evaluate(`document.querySelector('.dndp-tok').dispatchEvent(new MouseEvent('mouseover',{bubbles:true,clientX:600,clientY:300}))`);await delay(200);
  const enemyTip=await evaluate(`document.querySelector('#solo-detail-tip').textContent`);assert.ok(enemyTip.includes('AC / HP'));assert.ok(enemyTip.includes('来源'));assert.ok(enemyTip.includes(String(bound.token.ac)));await capture('enemy-tooltip');
  await api('map.token.remove',{id:'hover-enemy'});
  await evaluate(`(() => { const b = [...document.querySelectorAll('button')].find(b => b.textContent.includes('新建角色')); if (!b) throw Error('No character creation'); b.click(); })()`);
  await until(`!!document.querySelector('.dndp-cardwrap button')`);
  await evaluate(`(() => { const button = document.querySelector('.dndp-cardwrap button'); button.focus(); button.dispatchEvent(new MouseEvent('mouseover', {bubbles:true,clientX:50,clientY:80})); })()`); await delay(250);
  const tip = await evaluate(`(() => { const e = document.querySelector('.dndp-tipf'); const s=getComputedStyle(e), r=e.getBoundingClientRect(); return { background:s.backgroundColor,color:s.color,font:s.fontSize,events:s.pointerEvents,visible:s.display,inside:r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight }; })()`);
  assert.notEqual(tip.background, 'rgba(0, 0, 0, 0)'); assert.notEqual(tip.background, tip.color); assert.equal(tip.events, 'auto'); assert.equal(tip.inside, true); assert.ok(parseFloat(tip.font)>=14);
  await capture('tooltip');
  await fs.writeFile(path.join(home, 'ui-smoke.json'), JSON.stringify({ saved, tip, preset:true, persistence:true, reducedMotion:true, crossTab:true }, null, 2));
};
