import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';
import {startServer} from '../server.mjs';import {initializeData} from '../desktop/storage.mjs';import {explicitRolls,assemblePrompt} from '../src/ai-prompts.mjs';
async function fixture(npcFirst=false){const home=await fs.mkdtemp(path.join(os.tmpdir(),'solo-battle-')),root=await initializeData(home,'0.9.0');const pc=JSON.parse(await fs.readFile(new URL('../characters/pc-turiel-mistveil.json',import.meta.url),'utf8'));Object.assign(pc,{id:'hero',name:'测试法师',race:'human',level:3,classes:[{class:'wizard',level:3}],abilities:{str:10,dex:14,con:12,int:16,wis:10,cha:10},hp:{current:50,max:50,temp:0},conditions:[],choices:{},equipment:{mainHand:{key:'dagger',name:'匕首',damage:'1d4',props:['finesse']}},spellcasting:{ability:'int',cantrips:['acidSplash','fireBolt'],spells:['falseLife','fogCloud','magicMissile','burningHands']}});await fs.writeFile(path.join(root,'characters/hero.json'),JSON.stringify(pc));let app=await startServer({dataRoot:root,port:0});const api=async(op,args={})=>{const res=await(await fetch(app.url+'/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op,args})})).json();assert.equal(res.ok,true,res.error);return res.value};const ok=async(op,args={})=>{const r=await api(op,args);assert.equal(r.ok,true,op+': '+r.error);return r};await ok('map.create',{name:'测试',w:12,h:12,terrain:Array(12).fill('.'.repeat(12)),tokens:[{id:'hero',name:pc.name,kind:'pc',x:2,y:2,hp:50,max:50,ac:12,speed:30},{id:'g1',name:'地精',kind:'enemy',x:3,y:2,hp:50,max:50,ac:15,saves:{dex:-100},attackBonus:4,damage:'1d6+2',reach:5,speed:30},{id:'g2',name:'地精',kind:'enemy',x:4,y:2,hp:50,max:50,ac:15,saves:{dex:-100},attackBonus:4,damage:'1d6+2',reach:5}]});await ok('combat.start',{entries:[{id:'p',pcId:'hero',tokenId:'hero',kind:'pc',name:pc.name,hp:50,max:50,init:npcFirst?10:20},{id:'e',tokenId:'g1',kind:'enemy',name:'地精',hp:50,max:50,init:npcFirst?20:10}]});await ok('map.token.update',{id:'g1',patch:{saves:{dex:-100}}});await ok('map.token.update',{id:'g2',patch:{saves:{dex:-100}}});return {home,root,api,ok,restart:async()=>{await app.close();app=await startServer({dataRoot:root,port:0})},close:async()=>{await app.close();await fs.rm(home,{recursive:true,force:true})}};}
async function perform(f,args,id){const p=await f.ok('battle.preview',args);return f.ok('battle.submit',{...args,version:p.version,actionId:id})}

test('attack previews reject range and stale versions without spending; manual hit then damage resumes after restart',async()=>{const f=await fixture();try{assert.equal((await f.api('battle.preview',{actorId:'hero',abilityId:'weapon',targetIds:['g2']})).ok,false);const args={actorId:'hero',abilityId:'weapon',targetIds:['g1']},p=await f.ok('battle.preview',args);assert.equal((await f.api('battle.submit',{...args,version:'stale',actionId:'bad'})).ok,false);assert.equal((await f.ok('combat.get')).order[0].econ.action,undefined);await f.ok('battle.submit',{...args,version:p.version,actionId:'attack-one'});let d=(await f.ok('dice.pending')).pending[0];assert.match(d.label,/命中/);assert.equal((await f.api('dice.cancel',{id:d.id})).ok,false);await f.restart();const [a,b]=await Promise.all([f.ok('dice.answer',{id:d.id}),f.ok('dice.answer',{id:d.id})]);assert.equal(a.total,b.total);assert.equal(a.dropped.length,0);d=(await f.ok('dice.pending')).pending[0];if(d){assert.match(d.label,/伤害/);await f.ok('dice.answer',{id:d.id})}const state=await f.ok('battle.get');assert.equal(state.active,null);const hp=(await f.ok('map.get')).tokens.find(t=>t.id==='g1').hp;assert.ok(hp<=50);assert.equal((await f.ok('battle.submit',{...args,version:p.version,actionId:'attack-one'})).duplicate,true);assert.equal((await f.ok('map.get')).tokens.find(t=>t.id==='g1').hp,hp);}finally{await f.close()}});

test('spells require actual slot balances; temporary HP and selected spell effects commit exactly once',async()=>{const f=await fixture();try{const args={actorId:'hero',abilityId:'falseLife',targetIds:['hero']};assert.match((await f.api('battle.preview',args)).error,/剩余法术位/);await f.ok('battle.resources',{actorId:'hero',slots:{1:2,2:1}});await perform(f,args,'false-life');const d=(await f.ok('dice.pending')).pending[0];await f.ok('dice.answer',{id:d.id});const sheet=(await f.ok('party.sheet',{id:'hero'})).sheet;assert.ok(sheet.hp.temp>=5&&sheet.hp.temp<=8);assert.equal((await f.ok('battle.get')).slots.find(s=>s.lv===1).remaining,1);await f.ok('combat.damage',{id:'hero',amount:-3});assert.equal((await f.ok('party.sheet',{id:'hero'})).sheet.hp.cur,50);await f.ok('battle.endTurn');await f.ok('battle.endTurn');const q=await f.ok('battle.begin',{actorId:'hero',abilityId:'fogCloud'});await f.ok('interaction.answer',{id:q.request.id,x:7,y:7});assert.ok((await f.ok('session.pending')).effects.some(e=>e.spell==='fogCloud'&&e.area.cells.length));assert.equal((await f.ok('battle.get')).slots.find(s=>s.lv===1).remaining,0);}finally{await f.close()}});

test('area/save damage is shared across targets and resolves locally; player opportunity reaction pauses NPC movement',async()=>{const f=await fixture();try{await perform(f,{actorId:'hero',abilityId:'acidSplash',targetIds:['g1','g2']},'acid');let d=(await f.ok('dice.pending')).pending[0];assert.match(d.label,/伤害/);await f.ok('dice.answer',{id:d.id});const map=await f.ok('map.get');assert.equal(map.tokens.find(t=>t.id==='g1').hp,map.tokens.find(t=>t.id==='g2').hp);assert.equal((await f.ok('battle.get')).active,null);}finally{await f.close()}const g=await fixture(true);try{await perform(g,{actorId:'g1',abilityId:'move',x:3,y:4},'move-npc');const state=await g.ok('battle.get');assert.ok(state.active.reaction);assert.equal(state.active.reaction.actorId,'hero');await g.restart();await g.ok('battle.reaction',{actionId:'move-npc',accept:false});assert.equal((await g.ok('battle.get')).active,null);assert.equal((await g.ok('map.get')).tokens.find(t=>t.id==='g1').y,4);}finally{await g.close()}});

test('explicit conditional DC prose creates a real dice request without a second LLM call',async()=>{assert.equal(explicitRolls('**请掷 1d20+3，DC 15**（手动，报数字）。\n≥15守卫信了。',[{id:'hero'}])[0].dc,15);assert.equal(explicitRolls('如果决定动手，请掷1d20。',[{id:'hero'}]).length,0);const f=await fixture();let calls=0;const provider=http.createServer(async(req,res)=>{for await(const p of req){}calls++;res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'请掷 1d20+3，DC 15（手动，报数字）。\n≥15守卫信了；<15守卫起疑。'}}]}))});await new Promise(r=>provider.listen(0,'127.0.0.1',r));try{await f.ok('settings.set',{baseUrl:'http://127.0.0.1:'+provider.address().port,model:'test'});await f.ok('ai.chat',{message:'我说服守卫'});assert.equal(calls,1);const d=(await f.ok('dice.pending')).pending[0];assert.equal(d.expr,'1d20+3');assert.equal(d.dc,15);assert.ok(!assemblePrompt({mode:'combat'}).includes('凡戴尔'));}finally{await f.close();await new Promise(r=>provider.close(r))}});

test('death saves and utility movement obey current turns; other mutations cannot bypass a pending action',async()=>{const f=await fixture();try{await f.ok('battle.utility',{actorId:'hero',kind:'disengage'});await perform(f,{actorId:'hero',abilityId:'move',x:2,y:5},'safe-retreat');assert.equal((await f.ok('battle.get')).active,null);assert.equal((await f.ok('map.get')).tokens.find(t=>t.id==='hero').y,5);await f.ok('battle.endTurn');await f.ok('battle.endTurn');await f.ok('combat.damage',{id:'hero',amount:-50});await f.ok('battle.deathSave');const req=(await f.ok('dice.pending')).pending[0];assert.equal(req.label,'死亡豁免');assert.equal((await f.api('combat.mode',{mode:'free'})).ok,false);await f.restart();const result=await f.ok('dice.answer',{id:req.id});const pc=(await f.ok('battle.get')).actors[0];if(result.total===20)assert.equal(pc.hp.current,1);else assert.equal(pc.death.success+pc.death.failure,result.total===1?2:1);assert.equal((await f.api('battle.deathSave')).ok,false);}finally{await f.close()}});

test('a fighter can make extra attacks but cannot spend the same action on another ability',async()=>{const f=await fixture();try{const file=path.join(f.root,'characters/hero.json'),pc=JSON.parse(await fs.readFile(file,'utf8'));pc.classes=[{class:'fighter',level:5}];pc.level=5;await fs.writeFile(file,JSON.stringify(pc));const args={actorId:'hero',abilityId:'weapon',targetIds:['g1'],autoDice:true};assert.equal((await f.ok('battle.preview',args)).ability.maxAttacks,2);await perform(f,args,'attack-a');assert.equal((await f.ok('battle.get')).active,null);await perform(f,args,'attack-b');assert.equal((await f.api('battle.preview',args)).ok,false);assert.equal((await f.api('battle.utility',{actorId:'hero',kind:'dash'})).ok,false);}finally{await f.close()}});


test('unknown enemy AC is rejected before consuming resources',async()=>{const f=await fixture();try{await f.ok('map.token.add',{token:{id:'unknown-ac',name:'ZZQX987未定义单位',kind:'enemy',x:2,y:3,hp:12,max:12,ac:null}});const r=await f.api('battle.preview',{actorId:'hero',abilityId:'weapon',targetIds:['unknown-ac']});assert.equal(r.ok,false);assert.match(r.error,/AC/);assert.equal((await f.ok('combat.get')).order.find(e=>e.pcId==='hero').econ.action,undefined);}finally{await f.close()}});

test('story equipment updates once and projects AC to character, combat, map and DM scene',async()=>{const f=await fixture();try{
 const grant={actorId:'hero',changeId:'story-leather',reason:'卫兵赠送皮甲',item:{key:'leather',name:'皮甲'}};
 await f.ok('character.update',grant);assert.equal((await f.ok('party.sheet',{id:'hero'})).sheet.ac,12);
 await f.ok('dm.action',{action:'character',actorId:'hero',changeId:'wear-leather',reason:'玩家确认穿戴皮甲',slot:'armor',key:'leather'});
 await f.ok('character.update',{actorId:'hero',changeId:'story-shield',reason:'玩家确认持盾',item:{key:'shield',name:'盾牌'},slot:'shield'});
 assert.equal((await f.ok('party.sheet',{id:'hero'})).sheet.ac,15);assert.equal((await f.ok('map.get')).tokens.find(t=>t.id==='hero').ac,15);assert.equal((await f.ok('combat.get')).order.find(e=>e.pcId==='hero').ac,15);
 await f.restart();assert.equal((await f.ok('character.update',Object.fromEntries(Object.entries(grant).reverse()))).duplicate,true);const sheet=(await f.ok('party.sheet',{id:'hero'})).sheet;assert.equal(sheet.inventory.find(i=>i.key==='leather').qty,1);assert.equal((await f.api('character.update',{...grant,reason:'different'})).ok,false);
 const scene=await f.ok('scene.get');assert.ok(JSON.stringify(scene).includes('皮甲'));assert.ok(JSON.stringify(scene).includes('"ac":15'));
 await f.ok('character.update',{actorId:'hero',changeId:'remove-shield',reason:'交还盾牌',removeKey:'shield'});assert.equal((await f.ok('map.get')).tokens.find(t=>t.id==='hero').ac,13);
}finally{await f.close()}});

test('temporary HP, maximum HP and AC buffs share the character state and expire without permanent equipment changes',async()=>{const f=await fixture();try{
 await f.ok('effect.add',{actorId:'hero',targetId:'hero',name:'测试生命增益',maxHpBonus:5,durationSeconds:60});
 await f.ok('effect.add',{actorId:'hero',targetId:'hero',name:'测试临时生命',temp:7,durationSeconds:60});
 const shield=await f.ok('effect.add',{actorId:'hero',targetId:'hero',name:'护盾术',acBonus:5,durationSeconds:6});
 let s=(await f.ok('party.sheet',{id:'hero'})).sheet;assert.equal(s.hp.max,55);assert.equal(s.hp.temp,7);assert.equal(s.hp.effects.length,2);assert.equal(s.ac,17);assert.equal((await f.ok('map.get')).tokens.find(t=>t.id==='hero').max,55);
 await f.ok('combat.damage',{id:'hero',amount:-9});s=(await f.ok('party.sheet',{id:'hero'})).sheet;assert.equal(s.hp.temp,0);assert.equal(s.hp.cur,53);
 await f.ok('combat.mode',{mode:'free'});await f.ok('session.advance',{seconds:60});s=(await f.ok('party.sheet',{id:'hero'})).sheet;assert.equal(s.hp.max,50);assert.equal(s.hp.cur,48);assert.equal(s.ac,12);assert.equal(s.hp.effects.length,0);
}finally{await f.close()}});

test('local actions wait for end turn; duplicate end-turn clicks do not skip a unit',async()=>{const f=await fixture();try{
 await perform(f,{actorId:'hero',abilityId:'move',x:2,y:3},'one-move');assert.equal((await f.ok('session.pending')).ready,false);
 const before=await f.ok('battle.get');await f.ok('battle.endTurn',{turnKey:before.turnKey});assert.equal((await f.ok('battle.endTurn',{turnKey:before.turnKey})).duplicate,true);const after=await f.ok('battle.get');assert.equal(after.actorId,'g1');assert.equal(after.playerId,'hero');assert.equal(after.player.sheet.hp.cur,50);assert.equal((await f.ok('session.pending')).ready,true);
}finally{await f.close()}});

test('DM text-tool compatibility writes story gear and end-turn sends authoritative state',async()=>{const f=await fixture();let mode='gear',received=[];const provider=http.createServer(async(req,res)=>{let text='';for await(const p of req)text+=p;const body=JSON.parse(text);received.push(body);res.setHeader('content-type','application/json');const content=mode==='gear'?'```dm-action\n'+JSON.stringify({action:'character',actorId:'hero',changeId:'dm-leather',reason:'剧情奖励并确认穿戴皮甲',item:{key:'leather',name:'皮甲'},slot:'armor'})+'\n```':'回合已接收。';mode='reply';res.end(JSON.stringify({choices:[{message:{role:'assistant',content}}]}))});await new Promise(r=>provider.listen(0,'127.0.0.1',r));try{await f.ok('settings.set',{baseUrl:'http://127.0.0.1:'+provider.address().port,model:'test'});await f.ok('ai.chat',{message:'穿上刚获得的皮甲'});assert.equal((await f.ok('party.sheet',{id:'hero'})).sheet.ac,13);assert.ok(received[0].tools.some(t=>t.function.name==='character_update'));await perform(f,{actorId:'hero',abilityId:'move',x:2,y:3},'dm-move');await f.ok('battle.endTurn');await f.ok('session.resume');const context=received.at(-1).messages[0].content;assert.ok(context.includes('皮甲'));assert.match(context,/"ac":13/);assert.match(context,/"x":2,"y":3/);}finally{await f.close();await new Promise(r=>provider.close(r))}});

test('character projection retains timed combat conditions until their correct turn expires',async()=>{const f=await fixture();try{await f.ok('combat.conditions',{id:'hero',add:[{key:'poisoned',rounds:2}]});await f.ok('character.update',{actorId:'hero',changeId:'timed-gear',reason:'测试期间装备皮甲',item:{key:'leather',name:'皮甲'},slot:'armor'});assert.equal((await f.ok('combat.get')).order.find(e=>e.pcId==='hero').conditions[0].rounds,2);await f.ok('battle.endTurn');await f.ok('battle.endTurn');assert.equal((await f.ok('combat.get')).order.find(e=>e.pcId==='hero').conditions[0].rounds,1);await f.ok('battle.endTurn');await f.ok('battle.endTurn');assert.equal((await f.ok('party.sheet',{id:'hero'})).sheet.conditions.length,0);}finally{await f.close()}});

test('surprised NPC has a real turn, cannot act/react, then advances to the player and expires',async()=>{const f=await fixture(true);try{await f.ok('dm.action',{action:'surprise',actorIds:['g1'],reason:'DM判定未察觉埋伏'});assert.equal((await f.api('battle.preview',{actorId:'g1',abilityId:'weapon',targetIds:['hero']})).ok,false);const r=await f.ok('battle.advance');assert.equal(r.status,'player_turn');assert.equal((await f.ok('battle.get')).actorId,'hero');assert.equal((await f.ok('map.get')).tokens.find(t=>t.id==='hero').hp,50);assert.ok((await f.ok('battle.get')).events.some(e=>e.text.includes('空过')));assert.equal((await f.ok('combat.get')).order.find(e=>e.tokenId==='g1').conditions.length,0);await f.ok('battle.endTurn');assert.equal((await f.api('battle.surprise',{actorIds:['g1'],reason:'重复突袭'})).ok,false);assert.equal((await f.ok('battle.preview',{actorId:'g1',abilityId:'weapon',targetIds:['hero']})).ok,true);}finally{await f.close()}});

test('NPC end turn requires current identity and version; shared logs include legacy DM damage and turns',async()=>{const f=await fixture(true);try{const b=await f.ok('battle.get');assert.equal((await f.api('battle.npcEnd',{actorId:'hero',turnKey:b.turnKey,reason:'跳玩家'})).ok,false);await f.ok('dm.action',{action:'npcEnd',actorId:'g1',turnKey:b.turnKey,reason:'敌人待命'});assert.equal((await f.api('battle.npcEnd',{actorId:'g1',turnKey:b.turnKey,reason:'重复'})).ok,false);await f.ok('combat.damage',{id:'g1',amount:-2});const next=await f.ok('battle.get');assert.equal(next.actorId,'hero');assert.ok(next.events.some(e=>e.text.includes('敌人待命')));assert.ok(next.events.some(e=>e.text.includes('生命值结算')));}finally{await f.close()}});

test('ordinary Goblin A/B names bind real AC without overwriting injured HP; free stealth records intent without starting combat',async()=>{const f=await fixture();try{await f.ok('combat.mode',{mode:'free'});await f.ok('map.token.add',{token:{id:'gA',name:'地精A',kind:'enemy',x:8,y:8,hp:3,max:7}});const m=(await f.ok('battle.get')).map.tokens.find(t=>t.id==='gA');assert.equal(m.ac,15);assert.equal(m.hp,3);assert.ok(m.statblockId);await f.ok('battle.begin',{actorId:'hero',abilityId:'stealth'});const req=(await f.ok('session.pending')).request;assert.equal(req.exploration,true);await f.ok('interaction.answer',{id:req.id,targetIds:['hero']});const pending=await f.ok('session.pending');assert.equal(pending.ready,true);assert.equal(pending.combat.active,false);assert.ok(pending.completed.some(e=>e.battleAbility==='stealth'));}finally{await f.close()}});

test('NPC continuation completes attacks and returns control instead of stalling on spent action',async()=>{const f=await fixture(true);try{const r=await f.ok('battle.advance');assert.equal(r.status,'player_turn');assert.equal((await f.ok('battle.get')).actorId,'hero');const events=(await f.ok('battle.get')).events.length;await f.ok('battle.advance');assert.equal((await f.ok('battle.get')).events.length,events);}finally{await f.close()}});

test('unexecuted and failed DM turn claims are replaced with the actual current turn',async()=>{const f=await fixture(true);let failed=false;const provider=http.createServer(async(req,res)=>{for await(const p of req){}res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'我已经跳过地精回合，现在交给你。',...(failed?{tool_calls:[{id:'bad-skip',type:'function',function:{name:'battle_npcEnd',arguments:JSON.stringify({actorId:'hero',turnKey:'1:e',reason:'错误角色'})}}]}:{})}}]}))});await new Promise(r=>provider.listen(0,'127.0.0.1',r));try{await f.ok('settings.set',{baseUrl:'http://127.0.0.1:'+provider.address().port,model:'test',maxSteps:2});const plain=await f.ok('ai.chat',{message:'让敌人空过'});assert.match(plain.reply,/尚无成功/);assert.equal((await f.ok('battle.get')).actorId,'g1');failed=true;const bad=await f.ok('ai.chat',{message:'继续'});assert.match(bad.reply,/未完整执行/);assert.equal((await f.ok('battle.get')).actorId,'g1');}finally{await f.close();await new Promise(r=>provider.close(r))}});

test('initiative requests gate the enemy driver, and surprise remains until the affected turn ends',async()=>{const f=await fixture();try{await f.ok('combat.end');await f.ok('combat.start');let dice=(await f.ok('dice.pending')).pending;assert.ok(dice.some(d=>d.kind==='initiative'));assert.equal((await f.ok('battle.advance')).status,'waiting_player');for(const d of dice)await f.ok('dice.answer',{id:d.id});assert.equal((await f.ok('dice.pending')).pending.length,0);await f.ok('combat.end');await f.ok('combat.start',{entries:[{id:'p',tokenId:'hero',pcId:'hero',kind:'pc',name:'玩家',init:20,hp:50,max:50},{id:'e',tokenId:'g1',kind:'enemy',name:'地精',init:10,hp:50,max:50,conditions:[{key:'surprised',rounds:1}]}]});await f.ok('battle.endTurn');assert.equal((await f.ok('battle.get')).combat.order.find(e=>e.id==='e').conditions[0].key,'surprised');await f.ok('battle.advance');assert.equal((await f.ok('battle.get')).actorId,'hero');}finally{await f.close()}});
import {meleeProfile,completeAttack} from '../src/combat-state.mjs';
import {toolsForMode} from '../src/ai-prompts.mjs';
import {createModuleStore} from '../src/modules.mjs';

test('PDF split attack fragments and alternate hit notation bind without borrowing another creature',()=>{
 const expected={attackBonus:4,damage:'1d6+2',reach:5};
 assert.deepEqual(meleeProfile({actions:['弯刀。近战武器攻击：命中+4，触及 5 尺，单一目','标。','伤害：5（1d6+2）。短弓。远程武器攻击：命中+4，伤害1d6+2']}),expected);
 assert.deepEqual(meleeProfile({actions:['近战武器攻击：＋4命中，触及5尺。伤害（1 d 6 ＋ 2）']}),expected);
 assert.deepEqual(meleeProfile({actions:['Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 5 (1d6+2).']}),expected);
 assert.deepEqual(meleeProfile({actions:['近战武器攻击：命中+4，触及5尺。','另一个怪物 AC：15 HP：7 近战武器攻击：命中+6，触及5尺。伤害2d6+4']}),{});
 assert.equal(completeAttack({attackBonus:null,damage:'1d6+2',reach:5}),false);
});

test('imported split statblock repairs old bindings; map replacements and restart preserve attacks; free moves never drive enemies',async()=>{
 const f=await fixture(true);try{
  await f.ok('combat.mode',{mode:'free'});
  const store=createModuleStore(f.root);await store.import('synthetic.md',Buffer.from('地精\n小型类人生物\nAC：15\nHP：7（2d6）\n速度：30尺\n动作\n弯刀。近战武器攻击：命中+4，触及5尺，单一目\n标。\n伤害：5（1d6+2）的挥砍伤害。'));
  const entry=(await store.entries())[0];assert.ok(entry);
  await f.ok('map.token.add',{token:{id:'pdf',name:'地精A',kind:'enemy',x:6,y:6,hp:3,max:7,statblockId:entry.id}});
  const bound=await f.ok('enemy.bind',{tokenId:'pdf',statblockId:entry.id});assert.equal(bound.attackReady,true);assert.equal(bound.token.hp,3);assert.equal(bound.token.damage,'1d6+2');
  let map=await f.ok('map.get');await f.ok('map.set',map);
  await f.ok('map.batch',{ops:[{add:{id:'custom',name:'合成测试单位',kind:'enemy',x:8,y:8,attackBonus:6,damage:'2d4+3',reach:10}}]});
  await f.restart();map=await f.ok('map.get');assert.equal(map.tokens.find(t=>t.id==='pdf').damage,'1d6+2');assert.equal(map.tokens.find(t=>t.id==='custom').attackBonus,6);
  for(const x of [4,5,6])await f.ok('map.token.move',{id:'hero',x,y:4});
  const before=await f.ok('combat.get'),hp=(await f.ok('party.sheet',{id:'hero'})).sheet.hp;
  for(let n=0;n<3;n++)assert.equal((await f.ok('battle.enemy')).status,'exploration');
  assert.deepEqual(await f.ok('combat.get'),before);assert.deepEqual((await f.ok('party.sheet',{id:'hero'})).sheet.hp,hp);assert.equal((await f.ok('dice.pending')).pending.length,0);
  const ts=['battle_enemy','battle_advance','battle_npcEnd','battle_surprise','battle_begin','combat_start'].map(name=>({function:{name}}));assert.deepEqual(toolsForMode(ts,'explore').map(t=>t.function.name),['battle_begin','combat_start']);
 }finally{await f.close()}
});

test('mage hand creates a noncombat effect, moves by owner action, expires and cannot bypass range or economy',async()=>{
 const f=await fixture();try{
  const file=path.join(f.root,'characters/hero.json'),pc=JSON.parse(await fs.readFile(file,'utf8'));pc.spellcasting.cantrips.push('mageHand');await fs.writeFile(file,JSON.stringify(pc));
  assert.equal((await f.api('battle.preview',{actorId:'hero',abilityId:'mageHand',x:10,y:10})).ok,false);
  const args={actorId:'hero',abilityId:'mageHand',x:5,y:5};await perform(f,args,'hand-cast');
  let b=await f.ok('battle.get'),hand=b.map.tokens.find(t=>t.spell==='mageHand');assert.ok(hand);assert.equal(hand.ownerId,'hero');assert.ok(!b.combat.order.some(e=>e.tokenId===hand.id));assert.equal(b.combat.order[0].econ.action,true);assert.equal(b.effects.find(e=>e.tokenId===hand.id).remainingSeconds,60);
  assert.equal((await f.api('battle.preview',{actorId:'hero',abilityId:'mageHandControl',x:6,y:5})).ok,false);
  await f.ok('combat.mode',{mode:'free'});await perform(f,{actorId:'hero',abilityId:'mageHandControl',x:6,y:5},'hand-control');assert.equal((await f.ok('map.get')).tokens.find(t=>t.id===hand.id).x,6);
  assert.equal((await f.api('map.token.move',{id:hand.id,x:11,y:11})).ok,false);
  await perform(f,args,'hand-recast');b=await f.ok('battle.get');assert.equal(b.map.tokens.filter(t=>t.spell==='mageHand').length,1);assert.notEqual(b.map.tokens.find(t=>t.spell==='mageHand').id,hand.id);
  await f.restart();assert.equal((await f.ok('battle.get')).map.tokens.filter(t=>t.spell==='mageHand').length,1);
  await f.ok('session.advance',{seconds:60});assert.equal((await f.ok('map.get')).tokens.filter(t=>t.spell==='mageHand').length,0);
  const req=await f.ok('battle.begin',{actorId:'hero',abilityId:'mageHand'});assert.equal(req.request.kind,'point');await f.ok('interaction.answer',{id:req.request.id,x:2,y:3});
  await f.ok('map.token.move',{id:'hero',x:11,y:11});assert.equal((await f.ok('battle.get')).map.tokens.filter(t=>t.spell==='mageHand').length,0);
 }finally{await f.close()}
});

test('concurrent DM resume is processing not failure, starts one provider call and clears state',async()=>{
 const f=await fixture();let calls=0,release,entered;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);
 const provider=http.createServer(async(req,res)=>{for await(const p of req){}calls++;entered();await gate;res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'已读取探索状态。'}}]}))});await new Promise(r=>provider.listen(0,'127.0.0.1',r));
 try{await f.ok('combat.mode',{mode:'free'});await f.ok('settings.set',{baseUrl:'http://127.0.0.1:'+provider.address().port,model:'test'});await f.ok('battle.explore',{actorId:'hero'});const first=f.ok('session.resume');await started;assert.equal((await f.ok('session.pending')).resuming,true);assert.equal((await f.ok('session.pending')).ready,false);assert.equal((await f.ok('session.resume')).status,'processing');release();await first;assert.equal(calls,1);assert.equal((await f.ok('session.pending')).resuming,false);assert.equal((await f.ok('session.pending')).ready,false);
 }finally{release();await f.close();await new Promise(r=>provider.close(r))}
});

test('AI deadline aborts stalled response and releases both resume and chat locks',async t=>{
 const f=await fixture();let slow=true;
 const provider=http.createServer(async(req,res)=>{for await(const p of req){}if(slow)return;res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'连接已恢复。'}}]}))});await new Promise(r=>provider.listen(0,'127.0.0.1',r));
 const timeout=AbortSignal.timeout;t.mock.method(AbortSignal,'timeout',ms=>timeout(ms===120000?100:ms));
 try{await f.ok('combat.mode',{mode:'free'});await f.ok('settings.set',{baseUrl:'http://127.0.0.1:'+provider.address().port,model:'test'});await f.ok('battle.explore',{actorId:'hero'});assert.equal((await f.api('session.resume')).ok,false);const pending=await f.ok('session.pending');assert.equal(pending.resuming,false);assert.equal(pending.ready,false);assert.ok(pending.retryAt>Date.now());slow=false;t.mock.restoreAll();assert.ok((await f.ok('ai.chat',{message:'重试'})).reply.includes('连接已恢复'));
 }finally{t.mock.restoreAll();provider.closeAllConnections();await f.close();await new Promise(r=>provider.close(r))}
});
