import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';
import {startServer} from '../server.mjs';import {initializeData} from '../desktop/storage.mjs';import {createModuleStore} from '../src/modules.mjs';import {assemblePrompt} from '../src/ai-prompts.mjs';
async function setup(){const home=await fs.mkdtemp(path.join(os.tmpdir(),'solo-lobby-')),root=await initializeData(home,'0.12.0');const store=createModuleStore(root);const mod=await store.import('Test.md',Buffer.from('# 测试冒险\n一个庭院与门口的守卫。'));let app=await startServer({dataRoot:root,port:0});const api=async(op,args={})=>{const r=await(await fetch(app.url+'/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op,args})})).json();if(!r.ok)throw Error(r.error);return r.value};return {home,root,api,moduleId:(await store.list())[0].id,restart:async()=>{await app.close();app=await startServer({dataRoot:root,port:0})},close:async()=>{await app.close();await fs.rm(home,{recursive:true,force:true})}}}
test('profiles isolate characters, module, chat and combat across switches and restart; legacy data survives',async()=>{const f=await setup();try{
 const old=await f.api('party.list');await f.api('dm.player',{message:'原有对话'});const p=await f.api('profiles.create',{name:'新战役',moduleId:f.moduleId,aidm:false});assert.equal(p.ok,true);assert.equal((await f.api('party.list')).items.length,0);assert.equal((await f.api('controls.get')).aidm,false);assert.equal((await f.api('ai.history')).messages.length,0);assert.equal((await f.api('campaign.get')).moduleId,f.moduleId);
 await f.api('dm.player',{message:'新战役对话'});await f.restart();assert.equal((await f.api('profiles.list')).active,p.id);assert.equal((await f.api('campaign.get')).modules.length,1);assert.equal((await f.api('ai.history')).messages[0].content,'新战役对话');await f.api('profiles.select',{id:'legacy'});assert.equal((await f.api('party.list')).items.length,old.items.length);assert.equal((await f.api('ai.history')).messages[0].content,'原有对话');await assert.rejects(()=>f.api('profiles.select',{id:'../../escape'}),/存档不存在/);
 }finally{await f.close()}});
test('manual DM disables automatic AI and helpers cannot mutate roles; in-flight calls prevent save switching',async()=>{const f=await setup();let calls=0,release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);let wait=false;const seen=[];
 const provider=http.createServer(async(req,res)=>{let raw='';for await(const p of req)raw+=p;const body=JSON.parse(raw);seen.push(body);calls++;if(wait){entered();await gate}res.setHeader('content-type','application/json');res.end(JSON.stringify({usage:{prompt_tokens:100,completion_tokens:20},choices:[{message:{role:'assistant',content:'规则建议：先确认可见性。'}}]}))});await new Promise(r=>provider.listen(0,'127.0.0.1',r));try{
 await f.api('settings.set',{baseUrl:'http://127.0.0.1:'+provider.address().port,model:'test'});await f.api('controls.set',{aidm:false});assert.equal((await f.api('ai.chat',{message:'继续'})).ok,false);assert.equal((await f.api('session.resume',{continueEnemies:true})).status,'manual_dm');assert.equal(calls,0);
 const r=await f.api('ai.chat',{message:'可见性如何判定？',assistantTool:'rules'});assert.equal(r.ok,true,r.error);assert.ok(!seen[0].tools.some(t=>/damage|update|dm_action/.test(t.function.name)));assert.equal((await f.api('ai.history')).messages.length,0);assert.equal((await f.api('ai.usage')).prompt_tokens,100);assert.equal(seen[0].max_tokens,1200);
 wait=true;const pending=f.api('ai.chat',{message:'再查一条',assistantTool:'rules'});await started;assert.equal((await f.api('profiles.select',{id:'legacy'})).ok,false);release();await pending;
 }finally{release();await f.close();await new Promise(r=>provider.close(r))}});
test('compact AI state removes large terrain/area copies while retaining HP, spell identity and positions',()=>{const scene={map:{id:'m',w:80,h:60,terrain:Array(60).fill('.'.repeat(80)),tokens:[{id:'hero',kind:'pc',x:4,y:7,hp:9,ac:14}]},effects:[{name:'浓雾',spell:'fogCloud',area:{cells:Array.from({length:4800},(_,i)=>({x:i%80,y:Math.floor(i/80)}))}}],characters:[{id:'hero',name:'法师',hp:{cur:9,max:10},spells:[{key:'fogCloud',name:'云雾术'}]}]};const compact=assemblePrompt({scene});assert.ok(compact.length<JSON.stringify(scene).length/4);assert.ok(compact.includes('fogCloud'));assert.ok(compact.includes('"x":4,"y":7'));});
